"""Re-export attachment helpers (GUI package convenience; no Qt)."""

from survyai.attachments import (
    ARCHIVE_EXTENSIONS,
    ATTACHABLE_EXTENSIONS,
    ATTACHMENTS_END,
    ATTACHMENTS_START,
    CAD_EXTENSIONS,
    DEFAULT_ATTACHMENTS_ONLY_PROMPT,
    DOCUMENT_EXTENSIONS,
    GIS_EXTENSIONS,
    IMAGE_EXTENSIONS,
    PRESENTATION_EXTENSIONS,
    SPREADSHEET_EXTENSIONS,
    SURVEY_DATA_EXTENSIONS,
    TEXT_EXTENSIONS,
    attach_unsupported_message,
    attachment_kind,
    collect_attached_paths,
    display_label_for_attachment,
    file_dialog_filters,
    format_attachments_block,
    format_user_transcript,
    is_attachable_path,
    is_image_path,
    max_file_mb_for_path,
    parse_attachments_block,
)

__all__ = [
    "ARCHIVE_EXTENSIONS",
    "ATTACHABLE_EXTENSIONS",
    "ATTACHMENTS_END",
    "ATTACHMENTS_START",
    "CAD_EXTENSIONS",
    "DEFAULT_ATTACHMENTS_ONLY_PROMPT",
    "DOCUMENT_EXTENSIONS",
    "GIS_EXTENSIONS",
    "IMAGE_EXTENSIONS",
    "PRESENTATION_EXTENSIONS",
    "SPREADSHEET_EXTENSIONS",
    "SURVEY_DATA_EXTENSIONS",
    "TEXT_EXTENSIONS",
    "attach_unsupported_message",
    "attachment_kind",
    "collect_attached_paths",
    "display_label_for_attachment",
    "file_dialog_filters",
    "format_attachments_block",
    "format_user_transcript",
    "is_attachable_path",
    "is_image_path",
    "max_file_mb_for_path",
    "parse_attachments_block",
]
