# Generated by SurvyAI
# This script was dynamically generated based on user request
# Generated: 2026-04-03T11:36:17.896041
# 
# Execute this script in ArcGIS Pro's Python Window if needed:
# exec(open(r'C:\Users\UZOR\PycharmProjects\untitled\venv\SurvyAI\Adibawa_BorrowPit_Volume\scripts\Adibawa_BorrowPit_Volume_finalize_visualization.py').read())


import os
import arcpy

project_path = r"C:\Users\UZOR\PycharmProjects\untitled\venv\SurvyAI\Adibawa_BorrowPit_Volume\Adibawa_BorrowPit_Volume.aprx"
project_dir = r"C:\Users\UZOR\PycharmProjects\untitled\venv\SurvyAI\Adibawa_BorrowPit_Volume"
gdb_path = r"C:\Users\UZOR\PycharmProjects\untitled\venv\SurvyAI\Adibawa_BorrowPit_Volume\Adibawa_BorrowPit_Volume.gdb"

aprx = arcpy.mp.ArcGISProject(project_path)
maps = aprx.listMaps()

basemap_loaded = False
gdb_loaded = False
feature_classes_loaded = []

# Prefer the project's own geodatabase as the default, so it appears under Databases
try:
    if os.path.exists(gdb_path):
        aprx.defaultGeodatabase = gdb_path
except Exception:
    pass

# Add a folder connection to the project directory (so the .gdb is easy to find in Catalog)
try:
    aprx.addFolderConnection(project_dir)
except Exception:
    pass

# Load basemap
if True:
    for m in maps:
        try:
            # Try common basemap name variations
            basemap_names = [
                "Imagery Hybrid",
                "Imagery Hybrid",
                "ImageryHybrid",
                "Imagery_Hybrid",
                "ImageHybrid",
                "Image_Hybrid",
            ]
            for bm_name in basemap_names:
                try:
                    m.addBasemap(bm_name)
                    basemap_loaded = True
                    print("RESULT_BASEMAP_LOADED:", bm_name, "on map:", m.name)
                    break
                except Exception:
                    continue
            if not basemap_loaded:
                # Fallback: try to list available basemaps and use first imagery hybrid one
                try:
                    available = m.listBasemaps()
                    for bm in available:
                        if "imagery" in bm.name.lower() and "hybrid" in bm.name.lower():
                            m.addBasemap(bm.name)
                            basemap_loaded = True
                            print("RESULT_BASEMAP_LOADED:", bm.name, "on map:", m.name)
                            break
                except Exception as e:
                    print("RESULT_BASEMAP_WARNING:", str(e))
        except Exception as e:
            print("RESULT_BASEMAP_ERROR:", str(e))

# Load native geodatabase and all feature classes
if True and os.path.exists(gdb_path):
    for m in maps:
        try:
            # List all feature classes in the geodatabase
            fcs = []
            for dirpath, dirnames, filenames in arcpy.da.Walk(gdb_path, datatype="FeatureClass"):
                for filename in filenames:
                    fc_path = os.path.join(dirpath, filename)
                    if arcpy.Exists(fc_path):
                        fcs.append(fc_path)
            
            # Add each feature class to the map (if not already present)
            for fc_path in fcs:
                try:
                    # Check if layer already exists
                    fc_name = os.path.basename(fc_path)
                    existing = [lyr.name for lyr in m.listLayers() if lyr.name == fc_name]
                    if not existing:
                        m.addDataFromPath(fc_path)
                        feature_classes_loaded.append(fc_name)
                        print("RESULT_FC_LOADED:", fc_name, "on map:", m.name)
                except Exception as e:
                    print("RESULT_FC_WARNING:", fc_name, ":", str(e))
            
            if fcs:
                gdb_loaded = True
                print("RESULT_GDB_LOADED:", gdb_path, "with", len(fcs), "feature classes")
        except Exception as e:
            print("RESULT_GDB_ERROR:", str(e))

aprx.save()
print("RESULT_FINALIZATION_COMPLETE")

