# ArcGIS Pro Project Creation Script
# Generated by SurvyAI
# Project: BorrowPit_Volume_Project_IDW
# Coordinate System: EPSG:26392 (WKID: 26392)

import arcpy
import os
import glob

print("=" * 60)
print("SurvyAI - Creating ArcGIS Pro Project")
print("=" * 60)

# Configuration
project_name = "BorrowPit_Volume_Project_IDW"
project_dir = "C:/Users/UZOR/PycharmProjects/untitled/venv/SurvyAI/BorrowPit_Volume_Project_IDW"
project_path = "C:/Users/UZOR/PycharmProjects/untitled/venv/SurvyAI/BorrowPit_Volume_Project_IDW/BorrowPit_Volume_Project_IDW.aprx"
template_type = "MAP"
wkid = 26392
clean_layers = True

# Create project directory
os.makedirs(project_dir, exist_ok=True)
print("Project directory:", project_dir)

try:
    # Get ArcGIS Pro version info
    install_info = arcpy.GetInstallInfo()
    version = install_info.get("Version", "unknown")
    install_dir = install_info["InstallDir"]
    print("ArcGIS Pro version:", version)
    print("Install directory:", install_dir)
    
    # Search for template files in multiple locations
    template_paths_to_check = [
        os.path.join(install_dir, "Resources", "ProjectTemplates"),
        os.path.join(install_dir, "Resources", "Core", "ProjectTemplates"),
        os.path.join(os.path.expanduser("~"), "AppData", "Local", "ESRI", "ArcGISPro", "ProjectTemplates"),
        os.path.join(os.path.expanduser("~"), "AppData", "Roaming", "ESRI", "ArcGISPro", "ProjectTemplates"),
        os.path.join(os.path.expanduser("~"), "Documents", "ArcGIS", "ProjectTemplates"),
    ]
    
    template_found = None
    all_templates = []
    
    # Also search for .aprx files in template directories (some versions use .aprx as templates)
    for template_dir in template_paths_to_check:
        if os.path.exists(template_dir):
            templates_aptx = glob.glob(os.path.join(template_dir, "*.aptx"))
            templates_aprx = glob.glob(os.path.join(template_dir, "*.aprx"))
            all_templates.extend(templates_aptx)
            all_templates.extend(templates_aprx)
            total = len(templates_aptx) + len(templates_aprx)
            if total > 0:
                print("Found", total, "templates in:", template_dir)
    
    # Prefer templates matching the requested type
    template_preferences = {
        "MAP": ["map", "blank"],
        "CATALOG": ["catalog"],
        "GLOBAL_SCENE": ["global", "scene"],
        "LOCAL_SCENE": ["local", "scene"]
    }
    
    preferred_names = template_preferences.get(template_type, ["map", "blank"])
    
    for template_file in all_templates:
        tname_lower = os.path.basename(template_file).lower()
        if any(pref in tname_lower for pref in preferred_names):
            template_found = template_file
            print("Selected matching template:", template_file)
            break
    
    # If no matching template, use first available
    if not template_found and all_templates:
        template_found = all_templates[0]
        print("Using first available template:", template_found)
    
    if template_found:
        print("Creating project from template:", template_found)
        aprx = arcpy.mp.ArcGISProject(template_found)
        print("Project object created successfully")
    else:
        # No templates found - try to find any existing .aprx project to use as template
        print("No .aptx templates found. Searching for existing projects to use as template...")
        existing_project_paths = [
            os.path.join(os.path.expanduser("~"), "Documents", "ArcGIS", "Projects"),
        ]
        
        existing_project = None
        for proj_dir in existing_project_paths:
            if os.path.exists(proj_dir):
                # Look for any .aprx file in subdirectories
                for root, dirs, files in os.walk(proj_dir):
                    for file in files:
                        if file.endswith(".aprx") and file != os.path.basename(project_path):
                            existing_project = os.path.join(root, file)
                            print("Found existing project to use as template:", existing_project)
                            break
                    if existing_project:
                        break
            if existing_project:
                break
        
        if existing_project:
            try:
                print("Using existing project as template:", existing_project)
                aprx = arcpy.mp.ArcGISProject(existing_project)
                print("Opened existing project as template")
            except Exception as e:
                print("Failed to open existing project:", str(e))
                raise Exception("Cannot create project - found existing project but failed to open it. Please create manually in ArcGIS Pro.")
        else:
            # Last resort: try CURRENT (only works if ArcGIS Pro is running with a project open)
            try:
                print("Trying CURRENT project (requires ArcGIS Pro to be running)...")
                aprx = arcpy.mp.ArcGISProject("CURRENT")
                print("Using CURRENT project as base")
            except Exception as e:
                print("CURRENT method failed:", str(e))
                raise Exception("Cannot create project automatically - no templates found. Please create manually: 1) Open ArcGIS Pro, 2) Click 'Map' under 'New Project', 3) Save to: " + project_dir)
    
    # Set coordinate system if specified
    if wkid and wkid > 0:
        maps = aprx.listMaps()
        print("Maps in project:", [m.name for m in maps])
        if maps:
            sr = arcpy.SpatialReference(wkid)
            for m in maps:
                m.spatialReference = sr
            print("Set coordinate system to WKID:", wkid, "(" + 'EPSG:26392' + ")")
        else:
            print("Warning: No maps found in project")

    # Remove any template/sample layers & tables unless explicitly disabled
    if clean_layers:
        try:
            for m in aprx.listMaps():
                for lyr in m.listLayers():
                    try:
                        m.removeLayer(lyr)
                    except Exception:
                        pass
                try:
                    for tbl in m.listTables():
                        try:
                            m.removeTable(tbl)
                        except Exception:
                            pass
                except Exception:
                    pass
            print("Cleaned template layers/tables")
        except Exception as e:
            print("Warning: failed cleaning template layers:", str(e))
    
    # Save the project to the specified path
    print("Saving project to:", project_path)
    aprx.saveACopy(project_path)
    print("Project saved successfully")
    
    # Verify the file was created
    if os.path.exists(project_path):
        file_size = os.path.getsize(project_path)
        print("")
        print("=" * 60)
        print("SUCCESS! Project created:")
        print("  Path:", project_path)
        print("  Size:", file_size, "bytes")
        print("  Coordinate System:", 'EPSG:26392', "WKID:", wkid)
        print("=" * 60)
        exit(0)  # Success exit code
    else:
        print("ERROR: Project file was not created at:", project_path)
        exit(1)

except Exception as e:
    import traceback
    print("")
    print("=" * 60)
    print("ERROR creating project:")
    print("  ", str(e))
    print("")
    print("Full traceback:")
    traceback.print_exc()
    print("=" * 60)
    exit(1)
