# Generated by SurvyAI
# This script was dynamically generated based on user request
# Generated: 2026-06-30T06:25:36.039429
#
# REQUIRED checklist for analyst workflows (IDW, Cut Fill, borrow pits):
# - Use a projected CRS with known linear units for volume; log EPSG/WKID.
# - Add every output feature class/raster to the active map (addDataFromPath / layer objects).
# - project.save() after writes so the open Pro window shows new layers.
#
# Execute this script in ArcGIS Pro's Python Window if needed:
# exec(open(r'C:\Users\UZOR\PycharmProjects\untitled\venv\SurvyAI\Adibawa_TIN_Volume\scripts\Adibawa_TIN_Volume_pre_post_tin_volume.py').read())


import os, csv, time, arcpy
from arcpy.sa import Minus, ExtractByMask, Con

arcpy.env.overwriteOutput = True

project_path = r"C:\Users\UZOR\PycharmProjects\untitled\venv\SurvyAI\Adibawa_TIN_Volume\Adibawa_TIN_Volume.aprx"
workspace = r"C:\Users\UZOR\PycharmProjects\untitled\venv\SurvyAI"
pre_csv = r"C:\Users\UZOR\PycharmProjects\untitled\venv\SurvyAI\csv_adibawa__020416_0411510.csv"
post_csv = r"C:\Users\UZOR\PycharmProjects\untitled\venv\SurvyAI\csv_Adi_post_031618_062229.csv"
dwg_path = r"C:\Users\USER\Documents\SPDC\ADIBAWA WELL 13\Adibawa Well 13A BORROWPIT-Contractor\REVIEW\POST SURVEY FOR ADIBAWA WELL 13 BORROW PIT 13A RESTORATION.dwg"
out_csv = r"C:\Users\UZOR\PycharmProjects\untitled\venv\SurvyAI\Adibawa_VolumeResult.csv"
explicit_wkid = 26392
cad_ref_scale = "1000"

project_dir = os.path.dirname(project_path)
proj_base = os.path.splitext(os.path.basename(project_path))[0]
gdb_path = os.path.join(project_dir, proj_base + ".gdb")
if not arcpy.Exists(gdb_path):
    arcpy.management.CreateFileGDB(project_dir, proj_base + ".gdb")

arcpy.env.workspace = gdb_path
arcpy.env.scratchWorkspace = gdb_path

if arcpy.CheckExtension("3D") != "Available":
    raise RuntimeError("3D Analyst extension is required for CreateTin / TinRaster")
arcpy.CheckOutExtension("3D")
if arcpy.CheckExtension("Spatial") != "Available":
    raise RuntimeError("Spatial Analyst extension is required for volume rasters")
arcpy.CheckOutExtension("Spatial")

aprx = arcpy.mp.ArcGISProject(project_path)
maps = aprx.listMaps()
try:
    aprx.defaultGeodatabase = gdb_path
except Exception:
    pass
try:
    aprx.addFolderConnection(project_dir)
except Exception:
    pass

run_tag = "r" + str(int(time.time()))
cad_name = "cad_import_" + run_tag

def _cad_import():
    # Reference scale + optional SR (matches interactive Pro CAD import fixes)
    sr_proj = arcpy.SpatialReference(int(explicit_wkid)) if explicit_wkid else None
    if sr_proj is not None:
        return arcpy.conversion.CADToGeodatabase(dwg_path, gdb_path, cad_name, cad_ref_scale, sr_proj)
    return arcpy.conversion.CADToGeodatabase(dwg_path, gdb_path, cad_name, cad_ref_scale)

cad_result = _cad_import()
try:
    cad_path = cad_result[0]
except Exception:
    cad_path = os.path.join(gdb_path, cad_name)

polygon_fc = None
polyline_fc = None
for root in [cad_path, gdb_path]:
    try:
        for dirpath, dirnames, filenames in arcpy.da.Walk(root, datatype="FeatureClass"):
            for filename in filenames:
                full = os.path.join(dirpath, filename)
                nm = str(filename).strip().lower()
                if polygon_fc is None and nm == "polygon":
                    polygon_fc = full
                elif polyline_fc is None and nm == "polyline":
                    polyline_fc = full
    except Exception:
        pass
    if polygon_fc or polyline_fc:
        break

temp_poly = os.path.join(gdb_path, "cad_polygonized_" + run_tag)
boundary_fc = os.path.join(gdb_path, "analysis_boundary_" + run_tag)

def _largest_geom(fc):
    best_geom = None
    best_area = -1.0
    with arcpy.da.SearchCursor(fc, ["SHAPE@"]) as cur:
        for (geom,) in cur:
            if geom and float(getattr(geom, "area", 0.0) or 0.0) > best_area:
                best_area = float(getattr(geom, "area", 0.0) or 0.0)
                best_geom = geom
    return best_geom

boundary_geom = None
boundary_sr = None
if polygon_fc and arcpy.Exists(polygon_fc) and int(arcpy.management.GetCount(polygon_fc)[0]) > 0:
    boundary_geom = _largest_geom(polygon_fc)
    boundary_sr = arcpy.Describe(polygon_fc).spatialReference

if boundary_geom is None:
    if (not polyline_fc) or (not arcpy.Exists(polyline_fc)) or int(arcpy.management.GetCount(polyline_fc)[0]) == 0:
        raise RuntimeError("No polygon or polyline boundary found in DWG import")
    arcpy.management.FeatureToPolygon(polyline_fc, temp_poly)
    if not arcpy.Exists(temp_poly) or int(arcpy.management.GetCount(temp_poly)[0]) == 0:
        raise RuntimeError("Could not derive polygon boundary from DWG polylines")
    boundary_geom = _largest_geom(temp_poly)
    boundary_sr = arcpy.Describe(temp_poly).spatialReference

if boundary_geom is None:
    raise RuntimeError("Could not resolve a usable DWG boundary geometry")

sr = arcpy.SpatialReference(int(explicit_wkid)) if explicit_wkid else boundary_sr
if not sr:
    raise RuntimeError("Could not determine spatial reference for TIN (set coordinate_system / EPSG)")

if arcpy.Exists(boundary_fc):
    arcpy.management.Delete(boundary_fc)
if getattr(sr, "factoryCode", 0) and boundary_sr and getattr(boundary_sr, "factoryCode", 0) and sr.factoryCode != boundary_sr.factoryCode:
    try:
        boundary_geom = boundary_geom.projectAs(sr)
    except Exception:
        pass

arcpy.management.CreateFeatureclass(gdb_path, os.path.basename(boundary_fc), "POLYGON", spatial_reference=sr)
with arcpy.da.InsertCursor(boundary_fc, ["SHAPE@"]) as ic:
    ic.insertRow([boundary_geom])

boundary_single = os.path.join(gdb_path, "BOUNDARY_SINGLE_" + run_tag)
if arcpy.Exists(boundary_single):
    arcpy.management.Delete(boundary_single)
arcpy.management.Dissolve(boundary_fc, boundary_single)
try:
    arcpy.management.RepairGeometry(boundary_single)
except Exception:
    pass

def _pick_field(fieldnames, exact_names, contains_names):
    lower_map = {str(f).strip().lower(): f for f in (fieldnames or [])}
    for name in exact_names:
        if name in lower_map:
            return lower_map[name]
    for name in contains_names:
        for key, original in lower_map.items():
            if name in key:
                return original
    return None

def _detect_xyz(csv_path):
    with open(csv_path, "r", newline="", encoding="utf-8-sig") as f:
        reader = csv.DictReader(f)
        fields = reader.fieldnames or []
    xf = _pick_field(fields, ["e", "x"], ["east", "easting", "lon", "long"])
    yf = _pick_field(fields, ["n", "y"], ["north", "northing", "lat"])
    zf = _pick_field(fields, ["z"], ["elev", "elevation", "rl", "level"])
    return fields, xf, yf, zf

def _csv_to_points(csv_path, fc_name):
    fields, xf, yf, zf = _detect_xyz(csv_path)
    if not xf or not yf or not zf:
        raise RuntimeError("Missing usable E/N/Z fields in " + str(csv_path))
    out_fc = os.path.join(gdb_path, fc_name + "_" + run_tag)
    if arcpy.Exists(out_fc):
        arcpy.management.Delete(out_fc)
    arcpy.management.CreateFeatureclass(gdb_path, os.path.basename(out_fc), "POINT", spatial_reference=sr)
    arcpy.management.AddField(out_fc, "ZVAL", "DOUBLE")
    inserted = 0
    with open(csv_path, "r", newline="", encoding="utf-8-sig") as f:
        reader = csv.DictReader(f)
        with arcpy.da.InsertCursor(out_fc, ["SHAPE@XY", "ZVAL"]) as ic:
            for row in reader:
                try:
                    x = float(str(row[xf]).replace(",", "").strip())
                    y = float(str(row[yf]).replace(",", "").strip())
                    z = float(str(row[zf]).replace(",", "").strip())
                except Exception:
                    continue
                ic.insertRow([(x, y), z])
                inserted += 1
    if inserted == 0:
        raise RuntimeError("No usable rows inserted from " + str(csv_path))
    return out_fc, inserted

pre_fc, pre_count = _csv_to_points(pre_csv, "PRE_POINTS")
post_fc, post_count = _csv_to_points(post_csv, "POST_POINTS")

pre_3d = os.path.join(gdb_path, "PRE_3D_" + run_tag)
post_3d = os.path.join(gdb_path, "POST_3D_" + run_tag)
for fc in [pre_3d, post_3d]:
    if arcpy.Exists(fc):
        arcpy.management.Delete(fc)

arcpy.ddd.FeatureTo3DByAttribute(pre_fc, pre_3d, "ZVAL")
arcpy.ddd.FeatureTo3DByAttribute(post_fc, post_3d, "ZVAL")

pre_tin = os.path.join(project_dir, "pre_surface_" + run_tag)
post_tin = os.path.join(project_dir, "post_surface_" + run_tag)

def _createtin_robust(out_tin, pts_3d, clip_fc):
    last_err = None
    strategies = []
    strategies.append([[pts_3d, "Shape.Z", "masspoints"], [clip_fc, "<None>", "hardclip"]])
    strategies.append([[pts_3d, "Shape.Z", "masspoints"]])
    for idx, spec in enumerate(strategies):
        try:
            if arcpy.Exists(out_tin):
                try:
                    arcpy.management.Delete(out_tin)
                except Exception:
                    pass
            arcpy.ddd.CreateTin(out_tin, sr, spec, "DELAUNAY")
            print("RESULT_CREATETIN_OK:", os.path.basename(out_tin), "strategy", idx)
            return idx
        except Exception as e:
            last_err = e
            msg = str(e) + " " + arcpy.GetMessages(2)
            print("RESULT_CREATETIN_TRY_FAILED:", idx, msg)
    raise RuntimeError("CreateTin failed after retries: " + str(last_err))

_createtin_robust(pre_tin, pre_3d, boundary_single)
_createtin_robust(post_tin, post_3d, boundary_single)

desc_b = arcpy.Describe(boundary_single)
ext = desc_b.extent
_w = max(float(ext.XMax) - float(ext.XMin), 1.0)
_h = max(float(ext.YMax) - float(ext.YMin), 1.0)
cell = max(min(_w, _h) / 100.0, 0.5)
arcpy.env.extent = boundary_single
arcpy.env.mask = boundary_single
arcpy.env.outputCoordinateSystem = sr

pre_ras = os.path.join(gdb_path, "pre_tin_ras_" + run_tag)
post_ras = os.path.join(gdb_path, "post_tin_ras_" + run_tag)
for r in [pre_ras, post_ras]:
    if arcpy.Exists(r):
        arcpy.management.Delete(r)

arcpy.ddd.TinRaster(pre_tin, pre_ras, "FLOAT", "LINEAR", "CELLSIZE", cell)
arcpy.ddd.TinRaster(post_tin, post_ras, "FLOAT", "LINEAR", "CELLSIZE", cell)

dz_raster = os.path.join(gdb_path, "dz_tin_" + run_tag)
if arcpy.Exists(dz_raster):
    arcpy.management.Delete(dz_raster)
dz_tmp = Minus(arcpy.sa.Raster(post_ras), arcpy.sa.Raster(pre_ras))
ExtractByMask(dz_tmp, boundary_single).save(dz_raster)

dz_desc = arcpy.Describe(dz_raster)
try:
    cell_area = float(dz_desc.meanCellWidth) * float(dz_desc.meanCellHeight)
except Exception:
    cell_area = float(cell) * float(cell)

oid_field = arcpy.Describe(boundary_single).OIDFieldName
fill_tbl = os.path.join(gdb_path, "tin_fill_sum_" + run_tag)
cut_tbl = os.path.join(gdb_path, "tin_cut_sum_" + run_tag)
for t in [fill_tbl, cut_tbl]:
    if arcpy.Exists(t):
        arcpy.management.Delete(t)

fill_depth = Con(arcpy.sa.Raster(dz_raster) > 0, arcpy.sa.Raster(dz_raster), 0)
cut_depth = Con(arcpy.sa.Raster(dz_raster) < 0, -arcpy.sa.Raster(dz_raster), 0)
arcpy.sa.ZonalStatisticsAsTable(boundary_single, oid_field, fill_depth, fill_tbl, "DATA", "SUM")
arcpy.sa.ZonalStatisticsAsTable(boundary_single, oid_field, cut_depth, cut_tbl, "DATA", "SUM")
del fill_depth
del cut_depth

def _sum_from(tbl):
    flds = [f.name for f in arcpy.ListFields(tbl)]
    sf = next((f for f in flds if (f or "").strip().lower() == "sum"), None) or next(
        (f for f in flds if "sum" in (f or "").strip().lower()), None
    )
    if not sf:
        return 0.0
    with arcpy.da.SearchCursor(tbl, [sf]) as c:
        for (v,) in c:
            return float(v) if v is not None else 0.0
    return 0.0

fill_volume = _sum_from(fill_tbl) * cell_area
cut_volume = -(_sum_from(cut_tbl) * cell_area)
net_volume = fill_volume + cut_volume

boundary_area = 0.0
with arcpy.da.SearchCursor(boundary_fc, ["SHAPE@AREA"]) as cur:
    for (a,) in cur:
        boundary_area += float(a or 0.0)

with open(out_csv, "w", newline="", encoding="utf-8") as f:
    w = csv.writer(f)
    w.writerow(["metric", "value", "unit"])
    w.writerow(["method", "tin_surfaces", ""])
    w.writerow(["pre_points_inserted", pre_count, "count"])
    w.writerow(["post_points_inserted", post_count, "count"])
    w.writerow(["boundary_area", boundary_area, "square_meters"])
    w.writerow(["fill_volume", fill_volume, "cubic_meters"])
    w.writerow(["cut_volume", cut_volume, "cubic_meters"])
    w.writerow(["net_volume", net_volume, "cubic_meters"])
    w.writerow(["pre_copy", pre_csv, "path"])
    w.writerow(["post_copy", post_csv, "path"])
    w.writerow(["project_path", project_path, "path"])

mp = None
try:
    mp = aprx.activeMap
except Exception:
    mp = None
if mp is None and maps:
    mp = maps[0]

def _add_layer_to_map(map_obj, ds_path, tag):
    if not map_obj or not ds_path or not arcpy.Exists(ds_path):
        print("RESULT_LAYER_SKIP:", tag)
        return
    try:
        lyr = map_obj.addDataFromPath(ds_path)
        try:
            lyr.visible = True
        except Exception:
            pass
        print("RESULT_LAYER_ADDED:", tag, ds_path)
    except Exception as ex:
        print("RESULT_LAYER_ERROR:", tag, str(ex))

if mp:
    for tag, ds in [
        ("boundary", boundary_single),
        ("pre_points", pre_fc),
        ("post_points", post_fc),
        ("pre_tin_raster", pre_ras),
        ("post_tin_raster", post_ras),
        ("dz_tin", dz_raster),
    ]:
        _add_layer_to_map(mp, ds, tag)

try:
    aprx.save()
except Exception:
    pass

print("RESULT_PRE_POINTS_INSERTED:", pre_count)
print("RESULT_POST_POINTS_INSERTED:", post_count)
print("RESULT_BOUNDARY_AREA:", boundary_area)
print("RESULT_FILL_VOLUME:", fill_volume)
print("RESULT_CUT_VOLUME:", cut_volume)
print("RESULT_NET_VOLUME:", net_volume)
print("RESULT_OUTPUT_CSV:", out_csv)
print("RESULT_PRE_COPY:", pre_csv)
print("RESULT_POST_COPY:", post_csv)
print("RESULT_PROJECT_PATH:", project_path)
print("RESULT_PRE_TIN:", pre_tin)
print("RESULT_POST_TIN:", post_tin)
print("RESULT_VOLUME_METHOD:", "tin_plus_zonal")

