# Generated by SurvyAI
# This script was dynamically generated based on user request
# Generated: 2026-06-28T15:46:12.800005
#
# REQUIRED checklist for analyst workflows (IDW, Cut Fill, borrow pits):
# - Use a projected CRS with known linear units for volume; log EPSG/WKID.
# - Add every output feature class/raster to the active map (addDataFromPath / layer objects).
# - project.save() after writes so the open Pro window shows new layers.
#
# Execute this script in ArcGIS Pro's Python Window if needed:
# exec(open(r'C:\Users\UZOR\PycharmProjects\untitled\venv\SurvyAI\Adibawa_BorrowPit_Volume_Project\scripts\Adibawa_BorrowPit_Volume_Project_pre_post_cutfill.py').read())


import os, csv, time, arcpy
from arcpy.sa import Idw, CutFill, ExtractByMask

arcpy.env.overwriteOutput = True

project_path = r"C:\Users\UZOR\PycharmProjects\untitled\venv\SurvyAI\Adibawa_BorrowPit_Volume_Project\Adibawa_BorrowPit_Volume_Project.aprx"
workspace = r"C:\Users\UZOR\PycharmProjects\untitled\venv\SurvyAI"
pre_csv = r"C:\Users\UZOR\PycharmProjects\untitled\venv\SurvyAI\csv_adibawa__020416_0411510.csv"
post_csv = r"C:\Users\UZOR\PycharmProjects\untitled\venv\SurvyAI\csv_Adi_post_031618_062229.csv"
dwg_path = r"C:\Users\USER\Documents\SPDC\ADIBAWA WELL 13\Adibawa Well 13A BORROWPIT-Contractor\REVIEW\POST SURVEY FOR ADIBAWA WELL 13 BORROW PIT 13A RESTORATION.dwg"
out_csv = r"C:\Users\UZOR\PycharmProjects\untitled\venv\SurvyAI\Adibawa_VolumeResult.csv"
explicit_wkid = None

project_dir = os.path.dirname(project_path)
project_name = os.path.splitext(os.path.basename(project_path))[0]
gdb_path = os.path.join(project_dir, project_name + ".gdb")
if not arcpy.Exists(gdb_path):
    arcpy.management.CreateFileGDB(project_dir, project_name + ".gdb")

arcpy.env.workspace = gdb_path
arcpy.env.scratchWorkspace = gdb_path

if arcpy.CheckExtension("Spatial") != "Available":
    raise RuntimeError("Spatial Analyst extension is not available")
arcpy.CheckOutExtension("Spatial")

aprx = arcpy.mp.ArcGISProject(project_path)
maps = aprx.listMaps()
try:
    aprx.defaultGeodatabase = gdb_path
except Exception:
    pass
try:
    aprx.addFolderConnection(project_dir)
except Exception:
    pass

run_tag = "r" + str(int(time.time()))
cad_name = "cad_import_" + run_tag
cad_result = arcpy.conversion.CADToGeodatabase(dwg_path, gdb_path, cad_name, "1000")
try:
    cad_path = cad_result[0]
except Exception:
    cad_path = os.path.join(gdb_path, cad_name)

polygon_fc = None
polyline_fc = None
candidate_roots = [cad_path, gdb_path]
for root in candidate_roots:
    try:
        for dirpath, dirnames, filenames in arcpy.da.Walk(root, datatype="FeatureClass"):
            for filename in filenames:
                full = os.path.join(dirpath, filename)
                nm = str(filename).strip().lower()
                if polygon_fc is None and nm == "polygon":
                    polygon_fc = full
                elif polyline_fc is None and nm == "polyline":
                    polyline_fc = full
    except Exception:
        pass
    if polygon_fc or polyline_fc:
        break

temp_poly = os.path.join(gdb_path, "cad_polygonized_" + run_tag)
boundary_fc = os.path.join(gdb_path, "analysis_boundary_" + run_tag)

def _largest_geom(fc):
    best_geom = None
    best_area = -1.0
    with arcpy.da.SearchCursor(fc, ["SHAPE@"]) as cur:
        for (geom,) in cur:
            if geom and float(getattr(geom, "area", 0.0) or 0.0) > best_area:
                best_area = float(getattr(geom, "area", 0.0) or 0.0)
                best_geom = geom
    return best_geom

boundary_geom = None
boundary_sr = None
if polygon_fc and arcpy.Exists(polygon_fc) and int(arcpy.management.GetCount(polygon_fc)[0]) > 0:
    boundary_geom = _largest_geom(polygon_fc)
    boundary_sr = arcpy.Describe(polygon_fc).spatialReference

if boundary_geom is None:
    if (not polyline_fc) or (not arcpy.Exists(polyline_fc)) or int(arcpy.management.GetCount(polyline_fc)[0]) == 0:
        raise RuntimeError("No polygon or polyline boundary found in DWG import")
    arcpy.management.FeatureToPolygon(polyline_fc, temp_poly)
    if not arcpy.Exists(temp_poly) or int(arcpy.management.GetCount(temp_poly)[0]) == 0:
        raise RuntimeError("Could not derive polygon boundary from DWG polylines")
    boundary_geom = _largest_geom(temp_poly)
    boundary_sr = arcpy.Describe(temp_poly).spatialReference

if boundary_geom is None:
    raise RuntimeError("Could not resolve a usable DWG boundary geometry")

sr = arcpy.SpatialReference(int(explicit_wkid)) if explicit_wkid else boundary_sr
if sr:
    arcpy.management.CreateFeatureclass(gdb_path, os.path.basename(boundary_fc), "POLYGON", spatial_reference=sr)
else:
    arcpy.management.CreateFeatureclass(gdb_path, os.path.basename(boundary_fc), "POLYGON")

geom_to_write = boundary_geom
try:
    if sr and boundary_sr and getattr(boundary_sr, "name", "") not in ("", "Unknown") and getattr(sr, "factoryCode", 0) != getattr(boundary_sr, "factoryCode", 0):
        geom_to_write = boundary_geom.projectAs(sr)
except Exception:
    geom_to_write = boundary_geom

with arcpy.da.InsertCursor(boundary_fc, ["SHAPE@"]) as ic:
    ic.insertRow([geom_to_write])

desc = arcpy.Describe(boundary_fc)
ext = desc.extent
if not ext:
    raise RuntimeError("Boundary feature class has no usable extent")

width = max(float(ext.XMax - ext.XMin), 0.0)
height = max(float(ext.YMax - ext.YMin), 0.0)
cell_size = max(min(width if width > 0 else 1.0, height if height > 0 else 1.0) / 100.0, 0.5)
xpad = max(width * 0.02, cell_size * 2.0, 1.0)
ypad = max(height * 0.02, cell_size * 2.0, 1.0)

def _set_env(mult):
    arcpy.env.extent = arcpy.Extent(ext.XMin - xpad * mult, ext.YMin - ypad * mult, ext.XMax + xpad * mult, ext.YMax + ypad * mult)
    arcpy.env.mask = boundary_fc
    if sr and getattr(sr, "name", "") not in ("", "Unknown"):
        arcpy.env.outputCoordinateSystem = sr
    arcpy.env.cellSize = cell_size

def _pick_field(fieldnames, exact_names, contains_names):
    lower_map = {str(f).strip().lower(): f for f in (fieldnames or [])}
    for name in exact_names:
        if name in lower_map:
            return lower_map[name]
    for name in contains_names:
        for key, original in lower_map.items():
            if name in key:
                return original
    return None

def _detect_xyz_fields(csv_path):
    with open(csv_path, "r", newline="", encoding="utf-8-sig") as f:
        reader = csv.DictReader(f)
        fields = reader.fieldnames or []
    xf = _pick_field(fields, ["e", "x"], ["east", "easting", "lon", "long"])
    yf = _pick_field(fields, ["n", "y"], ["north", "northing", "lat"])
    zf = _pick_field(fields, ["z"], ["elev", "elevation", "rl", "level"])
    return fields, xf, yf, zf

def _csv_to_points(csv_path, fc_name):
    fields, xf, yf, zf = _detect_xyz_fields(csv_path)
    if not xf or not yf or not zf:
        raise RuntimeError("Missing usable E/N/Z fields in {}. Fields found: {}".format(csv_path, fields))
    out_fc = os.path.join(gdb_path, fc_name + "_" + run_tag)
    if sr:
        arcpy.management.CreateFeatureclass(gdb_path, os.path.basename(out_fc), "POINT", spatial_reference=sr)
    else:
        arcpy.management.CreateFeatureclass(gdb_path, os.path.basename(out_fc), "POINT")
    arcpy.management.AddField(out_fc, "ZVAL", "DOUBLE")
    inserted = 0
    with open(csv_path, "r", newline="", encoding="utf-8-sig") as f:
        reader = csv.DictReader(f)
        with arcpy.da.InsertCursor(out_fc, ["SHAPE@XY", "ZVAL"]) as ic:
            for row in reader:
                try:
                    x = float(str(row[xf]).replace(",", "").strip())
                    y = float(str(row[yf]).replace(",", "").strip())
                    z = float(str(row[zf]).replace(",", "").strip())
                except Exception:
                    continue
                ic.insertRow([(x, y), z])
                inserted += 1
    if inserted == 0:
        raise RuntimeError("No usable rows inserted from {}".format(csv_path))
    return out_fc, inserted

pre_fc, pre_count = _csv_to_points(pre_csv, "pre_points")
post_fc, post_count = _csv_to_points(post_csv, "post_points")

pre_idw_raw = os.path.join(gdb_path, "pre_idw_raw_" + run_tag)
post_idw_raw = os.path.join(gdb_path, "post_idw_raw_" + run_tag)
pre_idw = os.path.join(gdb_path, "pre_idw_" + run_tag)
post_idw = os.path.join(gdb_path, "post_idw_" + run_tag)
cutfill_raster = os.path.join(gdb_path, "cutfill_" + run_tag)
cutfill_poly = os.path.join(gdb_path, "cutfill_poly_" + run_tag)

idw_ok = False
for mult in [1.0, 2.0, 4.0]:
    try:
        _set_env(mult)
        Idw(pre_fc, "ZVAL", cell_size=cell_size).save(pre_idw_raw)
        Idw(post_fc, "ZVAL", cell_size=cell_size).save(post_idw_raw)
        ExtractByMask(pre_idw_raw, boundary_fc).save(pre_idw)
        arcpy.env.snapRaster = pre_idw
        ExtractByMask(post_idw_raw, boundary_fc).save(post_idw)
        idw_ok = True
        break
    except Exception as e:
        msg = arcpy.GetMessages(2) + " " + str(e)
        if "010092" in msg or "Invalid output extent" in msg:
            continue
        raise
if not idw_ok:
    raise RuntimeError("IDW failed after automatic extent repair attempts")

_set_env(4.0)
arcpy.env.snapRaster = pre_idw
CutFill(pre_idw, post_idw).save(cutfill_raster)

try:
    arcpy.management.BuildRasterAttributeTable(cutfill_raster, "Overwrite")
except Exception:
    pass

fill_volume = 0.0
cut_volume = 0.0
net_volume = 0.0

# Robust volume computation:
# derive dz = post - pre inside the boundary and integrate depth over cell area.
dz_raster = os.path.join(gdb_path, "dz_post_minus_pre_" + run_tag)
fill_tbl = os.path.join(gdb_path, "fill_depth_sum_" + run_tag)
cut_tbl = os.path.join(gdb_path, "cut_depth_sum_" + run_tag)

ExtractByMask(arcpy.sa.Minus(arcpy.sa.Raster(post_idw), arcpy.sa.Raster(pre_idw)), boundary_fc).save(dz_raster)
dz_desc = arcpy.Describe(dz_raster)
try:
    cell_area = float(dz_desc.meanCellWidth) * float(dz_desc.meanCellHeight)
except Exception:
    cell_area = float(cell_size) * float(cell_size)

oid_field = arcpy.Describe(boundary_fc).OIDFieldName
fill_depth = arcpy.sa.Con(arcpy.sa.Raster(dz_raster) > 0, arcpy.sa.Raster(dz_raster), 0)
cut_depth = arcpy.sa.Con(arcpy.sa.Raster(dz_raster) < 0, -arcpy.sa.Raster(dz_raster), 0)
arcpy.sa.ZonalStatisticsAsTable(boundary_fc, oid_field, fill_depth, fill_tbl, "DATA", "SUM")
arcpy.sa.ZonalStatisticsAsTable(boundary_fc, oid_field, cut_depth, cut_tbl, "DATA", "SUM")
del fill_depth
del cut_depth

def _sum_from(tbl):
    flds = [f.name for f in arcpy.ListFields(tbl)]
    sf = next((f for f in flds if (f or "").strip().lower() == "sum"), None) or next((f for f in flds if "sum" in (f or "").strip().lower()), None)
    if not sf:
        return 0.0
    with arcpy.da.SearchCursor(tbl, [sf]) as c:
        for (v,) in c:
            return float(v) if v is not None else 0.0
    return 0.0

fill_volume = _sum_from(fill_tbl) * cell_area
cut_volume = -(_sum_from(cut_tbl) * cell_area)
net_volume = fill_volume + cut_volume

boundary_area = 0.0
with arcpy.da.SearchCursor(boundary_fc, ["SHAPE@AREA"]) as cur:
    for (a,) in cur:
        boundary_area += float(a or 0.0)

with open(out_csv, "w", newline="", encoding="utf-8") as f:
    w = csv.writer(f)
    w.writerow(["metric", "value", "unit"])
    w.writerow(["pre_points_inserted", pre_count, "count"])
    w.writerow(["post_points_inserted", post_count, "count"])
    w.writerow(["boundary_area", boundary_area, "square_meters"])
    w.writerow(["fill_volume", fill_volume, "cubic_meters"])
    w.writerow(["cut_volume", cut_volume, "cubic_meters"])
    w.writerow(["net_volume", net_volume, "cubic_meters"])
    w.writerow(["pre_copy", pre_csv, "path"])
    w.writerow(["post_copy", post_csv, "path"])
    w.writerow(["project_path", project_path, "path"])

mp = None
try:
    mp = aprx.activeMap
except Exception:
    mp = None
if mp is None and maps:
    mp = maps[0]

def _add_layer_to_map(map_obj, ds_path, tag):
    if not map_obj or not ds_path or not arcpy.Exists(ds_path):
        print("RESULT_LAYER_SKIP:", tag)
        return
    try:
        lyr = map_obj.addDataFromPath(ds_path)
        try:
            lyr.visible = True
        except Exception:
            pass
        print("RESULT_LAYER_ADDED:", tag, ds_path)
    except Exception as ex:
        print("RESULT_LAYER_ERROR:", tag, str(ex))

if mp:
    for tag, ds in [
        ("boundary", boundary_fc),
        ("pre_points", pre_fc),
        ("post_points", post_fc),
        ("pre_idw", pre_idw),
        ("post_idw", post_idw),
        ("dz_post_minus_pre", dz_raster),
        ("cutfill", cutfill_raster),
    ]:
        _add_layer_to_map(mp, ds, tag)
    try:
        mp.defaultCamera.setExtent(arcpy.Describe(boundary_fc).extent)
    except Exception:
        pass

try:
    aprx.save()
except Exception:
    pass

print("RESULT_PRE_POINTS_INSERTED:", pre_count)
print("RESULT_POST_POINTS_INSERTED:", post_count)
print("RESULT_BOUNDARY_AREA:", boundary_area)
print("RESULT_FILL_VOLUME:", fill_volume)
print("RESULT_CUT_VOLUME:", cut_volume)
print("RESULT_NET_VOLUME:", net_volume)
print("RESULT_OUTPUT_CSV:", out_csv)
print("RESULT_PRE_COPY:", pre_csv)
print("RESULT_POST_COPY:", post_csv)
print("RESULT_PROJECT_PATH:", project_path)

