# Generated by SurvyAI
# This script was dynamically generated based on user request
# Generated: 2026-06-28T15:49:10.683940
#
# REQUIRED checklist for analyst workflows (IDW, Cut Fill, borrow pits):
# - Use a projected CRS with known linear units for volume; log EPSG/WKID.
# - Add every output feature class/raster to the active map (addDataFromPath / layer objects).
# - project.save() after writes so the open Pro window shows new layers.
#
# Execute this script in ArcGIS Pro's Python Window if needed:
# exec(open(r'C:\Users\UZOR\PycharmProjects\untitled\venv\SurvyAI\Adibawa_BorrowPit_Volume_Project\scripts\Adibawa_BorrowPit_Volume_Project_finalize_visualization.py').read())


import os
import arcpy

project_path = r"C:\Users\UZOR\PycharmProjects\untitled\venv\SurvyAI\Adibawa_BorrowPit_Volume_Project\Adibawa_BorrowPit_Volume_Project.aprx"
project_dir = r"C:\Users\UZOR\PycharmProjects\untitled\venv\SurvyAI\Adibawa_BorrowPit_Volume_Project"
gdb_path = r"C:\Users\UZOR\PycharmProjects\untitled\venv\SurvyAI\Adibawa_BorrowPit_Volume_Project\Adibawa_BorrowPit_Volume_Project.gdb"

aprx = arcpy.mp.ArcGISProject(project_path)
maps = aprx.listMaps()

basemap_loaded = False
gdb_loaded = False
feature_classes_loaded = []

# Prefer the project's own geodatabase as the default, so it appears under Databases
try:
    if os.path.exists(gdb_path):
        aprx.defaultGeodatabase = gdb_path
except Exception:
    pass

# Add a folder connection to the project directory (so the .gdb is easy to find in Catalog)
try:
    aprx.addFolderConnection(project_dir)
except Exception:
    pass

# Load basemap
if True:
    for m in maps:
        try:
            # Try common basemap name variations
            basemap_names = [
                "Imagery Hybrid",
                "Imagery Hybrid",
                "ImageryHybrid",
                "Imagery_Hybrid",
                "ImageHybrid",
                "Image_Hybrid",
            ]
            for bm_name in basemap_names:
                try:
                    m.addBasemap(bm_name)
                    basemap_loaded = True
                    print("RESULT_BASEMAP_LOADED:", bm_name, "on map:", m.name)
                    break
                except Exception:
                    continue
            if not basemap_loaded:
                # Fallback: try to list available basemaps and use first imagery hybrid one
                try:
                    available = m.listBasemaps()
                    for bm in available:
                        if "imagery" in bm.name.lower() and "hybrid" in bm.name.lower():
                            m.addBasemap(bm.name)
                            basemap_loaded = True
                            print("RESULT_BASEMAP_LOADED:", bm.name, "on map:", m.name)
                            break
                except Exception as e:
                    print("RESULT_BASEMAP_WARNING:", str(e))
        except Exception as e:
            print("RESULT_BASEMAP_ERROR:", str(e))

# Load native geodatabase: feature classes AND rasters (IDW, CutFill, etc.)
if True and os.path.exists(gdb_path):
    for m in maps:
        try:
            existing_paths = set()
            try:
                for lyr in m.listLayers():
                    try:
                        cp = getattr(lyr, "catalogPath", None) or getattr(lyr, "dataSource", None)
                        if cp:
                            existing_paths.add(os.path.normpath(str(cp)).lower())
                    except Exception:
                        pass
            except Exception:
                pass

            datasets = []
            for dtt in ("FeatureClass", "RasterDataset"):
                try:
                    for dirpath, dirnames, filenames in arcpy.da.Walk(gdb_path, datatype=dtt):
                        for filename in filenames:
                            ds_path = os.path.join(dirpath, filename)
                            if arcpy.Exists(ds_path):
                                datasets.append(ds_path)
                except Exception:
                    pass

            def _viz_rank(p):
                b = os.path.basename(p).lower()
                if "analysis_boundary" in b or b.startswith("boundary"):
                    return (0, b)
                if "pre_point" in b or b.startswith("pre_points"):
                    return (1, b)
                if "post_point" in b or b.startswith("post_points"):
                    return (2, b)
                if "pre_idw" in b:
                    return (3, b)
                if "post_idw" in b:
                    return (4, b)
                if "dz_" in b or "dz_post" in b:
                    return (5, b)
                if "cutfill" in b:
                    return (6, b)
                return (9, b)

            datasets.sort(key=_viz_rank)

            for ds_path in datasets:
                try:
                    key = os.path.normpath(ds_path).lower()
                    if key in existing_paths:
                        continue
                    lyr = m.addDataFromPath(ds_path)
                    try:
                        lyr.visible = True
                    except Exception:
                        pass
                    existing_paths.add(key)
                    ds_name = os.path.basename(ds_path)
                    feature_classes_loaded.append(ds_name)
                    print("RESULT_DS_LOADED:", ds_name, "on map:", m.name)
                except Exception as e:
                    print("RESULT_DS_WARNING:", os.path.basename(ds_path), ":", str(e))

            if datasets:
                gdb_loaded = True
                print("RESULT_GDB_LOADED:", gdb_path, "with", len(datasets), "datasets")

            try:
                zoom_ext = None
                for prefer in ("analysis_boundary", "boundary", "pre_idw", "post_idw", "cutfill"):
                    for ds_path in datasets:
                        if prefer in os.path.basename(ds_path).lower():
                            zoom_ext = arcpy.Describe(ds_path).extent
                            break
                    if zoom_ext:
                        break
                if zoom_ext:
                    m.defaultCamera.setExtent(zoom_ext)
            except Exception:
                pass
        except Exception as e:
            print("RESULT_GDB_ERROR:", str(e))

aprx.save()
print("RESULT_FINALIZATION_COMPLETE")

