# Generated by SurvyAI
# This script was dynamically generated based on user request
# Generated: 2026-03-28T12:58:37.117058
# 
# Execute this script in ArcGIS Pro's Python Window if needed:
# exec(open(r'C:\Users\UZOR\PycharmProjects\untitled\venv\SurvyAI\scripts\_test_rewrite.py').read())

# NOTE: xlsxwriter API replaced by openpyxl. Use ws.cell(row=r, column=c, value=v) or ws.append([...]).

import arcpy, os, xlsxwriter

# ---- SurvyAI auto-patch: safe .aprx creation ----
def _ensure_aprx(_path):
    import os as _os
    _path = _os.path.abspath(_path)
    if not _os.path.exists(_path):
        _folder = _os.path.dirname(_path)
        _name = _os.path.splitext(_os.path.basename(_path))[0]
        _os.makedirs(_folder, exist_ok=True)
        arcpy.mp.ArcGISProject.create(_folder, _name)
    return arcpy.mp.ArcGISProject(_path)
# ---- end auto-patch ----

project_folder = r"C:\tmp\work"
project_name = "Test"
project_path = os.path.join(project_folder, project_name + ".aprx")

if not os.path.exists(project_path):
    aprx = _ensure_aprx(project_path)
    try:
        aprx.saveACopy(project_path)
    except Exception as e:
        aprx = _ensure_aprx(project_path)
else:
    aprx = arcpy.mp.ArcGISProject(project_path)

m = aprx.listMaps()[0]

# NOTE: ZonalStatisticsAsTable removed by SurvyAI (ERROR 010167 with DWG masks). Use CutFill AREA/VOLUME fields.
# NOTE: ZonalStatisticsAsTable removed by SurvyAI (ERROR 010167 with DWG masks). Use CutFill AREA/VOLUME fields.
result_table = None  # ZonalStatisticsAsTable stub

workbook = openpyxl.Workbook()  # openpyxl: call wb.save(output_excel) at the end
worksheet = workbook.create_sheet("Volume")
worksheet.write(0, 0, "Metric")
workbook.close()

