# Generated by SurvyAI
# Automatic fallback after ArcGIS Pro UI bootstrap failed
# Generated: 2026-04-01T08:03:51.701806
# 
# Original interactive script: C:\Users\UZOR\PycharmProjects\untitled\venv\SurvyAI\scripts\adibawa_pre_post_cutfill_retry.py

import arcpy, os, csv, math, shutil, traceback
from arcpy.sa import Idw, CutFill

arcpy.env.overwriteOutput = True
workspace = os.getcwd()
pre_src = r"C:\Users\USER\Documents\SPDC\ADIBAWA WELL 13\Adibawa Well 13A BORROWPIT-Contractor\ADIBAWA WELL 13 BORROW PIT VOLUME COMPUTATION_074938\csv_adibawa__020416_0411510.csv"
post_src = r"C:\Users\USER\Documents\SPDC\ADIBAWA WELL 13\Adibawa Well 13A BORROWPIT-Contractor\ADIBAWA WELL 13 BORROW PIT VOLUME COMPUTATION_074938\csv_Adi post_031618_062229.csv"
dwg_path = r"C:\Users\USER\Documents\SPDC\ADIBAWA WELL 13\Adibawa Well 13A BORROWPIT-Contractor\REVIEW\POST SURVEY FOR ADIBAWA WELL 13 BORROW PIT 13A RESTORATION.dwg"
pre_copy = os.path.join(workspace, 'csv_adibawa__020416_0411510.csv')
post_copy = os.path.join(workspace, 'csv_Adi post_031618_062229.csv')
out_csv = os.path.join(workspace, 'Adibawa_VolumeResult.csv')
project_dir = r"C:\Users\USER\Documents\SPDC\ADIBAWA WELL 13\Adibawa Well 13A BORROWPIT-Contractor\ADIBAWA WELL 13 BORROW PIT VOLUME COMPUTATION_074938\Adibawa_BorrowPit_Volume"
os.makedirs(project_dir, exist_ok=True)
gdb = os.path.join(project_dir, 'Adibawa_BorrowPit_Volume.gdb')
if not arcpy.Exists(gdb):
    arcpy.management.CreateFileGDB(project_dir, 'Adibawa_BorrowPit_Volume.gdb')

shutil.copy2(pre_src, pre_copy)
shutil.copy2(post_src, post_copy)
print('RESULT_PRE_COPY:', pre_copy)
print('RESULT_POST_COPY:', post_copy)

arcpy.CheckOutExtension('Spatial')

# Use CURRENT if available, otherwise work headless without project creation dependency
aprx = None
mp = None
try:
    aprx = arcpy.mp.ArcGISProject('CURRENT')
    maps = aprx.listMaps()
    mp = maps[0] if maps else None
except Exception:
    aprx = None
    mp = None

cad_gdb = os.path.join(project_dir, 'cad_import.gdb')
if arcpy.Exists(cad_gdb):
    arcpy.management.Delete(cad_gdb)
arcpy.conversion.CADToGeodatabase(dwg_path, project_dir, 'cad_import')

polygon_candidates = []
for fc in [os.path.join(cad_gdb, 'Polygon'), os.path.join(cad_gdb, 'cad_import', 'Polygon')]:
    if arcpy.Exists(fc):
        polygon_candidates.append(fc)

boundary_fc = None
boundary_geom = None
max_area = -1.0
for fc in polygon_candidates:
    with arcpy.da.SearchCursor(fc, ['OID@', 'SHAPE@']) as cur:
        for oid, geom in cur:
            if geom and geom.area > max_area:
                max_area = geom.area
                boundary_fc = fc
                boundary_geom = geom

if boundary_geom is None:
    raise RuntimeError('No usable polygon found in DWG for boundary/extent mask')

mask_fc = os.path.join(gdb, 'borrowpit_mask')
if arcpy.Exists(mask_fc):
    arcpy.management.Delete(mask_fc)
arcpy.management.CreateFeatureclass(gdb, 'borrowpit_mask', 'POLYGON', spatial_reference=arcpy.Describe(boundary_fc).spatialReference)
with arcpy.da.InsertCursor(mask_fc, ['SHAPE@']) as ic:
    ic.insertRow([boundary_geom])

sr = arcpy.Describe(mask_fc).spatialReference
ext = arcpy.Describe(mask_fc).extent
xpad = max((ext.XMax - ext.XMin) * 0.02, 1.0)
ypad = max((ext.YMax - ext.YMin) * 0.02, 1.0)
expanded = arcpy.Extent(ext.XMin - xpad, ext.YMin - ypad, ext.XMax + xpad, ext.YMax + ypad)
arcpy.env.extent = expanded
arcpy.env.mask = mask_fc
arcpy.env.outputCoordinateSystem = sr


def detect_fields(csv_path):
    with open(csv_path, 'r', newline='', encoding='utf-8-sig') as f:
        reader = csv.reader(f)
        header = next(reader)
    lower = {h.lower().strip(): h for h in header}
    def pick(names):
        for n in names:
            for k,v in lower.items():
                if k == n:
                    return v
        for n in names:
            for k,v in lower.items():
                if n in k:
                    return v
        return None
    return header, pick(['e','east','easting','x']), pick(['n','north','northing','y']), pick(['z','elev','elevation','rl','level'])


def csv_to_points(csv_path, fc_name):
    header, xf, yf, zf = detect_fields(csv_path)
    if not xf or not yf or not zf:
        raise RuntimeError('Missing usable E/N/Z fields in %s. Header=%s' % (csv_path, header))
    out_fc = os.path.join(gdb, fc_name)
    if arcpy.Exists(out_fc):
        arcpy.management.Delete(out_fc)
    arcpy.management.CreateFeatureclass(gdb, fc_name, 'POINT', spatial_reference=sr)
    arcpy.management.AddField(out_fc, 'ZVAL', 'DOUBLE')
    inserted = 0
    with open(csv_path, 'r', newline='', encoding='utf-8-sig') as f:
        reader = csv.DictReader(f)
        with arcpy.da.InsertCursor(out_fc, ['SHAPE@XY', 'ZVAL']) as ic:
            for row in reader:
                try:
                    x = float(str(row[xf]).replace(',', '').strip())
                    y = float(str(row[yf]).replace(',', '').strip())
                    z = float(str(row[zf]).replace(',', '').strip())
                except Exception:
                    continue
                ic.insertRow([(x, y), z])
                inserted += 1
    if inserted == 0:
        raise RuntimeError('No usable rows inserted from %s' % csv_path)
    return out_fc, inserted, xf, yf, zf

pre_fc, pre_count, pxf, pyf, pzf = csv_to_points(pre_copy, 'pre_points')
post_fc, post_count, qxf, qyf, qzf = csv_to_points(post_copy, 'post_points')
print('RESULT_PRE_POINTS_INSERTED:', pre_count)
print('RESULT_POST_POINTS_INSERTED:', post_count)

width = expanded.XMax - expanded.XMin
height = expanded.YMax - expanded.YMin
cell = max(min(width, height) / 100.0, 0.5)
arcpy.env.cellSize = cell

pre_raster = os.path.join(gdb, 'pre_idw')
post_raster = os.path.join(gdb, 'post_idw')
cutfill_raster = os.path.join(gdb, 'cutfill')
for p in [pre_raster, post_raster, cutfill_raster]:
    if arcpy.Exists(p):
        arcpy.management.Delete(p)

for attempt in range(3):
    try:
        Idw(pre_fc, 'ZVAL', cell_size=cell).save(pre_raster)
        Idw(post_fc, 'ZVAL', cell_size=cell).save(post_raster)
        break
    except Exception as e:
        msg = arcpy.GetMessages(2) + ' ' + str(e)
        if '010092' in msg or 'Invalid output extent' in msg:
            xpad *= 2
            ypad *= 2
            expanded = arcpy.Extent(ext.XMin - xpad, ext.YMin - ypad, ext.XMax + xpad, ext.YMax + ypad)
            arcpy.env.extent = expanded
            continue
        raise

CutFill(pre_raster, post_raster).save(cutfill_raster)
try:
    arcpy.management.BuildRasterAttributeTable(cutfill_raster, 'Overwrite')
except Exception:
    pass
fields = [f.name for f in arcpy.ListFields(cutfill_raster)]
vol_field = next((f for f in fields if f.upper() == 'VOLUME' or 'VOLUME' in f.upper() or f.upper() == 'VOL'), None)
if not vol_field:
    raise RuntimeError('Could not find volume field in cutfill raster fields: %s' % fields)

zone_area = boundary_geom.area
fill_volume = 0.0
cut_volume = 0.0
net_volume = 0.0
with arcpy.da.SearchCursor(cutfill_raster, [vol_field]) as cur:
    for (v,) in cur:
        if v is None:
            continue
        v = float(v)
        net_volume += v
        if v > 0:
            fill_volume += v
        elif v < 0:
            cut_volume += v

with open(out_csv, 'w', newline='', encoding='utf-8') as f:
    w = csv.writer(f)
    w.writerow(['Metric','Value','Unit'])
    w.writerow(['Boundary_Area', zone_area, 'square_meters'])
    w.writerow(['Fill_Volume', fill_volume, 'cubic_meters'])
    w.writerow(['Cut_Volume', cut_volume, 'cubic_meters'])
    w.writerow(['Net_Volume', net_volume, 'cubic_meters'])
    w.writerow(['Pre_Points_Inserted', pre_count, 'count'])
    w.writerow(['Post_Points_Inserted', post_count, 'count'])

if mp is not None:
    for ds in [mask_fc, pre_fc, post_fc, pre_raster, post_raster, cutfill_raster]:
        try:
            mp.addDataFromPath(ds)
        except Exception:
            pass
    try:
        aprx.save()
    except Exception:
        pass

print('RESULT_AREA:', zone_area)
print('RESULT_FILL_VOLUME:', fill_volume)
print('RESULT_CUT_VOLUME:', cut_volume)
print('RESULT_NET_VOLUME:', net_volume)
print('RESULT_OUTPUT_CSV:', out_csv)
print('RESULT_PROJECT_FOLDER:', project_dir)

