# Generated by SurvyAI
# Automatic fallback after ArcGIS Pro UI bootstrap failed
# Generated: 2026-03-29T11:02:32.547254
# 
# Original interactive script: C:\Users\UZOR\PycharmProjects\untitled\venv\SurvyAI\scripts\adibawa_volume_idw_cutfill.py

import arcpy, os, math

pre_excel = r"C:\Users\USER\Documents\SPDC\ADIBAWA WELL 13\Adibawa Well 13A BORROWPIT-Contractor\ADIBAWA WELL 13 BORROW PIT VOLUME COMPUTATION_074938\csv_adibawa__020416_0411510.xlsx"
post_excel = r"C:\Users\USER\Documents\SPDC\ADIBAWA WELL 13\Adibawa Well 13A BORROWPIT-Contractor\ADIBAWA WELL 13 BORROW PIT VOLUME COMPUTATION_074938\csv_Adi post_031618_062229.xlsx"
dwg_path = r"C:\Users\USER\Documents\SPDC\ADIBAWA WELL 13\Adibawa Well 13A BORROWPIT-Contractor\REVIEW\POST SURVEY FOR ADIBAWA WELL 13 BORROW PIT 13A RESTORATION.dwg"

# Workspace in SurvyAI folder
workspace = os.path.join(os.path.expanduser("~"), "SurvyAI")
os.makedirs(workspace, exist_ok=True)

arcpy.env.workspace = workspace
arcpy.env.overwriteOutput = True

# Create a file geodatabase
gdb_path = os.path.join(workspace, "AdibawaVolume.gdb")
if not arcpy.Exists(gdb_path):
    arcpy.management.CreateFileGDB(workspace, "AdibawaVolume.gdb")

arcpy.env.workspace = gdb_path

# Import DWG and get polygon for extent/mask
cad_dataset = arcpy.conversion.CADToGeodatabase(dwg_path, gdb_path, "Adibawa_CAD", "1000")

boundary_fc = None
for fc in arcpy.ListFeatureClasses(feature_dataset="Adibawa_CAD"):
    desc = arcpy.Describe(fc)
    if desc.shapeType == "Polygon":
        boundary_fc = fc
        break

if not boundary_fc:
    raise RuntimeError("No polygon boundary found in DWG-derived dataset.")

boundary_desc = arcpy.Describe(boundary_fc)

# Set environment from boundary
arcpy.env.extent = boundary_desc.extent
arcpy.env.mask = boundary_fc
arcpy.env.outputCoordinateSystem = boundary_desc.spatialReference

# Helper: import Excel to points

def excel_to_points(excel_path, out_fc_name):
    table_name = os.path.basename(excel_path).replace('.xlsx', '')
    excel_table = arcpy.conversion.ExcelToTable(excel_path, table_name)

    fields = [f.name for f in arcpy.ListFields(excel_table)]
    # Expect E, N, Z as given
    x_field = 'E'
    y_field = 'N'
    z_field = 'Z'
    missing = [f for f in [x_field, y_field, z_field] if f not in fields]
    if missing:
        raise RuntimeError(f"Missing expected fields {missing} in {excel_path}. Found: {fields}")

    sr = boundary_desc.spatialReference
    out_fc = os.path.join(gdb_path, out_fc_name)
    if arcpy.Exists(out_fc):
        arcpy.management.Delete(out_fc)
    arcpy.management.CreateFeatureclass(gdb_path, out_fc_name, "POINT", spatial_reference=sr)
    arcpy.management.AddField(out_fc, "Z", "DOUBLE")

    with arcpy.da.SearchCursor(excel_table, [x_field, y_field, z_field]) as sc,
         arcpy.da.InsertCursor(out_fc, ["SHAPE@XY", "Z"]) as ic:
        for x_raw, y_raw, z_raw in sc:
            try:
                x = float(str(x_raw).replace(',', ''))
                y = float(str(y_raw).replace(',', ''))
                z = float(str(z_raw).replace(',', ''))
            except Exception:
                continue
            ic.insertRow(((x, y), z))

    return out_fc, "Z"

pre_points, pre_z = excel_to_points(pre_excel, "PRE_points")
post_points, post_z = excel_to_points(post_excel, "POST_points")

# Create IDW surfaces
cell_size = (arcpy.env.extent.XMax - arcpy.env.extent.XMin) / 200.0

pre_idw = arcpy.ga.IDW(pre_points, pre_z, cell_size=cell_size)
post_idw = arcpy.ga.IDW(post_points, post_z, cell_size=cell_size)

pre_idw_path = os.path.join(gdb_path, "PRE_IDW")
post_idw_path = os.path.join(gdb_path, "POST_IDW")

pre_idw.save(pre_idw_path)
post_idw.save(post_idw_path)

# CutFill
cutfill_raster = os.path.join(gdb_path, "CutFill_PRE_POST")
cf = arcpy.sa.CutFill(pre_idw_path, post_idw_path)
cf.save(cutfill_raster)

# Zonal statistics over the boundary polygon to get volume (SUM of difference * cell area)
# CutFill output is in same vertical units as Z and horizontal units from CRS; volume is handled internally by CutFill.

# Use Raster to polygon extent + ZonalStatisticsAsTable
zone_fc = boundary_fc
zone_field = "FID"

# Ensure zone_field exists
fields = [f.name for f in arcpy.ListFields(zone_fc)]
if zone_field not in fields:
    zone_field = fields[0]

zs_table = os.path.join(gdb_path, "CutFill_Stats")
if arcpy.Exists(zs_table):
    arcpy.management.Delete(zs_table)

arcpy.sa.ZonalStatisticsAsTable(zone_fc, zone_field, cutfill_raster, zs_table, "DATA", "SUM")

volume = 0.0
sum_field = None
for f in arcpy.ListFields(zs_table):
    if f.name.upper().startswith("SUM"):
        sum_field = f.name
        break

if sum_field is None:
    raise RuntimeError("No SUM field found in ZonalStatistics table.")

with arcpy.da.SearchCursor(zs_table, [sum_field]) as cursor:
    for (v,) in cursor:
        if v is not None:
            volume += float(v)

# Export result CSV in workspace
csv_out = os.path.join(workspace, "Adibawa_VolumeResult.csv")
with open(csv_out, 'w') as f:
    f.write("Name,Volume_m3\n")
    f.write(f"Adibawa_BorrowPit,{volume}\n")

print("RESULT_VOLUME_M3:", volume)
print("RESULT_CSV_PATH:", csv_out)

