# Generated by SurvyAI
# This script was dynamically generated based on user request
# Generated: 2026-05-04T18:01:07.910006
#
# REQUIRED checklist for analyst workflows (IDW, Cut Fill, borrow pits):
# - Use a projected CRS with known linear units for volume; log EPSG/WKID.
# - Add every output feature class/raster to the active map (addDataFromPath / layer objects).
# - project.save() after writes so the open Pro window shows new layers.
#
# Execute this script in ArcGIS Pro's Python Window if needed:
# exec(open(r'C:\Users\UZOR\PycharmProjects\untitled\venv\SurvyAI\scripts\adibawa_volume_workflow.py').read())

import arcpy, os, csv, math, shutil, sys, traceback
from pathlib import Path

# Inputs
pre_src = r"C:\Users\USER\Documents\SPDC\ADIBAWA WELL 13\Adibawa Well 13A BORROWPIT-Contractor\ADIBAWA WELL 13 BORROW PIT VOLUME COMPUTATION_074938\csv_adibawa__020416_0411510.csv"
post_src = r"C:\Users\USER\Documents\SPDC\ADIBAWA WELL 13\Adibawa Well 13A BORROWPIT-Contractor\ADIBAWA WELL 13 BORROW PIT VOLUME COMPUTATION_074938\csv_Adi post_031618_062229.csv"
dwg_path = r"C:\Users\USER\Documents\SPDC\ADIBAWA WELL 13\Adibawa Well 13A BORROWPIT-Contractor\REVIEW\POST SURVEY FOR ADIBAWA WELL 13 BORROW PIT 13A RESTORATION.dwg"
workspace = r"C:\Users\UZOR\PycharmProjects\untitled\venv\SurvyAI"
pre_copy = os.path.join(workspace, os.path.basename(pre_src))
post_copy = os.path.join(workspace, os.path.basename(post_src))
result_csv = os.path.join(workspace, 'Adibawa_VolumeResult.csv')
project_dir = os.path.join(workspace, 'Adibawa_Volume_Project')
os.makedirs(project_dir, exist_ok=True)
project_path = os.path.join(project_dir, 'Adibawa_Volume_Project.aprx')
gdb = os.path.join(project_dir, 'Adibawa_Volume.gdb')
if not arcpy.Exists(gdb):
    arcpy.management.CreateFileGDB(project_dir, 'Adibawa_Volume.gdb')

# stable env
arcpy.env.workspace = gdb
arcpy.env.overwriteOutput = True
arcpy.env.scratchWorkspace = gdb
arcpy.env.scratchGDB = gdb
print('WORKSPACE:', gdb)

# Copy source CSVs into workspace as requested
shutil.copy2(pre_src, pre_copy)
shutil.copy2(post_src, post_copy)
print('COPIED_PRE:', pre_copy)
print('COPIED_POST:', post_copy)

# create/open project
if os.path.exists(project_path):
    aprx = arcpy.mp.ArcGISProject(project_path)
else:
    try:
        arcpy.management.CreateProject(project_dir, 'Adibawa_Volume_Project', 'MAP')
        aprx = arcpy.mp.ArcGISProject(project_path)
    except Exception:
        # fallback from installed template
        aprx = arcpy.mp.ArcGISProject(r"C:\Users\UZOR\PycharmProjects\untitled\venv\SurvyAI\Adibawa_Volume_Project\Adibawa_Volume_Project.aprx")
        aprx.saveACopy(project_path)
        aprx = arcpy.mp.ArcGISProject(project_path)

maps = aprx.listMaps()
mp = maps[0] if maps else aprx.createMap('Map')

# Helpers

def detect_fields(csv_path):
    with open(csv_path, 'r', newline='', encoding='utf-8-sig') as f:
        reader = csv.reader(f)
        header = next(reader)
    norm = {h.strip(): h for h in header}
    lower = {h.strip().lower(): h for h in header}
    x = next((lower[k] for k in lower if k in ('e','east','easting','x')), None)
    y = next((lower[k] for k in lower if k in ('n','north','northing','y')), None)
    z = next((lower[k] for k in lower if k in ('z','elev','elevation','level','rl')), None)
    if not (x and y and z):
        # fuzzy contains fallback
        for k,v in lower.items():
            if x is None and ('east' in k or k == 'x' or k == 'e'):
                x = v
            if y is None and ('north' in k or k == 'y' or k == 'n'):
                y = v
            if z is None and ('elev' in k or 'level' in k or k == 'z' or 'rl' == k):
                z = v
    return header, x, y, z


def make_points_from_csv(csv_path, fc_name):
    header, x_field, y_field, z_field = detect_fields(csv_path)
    if not (x_field and y_field and z_field):
        raise RuntimeError(f'Missing usable X/Y/Z fields in {csv_path}. Header={header}')
    fc = os.path.join(gdb, fc_name)
    if arcpy.Exists(fc):
        arcpy.management.Delete(fc)
    sr = arcpy.SpatialReference()  # unknown, preserve native XY consistently
    arcpy.management.CreateFeatureclass(gdb, fc_name, 'POINT', has_z='ENABLED', spatial_reference=sr)
    arcpy.management.AddField(fc, 'SRC_ID', 'LONG')
    arcpy.management.AddField(fc, 'Z_VAL', 'DOUBLE')
    count = 0
    with open(csv_path, 'r', newline='', encoding='utf-8-sig') as f:
        reader = csv.DictReader(f)
        with arcpy.da.InsertCursor(fc, ['SRC_ID','Z_VAL','SHAPE@XYZ']) as ic:
            oid = 1
            for row in reader:
                try:
                    x = float(str(row[x_field]).replace(',','').strip())
                    y = float(str(row[y_field]).replace(',','').strip())
                    z = float(str(row[z_field]).replace(',','').strip())
                except Exception:
                    continue
                ic.insertRow((oid, z, (x,y,z)))
                oid += 1
                count += 1
    return fc, count, x_field, y_field, z_field

pre_fc, pre_count, _, _, _ = make_points_from_csv(pre_copy, 'pre_points')
post_fc, post_count, _, _, _ = make_points_from_csv(post_copy, 'post_points')
print('RESULT_PRE_POINTS_INSERTED:', pre_count)
print('RESULT_POST_POINTS_INSERTED:', post_count)
if pre_count == 0 or post_count == 0:
    raise RuntimeError('No usable X/Y/Z rows found in PRE or POST CSV.')

# Import DWG polygon/boundary
cad_ds = os.path.join(project_dir, 'cad_import.gdb')
if not arcpy.Exists(cad_ds):
    arcpy.conversion.CADToGeodatabase(dwg_path, project_dir, 'cad_import')
polygon_fc = os.path.join(cad_ds, 'Polygon')
polyline_fc = os.path.join(cad_ds, 'Polyline')
analysis_poly = os.path.join(gdb, 'analysis_boundary')
if arcpy.Exists(analysis_poly):
    arcpy.management.Delete(analysis_poly)

chosen = None
# Prefer polygon features if any exist
if arcpy.Exists(polygon_fc) and int(arcpy.management.GetCount(polygon_fc)[0]) > 0:
    arcpy.management.MultipartToSinglepart(polygon_fc, analysis_poly)
    chosen = analysis_poly
else:
    # Build polygon from closed polylines if possible
    tmp_poly = os.path.join(gdb, 'tmp_boundary_poly')
    if arcpy.Exists(tmp_poly):
        arcpy.management.Delete(tmp_poly)
    arcpy.management.FeatureToPolygon(polyline_fc, tmp_poly)
    if int(arcpy.management.GetCount(tmp_poly)[0]) > 0:
        arcpy.management.MultipartToSinglepart(tmp_poly, analysis_poly)
        chosen = analysis_poly

if not chosen or int(arcpy.management.GetCount(chosen)[0]) == 0:
    raise RuntimeError('Could not derive analysis polygon from DWG.')

# Keep largest polygon as mask/extent boundary
largest_poly = os.path.join(gdb, 'analysis_boundary_largest')
if arcpy.Exists(largest_poly):
    arcpy.management.Delete(largest_poly)
max_area = -1
geom_keep = None
with arcpy.da.SearchCursor(chosen, ['SHAPE@']) as sc:
    for (geom,) in sc:
        if geom and geom.area > max_area:
            max_area = geom.area
            geom_keep = geom
arcpy.management.CreateFeatureclass(gdb, 'analysis_boundary_largest', 'POLYGON', spatial_reference=arcpy.Describe(chosen).spatialReference)
with arcpy.da.InsertCursor(largest_poly, ['SHAPE@']) as ic:
    ic.insertRow([geom_keep])

# Environment from polygon
ext = arcpy.Describe(largest_poly).extent
xmin, ymin, xmax, ymax = ext.XMin, ext.YMin, ext.XMax, ext.YMax
padx = max((xmax-xmin)*0.02, 1.0)
pady = max((ymax-ymin)*0.02, 1.0)
arcpy.env.extent = arcpy.Extent(xmin-padx, ymin-pady, xmax+padx, ymax+pady)
arcpy.env.mask = largest_poly
arcpy.env.outputCoordinateSystem = arcpy.Describe(largest_poly).spatialReference
print('EXTENT_SET:', arcpy.env.extent.JSON)

# Check out Spatial Analyst
arcpy.CheckOutExtension('Spatial')
from arcpy.sa import Idw, ExtractByMask, CutFill

pre_idw = os.path.join(gdb, 'pre_idw')
post_idw = os.path.join(gdb, 'post_idw')
pre_clip = os.path.join(gdb, 'pre_idw_clip')
post_clip = os.path.join(gdb, 'post_idw_clip')
cutfill_ras = os.path.join(gdb, 'cutfill_raster')

# Cell size from boundary extent and point density
cell_size = max(min((xmax-xmin)/100.0, (ymax-ymin)/100.0), 1.0)
print('CELL_SIZE:', cell_size)

pre_r = Idw(pre_fc, 'Z_VAL', cell_size)
pre_r.save(pre_idw)
post_r = Idw(post_fc, 'Z_VAL', cell_size)
post_r.save(post_idw)
ExtractByMask(pre_idw, largest_poly).save(pre_clip)
ExtractByMask(post_idw, largest_poly).save(post_clip)

# CutFill
cf = CutFill(pre_clip, post_clip)
cf.save(cutfill_ras)

# Compute area and net volume from CutFill raster table if available; fallback raster properties
net_vol = 0.0
cf_area = 0.0
try:
    tbl_fields = [f.name.upper() for f in arcpy.ListFields(cutfill_ras)]
    if 'AREA' in tbl_fields and 'VOLUME' in tbl_fields:
        with arcpy.da.SearchCursor(cutfill_ras, ['AREA','VOLUME']) as sc:
            for a,v in sc:
                if a is not None: cf_area += float(a)
                if v is not None: net_vol += float(v)
    else:
        raise RuntimeError('No AREA/VOLUME fields on cutfill raster')
except Exception:
    # Fallback to zoneless approach: use polygon area only; net volume unavailable from fallback
    with arcpy.da.SearchCursor(largest_poly, ['SHAPE@AREA']) as sc:
        for (a,) in sc:
            cf_area += float(a)

# Write result CSV
with open(result_csv, 'w', newline='', encoding='utf-8') as f:
    w = csv.writer(f)
    w.writerow(['Metric','Value','Units'])
    w.writerow(['PRE_Points_Inserted', pre_count, 'count'])
    w.writerow(['POST_Points_Inserted', post_count, 'count'])
    w.writerow(['Analysis_Area', cf_area, 'square_map_units'])
    w.writerow(['Net_Volume', net_vol, 'cubic_map_units'])
    w.writerow(['Boundary_Source_DWG', dwg_path, 'path'])

# Add outputs to map
for p in [pre_fc, post_fc, largest_poly, pre_clip, post_clip, cutfill_ras]:
    try:
        mp.addDataFromPath(p)
    except Exception as e:
        print('ADD_TO_MAP_WARN:', p, str(e))

try:
    d = arcpy.Describe(largest_poly)
    ext2 = d.extent
    try:
        mp.defaultCamera.setExtent(ext2)
    except Exception:
        pass
except Exception:
    pass

aprx.save()
print('RESULT_AREA:', cf_area)
print('RESULT_NET_VOLUME:', net_vol)
print('RESULT_RESULT_CSV:', result_csv)
print('RESULT_PROJECT_PATH:', project_path)
print('RESULT_PRE_COPY:', pre_copy)
print('RESULT_POST_COPY:', post_copy)

# Verify key outputs exist from ArcPy perspective
for p in [result_csv, project_path, pre_copy, post_copy, pre_fc, post_fc, pre_clip, post_clip, cutfill_ras]:
    print('EXISTS_CHECK:', p, os.path.exists(p) or arcpy.Exists(p))

