# Generated by SurvyAI
# This script was dynamically generated based on user request
# Generated: 2026-03-29T13:35:52.280031
# 
# Execute this script in ArcGIS Pro's Python Window if needed:
# exec(open(r'C:\Users\UZOR\PycharmProjects\untitled\venv\SurvyAI\scripts\adibawa_volume_cutfill.py').read())

import arcpy, os, math

# Input data paths
pre_csv = r"C:\Users\USER\Documents\SPDC\ADIBAWA WELL 13\Adibawa Well 13A BORROWPIT-Contractor\ADIBAWA WELL 13 BORROW PIT VOLUME COMPUTATION_074938\csv_adibawa__020416_0411510.csv"
post_csv = r"C:\Users\USER\Documents\SPDC\ADIBAWA WELL 13\Adibawa Well 13A BORROWPIT-Contractor\ADIBAWA WELL 13 BORROW PIT VOLUME COMPUTATION_074938\csv_Adi post_031618_062229.csv"
polygon_dwg = r"C:\Users\USER\Documents\SPDC\ADIBAWA WELL 13\Adibawa Well 13A BORROWPIT-Contractor\REVIEW\POST SURVEY FOR ADIBAWA WELL 13 BORROW PIT 13A RESTORATION.dwg"

# Workspace and project
workspace = arcpy.env.scratchFolder if arcpy.env.scratchFolder else arcpy.env.workspace or os.path.dirname(pre_csv)
if not workspace:
    workspace = os.path.dirname(pre_csv)

gdb = os.path.join(workspace, "adibawa_volume.gdb")
if not arcpy.Exists(gdb):
    arcpy.management.CreateFileGDB(os.path.dirname(gdb), os.path.basename(gdb))

arcpy.env.workspace = gdb
arcpy.env.overwriteOutput = True

# Import CSVs to tables
pre_table = os.path.join(gdb, "pre_points_table")
post_table = os.path.join(gdb, "post_points_table")

if arcpy.Exists(pre_table):
    arcpy.management.Delete(pre_table)
if arcpy.Exists(post_table):
    arcpy.management.Delete(post_table)

arcpy.management.TableToTable(pre_csv, gdb, "pre_points_table")
arcpy.management.TableToTable(post_csv, gdb, "post_points_table")

# Discover fields and create point feature classes from N (Y), E (X), Z
for tbl_name, fc_name in [(pre_table, "pre_points"), (post_table, "post_points")]:
    if arcpy.Exists(fc_name):
        arcpy.management.Delete(fc_name)

    fields = [f.name for f in arcpy.ListFields(tbl_name)]
    # Expect 'E', 'N', 'Z'
    x_field = 'E' if 'E' in fields else None
    y_field = 'N' if 'N' in fields else None
    z_field = 'Z' if 'Z' in fields else None

    if not x_field or not y_field or not z_field:
        raise Exception("Required fields E, N, Z not found in table {}. Fields: {}".format(tbl_name, fields))

    sr = arcpy.SpatialReference(26392)  # Minna / Nigeria Mid Belt (common for SPDC; adjust if needed)
    arcpy.management.CreateFeatureclass(gdb, os.path.basename(fc_name), "POINT", spatial_reference=sr, has_z="ENABLED")

    # Add a field to carry Z explicitly
    if 'Height' not in [f.name for f in arcpy.ListFields(fc_name)]:
        arcpy.management.AddField(fc_name, 'Height', 'DOUBLE')

    with arcpy.da.SearchCursor(tbl_name, [x_field, y_field, z_field]) as sc:
        with arcpy.da.InsertCursor(fc_name, ['SHAPE@XY', 'Height']) as ic:
            for x_raw, y_raw, z_raw in sc:
                if x_raw is None or y_raw is None or z_raw is None:
                    continue
                try:
                    x = float(str(x_raw).replace(',', ''))
                    y = float(str(y_raw).replace(',', ''))
                    z = float(str(z_raw).replace(',', ''))
                except:
                    continue
                ic.insertRow(((x, y), z))

# Import DWG polygon, derive boundary polygon
boundary_fc = os.path.join(gdb, "boundary_polygon")
if arcpy.Exists(boundary_fc):
    arcpy.management.Delete(boundary_fc)

# Convert DWG POLYLINEs to feature class, then dissolve to single polygon
# Note: CAD to Geodatabase creates multipatch/polyline/polygon etc.

cad_dataset = arcpy.conversion.CADToGeodatabase(
    Input_CAD_Datasets=polygon_dwg,
    Output_Geodatabase=gdb,
    Out_CAD_Dataset="adibawa_cad",
    Reference_Scale="1000"
)[0]

# Try to find polygon feature class inside the CAD dataset
cad_contents = arcpy.ListFeatureClasses(feature_dataset=cad_dataset)
poly_fc = None
for fc in cad_contents:
    desc = arcpy.Describe(fc)
    if desc.shapeType.lower() in ("polygon", "multipatch"):
        poly_fc = fc
        break

if not poly_fc:
    raise Exception("No polygon feature class found in CAD dataset {}".format(cad_dataset))

# Dissolve all polygons into a single boundary
arcpy.management.Dissolve(poly_fc, boundary_fc)

# Set environment from boundary polygon
boundary_desc = arcpy.Describe(boundary_fc)
arcpy.env.extent = boundary_desc.extent
arcpy.env.mask = boundary_fc
arcpy.env.outputCoordinateSystem = boundary_desc.spatialReference

# IDW for PRE and POST using Height field
cell_size = (boundary_desc.extent.XMax - boundary_desc.extent.XMin) / 200.0
if cell_size <= 0:
    cell_size = "10"

pre_points_fc = os.path.join(gdb, "pre_points")
post_points_fc = os.path.join(gdb, "post_points")

pre_idw = os.path.join(gdb, "pre_idw")
post_idw = os.path.join(gdb, "post_idw")

for out_raster in [pre_idw, post_idw]:
    if arcpy.Exists(out_raster):
        arcpy.management.Delete(out_raster)

pre_idw_raster = arcpy.sa.Idw(pre_points_fc, "Height", cell_size)
pre_idw_raster.save(pre_idw)

post_idw_raster = arcpy.sa.Idw(post_points_fc, "Height", cell_size)
post_idw_raster.save(post_idw)

# CutFill
cutfill_raster = os.path.join(gdb, "cutfill")
if arcpy.Exists(cutfill_raster):
    arcpy.management.Delete(cutfill_raster)

cf = arcpy.sa.CutFill(pre_idw_raster, post_idw_raster)
cf.save(cutfill_raster)

# Summarize volume (m3) and area (m2) for entire raster within mask
# Use RasterToPolygon then Zonal Statistics as Table on absolute values if needed, but CutFill already encodes cut/fill.

# Convert cutfill raster to polygon with VALUE field representing volume/m^2 difference per cell*area
cf_table = os.path.join(gdb, "cutfill_stats")
if arcpy.Exists(cf_table):
    arcpy.management.Delete(cf_table)

# Use RasterToPolygon then AddField+CalculateGeometryAttributes is heavier; instead, use Raster attribute table if integer.

# Use Cell statistics: sum of (VALUE * cell_area) over all cells
cell_area = float(cell_size) * float(cell_size) if isinstance(cell_size, (int, float)) or str(cell_size).replace('.', '', 1).isdigit() else None

# Build raster attribute table to get VALUE and COUNT
arcpy.management.BuildRasterAttributeTable(cutfill_raster, "OVERWRITE")

volume = 0.0
with arcpy.da.SearchCursor(cutfill_raster, ["VALUE", "COUNT"]) as rc:
    for val, cnt in rc:
        if val is None or cnt is None:
            continue
        if cell_area is None:
            raise Exception("Cell area undetermined; cell_size=" + str(cell_size))
        volume += float(val) * float(cnt) * cell_area

# Export result CSV in workspace
out_csv = os.path.join(workspace, "Adibawa_VolumeResult.csv")
with open(out_csv, 'w') as f:
    f.write('Metric,Value,Units\n')
    f.write('Net_Volume,{:.3f},cubic_meters\n'.format(volume))

print('RESULT_VOLUME_CUBIC_METERS:', volume)
print('RESULT_OUTPUT_CSV:', out_csv)

