# Generated by SurvyAI
# This script was dynamically generated based on user request
# Generated: 2026-03-29T12:14:42.533705
# 
# Execute this script in ArcGIS Pro's Python Window if needed:
# exec(open(r'C:\Users\UZOR\PycharmProjects\untitled\venv\SurvyAI\scripts\adibawa_fill_volume.py').read())

import arcpy, os, csv

# Paths
pre_csv = r"C:\Users\USER\Documents\SPDC\ADIBAWA WELL 13\Adibawa Well 13A BORROWPIT-Contractor\ADIBAWA WELL 13 BORROW PIT VOLUME COMPUTATION_074938\csv_adibawa__020416_0411510.csv"
post_csv = r"C:\Users\USER\Documents\SPDC\ADIBAWA WELL 13\Adibawa Well 13A BORROWPIT-Contractor\ADIBAWA WELL 13 BORROW PIT VOLUME COMPUTATION_074938\csv_Adi post_031618_062229.csv"
polygon_dwg = r"C:\Users\USER\Documents\SPDC\ADIBAWA WELL 13\Adibawa WELL 13A BORROWPIT-Contractor\REVIEW\POST SURVEY FOR ADIBAWA WELL 13 BORROW PIT 13A RESTORATION.dwg"
workspace = os.path.dirname(pre_csv)

# Set environment
arcpy.env.overwriteOutput = True
arcpy.env.workspace = workspace

# Create a file geodatabase
gdb = os.path.join(workspace, 'Adibawa_Workspace.gdb')
if not arcpy.Exists(gdb):
    arcpy.CreateFileGDB_management(workspace, 'Adibawa_Workspace.gdb')

# Import DWG polygon as feature class
polygon_fc = os.path.join(gdb, 'BorrowPitBoundary')
if not arcpy.Exists(polygon_fc):
    arcpy.conversion.CADToGeodatabase(polygon_dwg, gdb, 'CAD_Features', '200')
    # Assume polygon layer is named 'Polygon'
    cad_polygon_fc = os.path.join(gdb, 'CAD_Features_Polygon')
    arcpy.management.MakeFeatureLayer(cad_polygon_fc, 'poly_lyr')
    arcpy.management.SelectLayerByAttribute('poly_lyr', 'NEW_SELECTION', "Layer <> ''")
    arcpy.management.CopyFeatures('poly_lyr', polygon_fc)

# Set extent and mask from polygon
arcpy.env.extent = arcpy.Describe(polygon_fc).extent
arcpy.env.mask = polygon_fc

# Function to create point feature class from CSV

def create_points_from_csv(csv_path, fc_name):
    fc = os.path.join(gdb, fc_name)
    if arcpy.Exists(fc):
        arcpy.Delete_management(fc)
    # Create spatial reference (assume projected, use WGS 1984 UTM Zone 32N as placeholder)
    sr = arcpy.SpatialReference(32632)
    arcpy.management.CreateFeatureclass(gdb, fc_name, 'POINT', spatial_reference=sr)
    arcpy.management.AddField(fc, 'Z', 'DOUBLE')
    # Read CSV and insert points
    with open(csv_path, 'r') as f:
        reader = csv.DictReader(f)
        with arcpy.da.InsertCursor(fc, ['SHAPE@XY', 'Z']) as cursor:
            for row in reader:
                try:
                    x = float(row['E'])
                    y = float(row['N'])
                    z = float(row['Z'])
                    cursor.insertRow(((x, y), z))
                except Exception as e:
                    continue
    return fc

pre_points = create_points_from_csv(pre_csv, 'PrePoints')
post_points = create_points_from_csv(post_csv, 'PostPoints')

# Create IDW rasters
cell_size = 1
pre_idw = os.path.join(gdb, 'Pre_IDW')
post_idw = os.path.join(gdb, 'Post_IDW')
arcpy.ddd.Idw(pre_points, 'Z', pre_idw, cell_size)
arcpy.ddd.Idw(post_points, 'Z', post_idw, cell_size)

# CutFill
cutfill_raster = os.path.join(gdb, 'CutFill')
arcpy.ddd.CutFill(post_idw, pre_idw, cutfill_raster)

# Calculate volume by summing positive (fill) values
result_csv = os.path.join(workspace, 'Adibawa_VolumeResult.csv')

# Use RasterToNumPyArray for volume calculation
from arcpy.sa import Raster
import numpy as np

cut_ras = Raster(cutfill_raster)
arr = arcpy.RasterToNumPyArray(cut_ras, nodata_to_value=np.nan)
mean_cell_width = cut_ras.meanCellWidth
mean_cell_height = cut_ras.meanCellHeight
cell_area = mean_cell_width * mean_cell_height

fill_volume = np.nansum(arr[arr > 0]) * cell_area
cut_volume = np.nansum(arr[arr < 0]) * cell_area
net_volume = np.nansum(arr) * cell_area

# Save to CSV
with open(result_csv, 'w', newline='') as f:
    writer = csv.writer(f)
    writer.writerow(['Metric', 'Volume_m3'])
    writer.writerow(['Fill_Volume', fill_volume])
    writer.writerow(['Cut_Volume', cut_volume])
    writer.writerow(['Net_Volume', net_volume])

print('RESULT_FILL_VOLUME:', fill_volume)
print('RESULT_CUT_VOLUME:', cut_volume)
print('RESULT_NET_VOLUME:', net_volume)
print('RESULT_OUTPUT_CSV:', result_csv)

