# Generated by SurvyAI
# This script was dynamically generated based on user request
# Generated: 2026-05-04T18:03:15.656675
#
# REQUIRED checklist for analyst workflows (IDW, Cut Fill, borrow pits):
# - Use a projected CRS with known linear units for volume; log EPSG/WKID.
# - Add every output feature class/raster to the active map (addDataFromPath / layer objects).
# - project.save() after writes so the open Pro window shows new layers.
#
# Execute this script in ArcGIS Pro's Python Window if needed:
# exec(open(r'C:\Users\UZOR\PycharmProjects\untitled\venv\SurvyAI\scripts\adibawa_volume_workflow_retry3.py').read())

import arcpy, os, csv, shutil

pre_src = r"C:\Users\USER\Documents\SPDC\ADIBAWA WELL 13\Adibawa Well 13A BORROWPIT-Contractor\ADIBAWA WELL 13 BORROW PIT VOLUME COMPUTATION_074938\csv_adibawa__020416_0411510.csv"
post_src = r"C:\Users\USER\Documents\SPDC\ADIBAWA WELL 13\Adibawa Well 13A BORROWPIT-Contractor\ADIBAWA WELL 13 BORROW PIT VOLUME COMPUTATION_074938\csv_Adi post_031618_062229.csv"
dwg_path = r"C:\Users\USER\Documents\SPDC\ADIBAWA WELL 13\Adibawa Well 13A BORROWPIT-Contractor\REVIEW\POST SURVEY FOR ADIBAWA WELL 13 BORROW PIT 13A RESTORATION.dwg"
workspace = r"C:\Users\UZOR\PycharmProjects\untitled\venv\SurvyAI"
pre_copy = os.path.join(workspace, os.path.basename(pre_src))
post_copy = os.path.join(workspace, os.path.basename(post_src))
result_csv = os.path.join(workspace, 'Adibawa_VolumeResult.csv')
project_dir = os.path.join(workspace, 'Adibawa_Volume_Project')
os.makedirs(project_dir, exist_ok=True)
project_path = os.path.join(project_dir, 'Adibawa_Volume_Project.aprx')
gdb = os.path.join(project_dir, 'Adibawa_Volume.gdb')
if not arcpy.Exists(gdb):
    arcpy.management.CreateFileGDB(project_dir, 'Adibawa_Volume.gdb')

arcpy.env.workspace = gdb
arcpy.env.overwriteOutput = True
arcpy.env.scratchWorkspace = gdb

shutil.copy2(pre_src, pre_copy)
shutil.copy2(post_src, post_copy)

aprx = None
mp = None
try:
    if os.path.exists(project_path):
        aprx = arcpy.mp.ArcGISProject(project_path)
        maps = aprx.listMaps()
        mp = maps[0] if maps else None
except Exception:
    pass

def safe_num(val):
    return float(str(val).strip().replace(',', ''))

def normalized_header_name(h):
    return ''.join(ch.lower() for ch in str(h) if ch.isalnum())

def detect_fields(csv_path):
    with open(csv_path, 'r', newline='', encoding='utf-8-sig') as f:
        header = next(csv.reader(f))
    norm_map = {normalized_header_name(h): h for h in header}
    x = y = z = None
    for k,h in norm_map.items():
        if x is None and (k in ('e','x','east','easting') or 'east' in k): x = h
        if y is None and (k in ('n','y','north','northing') or 'north' in k): y = h
        if z is None and (k in ('z','rl') or 'elev' in k or 'level' in k or k == 'height'): z = h
    return x, y, z

def make_points(csv_path, fc_name):
    x_field, y_field, z_field = detect_fields(csv_path)
    if not (x_field and y_field and z_field):
        raise RuntimeError('Missing usable X/Y/Z fields in ' + csv_path)
    fc = os.path.join(gdb, fc_name)
    if arcpy.Exists(fc):
        arcpy.management.Delete(fc)
    arcpy.management.CreateFeatureclass(gdb, fc_name, 'POINT', has_z='ENABLED')
    arcpy.management.AddField(fc, 'SRC_ID', 'LONG')
    arcpy.management.AddField(fc, 'Z_VAL', 'DOUBLE')
    cnt = 0
    with open(csv_path, 'r', newline='', encoding='utf-8-sig') as f:
        rdr = csv.DictReader(f)
        with arcpy.da.InsertCursor(fc, ['SRC_ID', 'Z_VAL', 'SHAPE@XYZ']) as ic:
            oid = 1
            for row in rdr:
                try:
                    x = safe_num(row[x_field]); y = safe_num(row[y_field]); z = safe_num(row[z_field])
                    ic.insertRow((oid, z, (x, y, z)))
                    oid += 1
                    cnt += 1
                except Exception:
                    continue
    return fc, cnt

pre_fc, pre_count = make_points(pre_copy, 'pre_points')
post_fc, post_count = make_points(post_copy, 'post_points')
print('RESULT_PRE_POINTS_INSERTED:', pre_count)
print('RESULT_POST_POINTS_INSERTED:', post_count)
if pre_count == 0 or post_count == 0:
    raise RuntimeError('No usable X/Y/Z rows found in PRE or POST CSV.')

cad_ds = os.path.join(gdb, 'cad_dwg')
if arcpy.Exists(cad_ds):
    arcpy.management.Delete(cad_ds)
arcpy.conversion.CADToGeodatabase(dwg_path, gdb, 'cad_dwg', 1000)
polygon_fc = os.path.join(cad_ds, 'Polygon')
polyline_fc = os.path.join(cad_ds, 'Polyline')
analysis_poly = os.path.join(gdb, 'analysis_boundary')
if arcpy.Exists(analysis_poly):
    arcpy.management.Delete(analysis_poly)
if arcpy.Exists(polygon_fc) and int(arcpy.management.GetCount(polygon_fc)[0]) > 0:
    arcpy.management.MultipartToSinglepart(polygon_fc, analysis_poly)
else:
    temp_poly = os.path.join(gdb, 'temp_poly')
    if arcpy.Exists(temp_poly):
        arcpy.management.Delete(temp_poly)
    arcpy.management.FeatureToPolygon(polyline_fc, temp_poly)
    if int(arcpy.management.GetCount(temp_poly)[0]) == 0:
        raise RuntimeError('Could not derive analysis polygon from DWG.')
    arcpy.management.MultipartToSinglepart(temp_poly, analysis_poly)

largest_poly = os.path.join(gdb, 'analysis_boundary_largest')
if arcpy.Exists(largest_poly):
    arcpy.management.Delete(largest_poly)
spref = arcpy.Describe(analysis_poly).spatialReference
arcpy.management.CreateFeatureclass(gdb, 'analysis_boundary_largest', 'POLYGON', spatial_reference=spref)
keep = None
max_area = -1.0
with arcpy.da.SearchCursor(analysis_poly, ['SHAPE@']) as sc:
    for (geom,) in sc:
        if geom and geom.area > max_area:
            max_area = geom.area
            keep = geom
if keep is None:
    raise RuntimeError('No usable polygon geometry from DWG.')
with arcpy.da.InsertCursor(largest_poly, ['SHAPE@']) as ic:
    ic.insertRow([keep])

ext = arcpy.Describe(largest_poly).extent
xmin, ymin, xmax, ymax = ext.XMin, ext.YMin, ext.XMax, ext.YMax
padx = max((xmax - xmin) * 0.02, 1.0)
pady = max((ymax - ymin) * 0.02, 1.0)
arcpy.env.extent = arcpy.Extent(xmin - padx, ymin - pady, xmax + padx, ymax + pady)
arcpy.env.mask = largest_poly
arcpy.env.outputCoordinateSystem = spref
cell_size = max(min((xmax - xmin) / 100.0, (ymax - ymin) / 100.0), 1.0)

arcpy.CheckOutExtension('Spatial')
from arcpy.sa import Idw, ExtractByMask, CutFill
pre_idw = os.path.join(gdb, 'pre_idw')
post_idw = os.path.join(gdb, 'post_idw')
pre_clip = os.path.join(gdb, 'pre_idw_clip')
post_clip = os.path.join(gdb, 'post_idw_clip')
cutfill_ras = os.path.join(gdb, 'cutfill_raster')

Idw(pre_fc, 'Z_VAL', cell_size).save(pre_idw)
Idw(post_fc, 'Z_VAL', cell_size).save(post_idw)
ExtractByMask(pre_idw, largest_poly).save(pre_clip)
ExtractByMask(post_idw, largest_poly).save(post_clip)
CutFill(pre_clip, post_clip).save(cutfill_ras)

cf_area = 0.0
net_vol = 0.0
try:
    with arcpy.da.SearchCursor(cutfill_ras, ['AREA', 'VOLUME']) as sc:
        for a, v in sc:
            if a is not None: cf_area += float(a)
            if v is not None: net_vol += float(v)
except Exception:
    with arcpy.da.SearchCursor(largest_poly, ['SHAPE@AREA']) as sc:
        for (a,) in sc:
            cf_area += float(a)

with open(result_csv, 'w', newline='', encoding='utf-8') as f:
    w = csv.writer(f)
    w.writerow(['Metric', 'Value', 'Units'])
    w.writerow(['PRE_Points_Inserted', pre_count, 'count'])
    w.writerow(['POST_Points_Inserted', post_count, 'count'])
    w.writerow(['Analysis_Area', cf_area, 'square_map_units'])
    w.writerow(['Net_Volume', net_vol, 'cubic_map_units'])
    w.writerow(['Boundary_Source_DWG', dwg_path, 'path'])

if mp:
    for p in [pre_fc, post_fc, largest_poly, pre_clip, post_clip, cutfill_ras]:
        try:
            mp.addDataFromPath(p)
        except Exception:
            pass
    try:
        mp.defaultCamera.setExtent(arcpy.Describe(largest_poly).extent)
    except Exception:
        pass
if aprx:
    aprx.save()

print('RESULT_AREA:', cf_area)
print('RESULT_NET_VOLUME:', net_vol)
print('RESULT_RESULT_CSV:', result_csv)
print('RESULT_PROJECT_PATH:', project_path)
print('RESULT_PRE_COPY:', pre_copy)
print('RESULT_POST_COPY:', post_copy)

