# Generated by SurvyAI
# Automatic fallback after ArcGIS Pro UI bootstrap failed
# Generated: 2026-03-29T14:25:40.547286
# 
# Original interactive script: C:\Users\UZOR\PycharmProjects\untitled\venv\SurvyAI\scripts\adibawa_volume_workflow.py

import arcpy, os, math

# Input paths
pre_excel = r'C:\Users\USER\Documents\SPDC\ADIBAWA WELL 13\Adibawa Well 13A BORROWPIT-Contractor\ADIBAWA WELL 13 BORROW PIT VOLUME COMPUTATION_074938\csv_adibawa__020416_0411510.xlsx'
post_excel = r'C:\Users\USER\Documents\SPDC\ADIBAWA WELL 13\Adibawa Well 13A BORROWPIT-Contractor\ADIBAWA WELL 13 BORROW PIT VOLUME COMPUTATION_074938\csv_Adi post_031618_062229.xlsx'
dwg_path = r'C:\Users\USER\Documents\SPDC\ADIBAWA WELL 13\Adibawa Well 13A BORROWPIT-Contractor\REVIEW\POST SURVEY FOR ADIBAWA WELL 13 BORROW PIT 13A RESTORATION.dwg'

# Workspace (SurvyAI workspace)
workspace = arcpy.env.scratchFolder or arcpy.env.scratchGDB
if not workspace:
    workspace = arcpy.env.workspace or os.getcwd()

print('RESULT_WORKSPACE:', workspace)

# Set environment
arcpy.env.overwriteOutput = True

# Create a file geodatabase in workspace
gdb_path = os.path.join(workspace, 'Adibawa_Workspace.gdb')
if not arcpy.Exists(gdb_path):
    arcpy.management.CreateFileGDB(os.path.dirname(gdb_path), os.path.basename(gdb_path))

arcpy.env.workspace = gdb_path

# Import DWG polygon (assume boundary is in a POLYLINE or POLYGON layer; we will take the largest polygon as mask)
dwg_dataset = arcpy.management.CADToGeodatabase(dwg_path, gdb_path, 'Adibawa_DWG', '200', '')[0]

# Find polygon/line feature classes
fc_list = arcpy.ListFeatureClasses(feature_dataset='Adibawa_DWG')
poly_fc = None
for fc in fc_list:
    desc = arcpy.Describe(fc)
    if desc.shapeType in ['Polygon', 'Polyline']:
        poly_fc = fc
        break

if not poly_fc:
    raise RuntimeError('No polygon or polyline feature class found in DWG-derived dataset.')

# If polyline, convert to polygon
poly_desc = arcpy.Describe(poly_fc)
if poly_desc.shapeType == 'Polyline':
    poly_polygon = os.path.join(gdb_path, 'Adibawa_Boundary')
    arcpy.management.FeatureToPolygon(poly_fc, poly_polygon)
    poly_fc = poly_polygon

# Dissolve to a single boundary polygon
boundary_fc = os.path.join(gdb_path, 'Adibawa_Boundary_Dissolve')
arcpy.management.Dissolve(poly_fc, boundary_fc)

# Get spatial reference from boundary
sr = arcpy.Describe(boundary_fc).spatialReference

# Set env extent/mask/coordinate system from boundary
arcpy.env.extent = arcpy.Describe(boundary_fc).extent
arcpy.env.mask = boundary_fc
arcpy.env.outputCoordinateSystem = sr

# Helper to create point FC from Excel
def excel_to_points(excel_path, out_name):
    # Convert Excel to table in GDB
    tbl_name = out_name + '_tbl'
    tbl_path = os.path.join(gdb_path, tbl_name)
    if arcpy.Exists(tbl_path):
        arcpy.management.Delete(tbl_path)
    arcpy.conversion.ExcelToTable(excel_path, tbl_path)

    # Discover fields
    fields = [f.name for f in arcpy.ListFields(tbl_path)]
    def find_field(candidates):
        for c in candidates:
            for f in fields:
                if f.lower().replace(' ', '').startswith(c.lower()):
                    return f
        return None

    x_field = find_field(['E', 'east', 'easting', 'x'])
    y_field = find_field(['N', 'north', 'northing', 'y'])
    z_field = find_field(['Z', 'elev', 'height'])

    if not x_field or not y_field or not z_field:
        raise RuntimeError('Could not find E/N/Z fields in table %s. Fields: %s' % (tbl_path, fields))

    # Create point feature class
    out_fc = os.path.join(gdb_path, out_name)
    if arcpy.Exists(out_fc):
        arcpy.management.Delete(out_fc)
    arcpy.management.CreateFeatureclass(gdb_path, out_name, 'POINT', spatial_reference=sr)
    arcpy.management.AddField(out_fc, 'SrcOID', 'LONG')
    arcpy.management.AddField(out_fc, 'Z', 'DOUBLE')

    with arcpy.da.SearchCursor(tbl_path, ['OID@', x_field, y_field, z_field]) as sc, \
         arcpy.da.InsertCursor(out_fc, ['SrcOID', 'Z', 'SHAPE@XY']) as ic:
        for oid, x_raw, y_raw, z_raw in sc:
            if x_raw is None or y_raw is None or z_raw is None:
                continue
            try:
                x = float(str(x_raw).replace(',', ''))
                y = float(str(y_raw).replace(',', ''))
                z = float(str(z_raw).replace(',', ''))
            except Exception:
                continue
            ic.insertRow((oid, z, (x, y)))

    return out_fc

pre_points = excel_to_points(pre_excel, 'Adibawa_PRE_Points')
post_points = excel_to_points(post_excel, 'Adibawa_POST_Points')

print('RESULT_PRE_POINTS_FC:', pre_points)
print('RESULT_POST_POINTS_FC:', post_points)

# Create IDW rasters for PRE and POST
cell_size = ''  # let ArcGIS choose
pre_idw = os.path.join(gdb_path, 'Adibawa_PRE_IDW')
post_idw = os.path.join(gdb_path, 'Adibawa_POST_IDW')

for out_raster, in_points in [(pre_idw, pre_points), (post_idw, post_points)]:
    if arcpy.Exists(out_raster):
        arcpy.management.Delete(out_raster)
    arcpy.sa.Idw(in_points, 'Z', cell_size).save(out_raster)

print('RESULT_PRE_IDW_RASTER:', pre_idw)
print('RESULT_POST_IDW_RASTER:', post_idw)

# CutFill volume: pre is base, post is surface
cutfill_raster = os.path.join(gdb_path, 'Adibawa_CutFill')
if arcpy.Exists(cutfill_raster):
    arcpy.management.Delete(cutfill_raster)
cf = arcpy.sa.CutFill(pre_idw, post_idw)
cf.save(cutfill_raster)

print('RESULT_CUTFILL_RASTER:', cutfill_raster)

# Convert CutFill raster to table and summarize volume
zone_fc = boundary_fc
zonal_table = os.path.join(gdb_path, 'Adibawa_CutFill_Table')
if arcpy.Exists(zonal_table):
    arcpy.management.Delete(zonal_table)

# Use Raster to Polygon then Zonal Statistics as Table on absolute volume
abs_cf = arcpy.sa.Abs(cf)
abs_cf_raster = os.path.join(gdb_path, 'Adibawa_CutFill_Abs')
if arcpy.Exists(abs_cf_raster):
    arcpy.management.Delete(abs_cf_raster)
abs_cf.save(abs_cf_raster)

# Use Zonal Statistics as Table to get mean absolute depth, then multiply by area
arcpy.sa.ZonalStatisticsAsTable(zone_fc, 'FID', abs_cf_raster, zonal_table, 'NODATA', 'MEAN')

# Get area of zone polygon in square meters (projected SR assumed)
area_m2 = 0.0
with arcpy.da.SearchCursor(zone_fc, ['SHAPE@AREA']) as cur:
    for (a,) in cur:
        area_m2 += a

mean_abs_depth = 0.0
with arcpy.da.SearchCursor(zonal_table, ['MEAN']) as cur:
    for (m,) in cur:
        if m is not None:
            mean_abs_depth += m

# If multiple zones, take average of means
row_count = int(arcpy.management.GetCount(zonal_table)[0])
if row_count > 0:
    mean_abs_depth = mean_abs_depth / row_count

volume_m3 = area_m2 * mean_abs_depth

print('RESULT_AREA_SQ_M:', area_m2)
print('RESULT_MEAN_ABS_DEPTH_M:', mean_abs_depth)
print('RESULT_VOLUME_CU_M:', volume_m3)

# Export volume result to CSV in workspace
csv_path = os.path.join(workspace, 'Adibawa_VolumeResult.csv')
with open(csv_path, 'w') as f:
    f.write('Area_sq_m,MeanAbsDepth_m,Volume_cu_m\n')
    f.write(f"{area_m2},{mean_abs_depth},{volume_m3}\n")

print('RESULT_CSV_PATH:', csv_path)

