# Generated by SurvyAI
# This script was dynamically generated based on user request
# Generated: 2026-05-04T18:01:54.392212
#
# REQUIRED checklist for analyst workflows (IDW, Cut Fill, borrow pits):
# - Use a projected CRS with known linear units for volume; log EPSG/WKID.
# - Add every output feature class/raster to the active map (addDataFromPath / layer objects).
# - project.save() after writes so the open Pro window shows new layers.
#
# Execute this script in ArcGIS Pro's Python Window if needed:
# exec(open(r'C:\Users\UZOR\PycharmProjects\untitled\venv\SurvyAI\scripts\adibawa_volume_workflow_retry.py').read())

import arcpy, os, csv, shutil, traceback

pre_src = r"C:\Users\USER\Documents\SPDC\ADIBAWA WELL 13\Adibawa Well 13A BORROWPIT-Contractor\ADIBAWA WELL 13 BORROW PIT VOLUME COMPUTATION_074938\csv_adibawa__020416_0411510.csv"
post_src = r"C:\Users\USER\Documents\SPDC\ADIBAWA WELL 13\Adibawa Well 13A BORROWPIT-Contractor\ADIBAWA WELL 13 BORROW PIT VOLUME COMPUTATION_074938\csv_Adi post_031618_062229.csv"
dwg_path = r"C:\Users\USER\Documents\SPDC\ADIBAWA WELL 13\Adibawa Well 13A BORROWPIT-Contractor\REVIEW\POST SURVEY FOR ADIBAWA WELL 13 BORROW PIT 13A RESTORATION.dwg"
workspace = r"C:\Users\UZOR\PycharmProjects\untitled\venv\SurvyAI"
pre_copy = os.path.join(workspace, os.path.basename(pre_src))
post_copy = os.path.join(workspace, os.path.basename(post_src))
result_csv = os.path.join(workspace, 'Adibawa_VolumeResult.csv')
project_dir = os.path.join(workspace, 'Adibawa_Volume_Project')
os.makedirs(project_dir, exist_ok=True)
project_path = os.path.join(project_dir, 'Adibawa_Volume_Project.aprx')
gdb = os.path.join(project_dir, 'Adibawa_Volume.gdb')
if not arcpy.Exists(gdb):
    arcpy.management.CreateFileGDB(project_dir, 'Adibawa_Volume.gdb')

arcpy.env.workspace = gdb
arcpy.env.overwriteOutput = True
arcpy.env.scratchWorkspace = gdb
print('WORKSPACE:', gdb)

shutil.copy2(pre_src, pre_copy)
shutil.copy2(post_src, post_copy)
print('COPIED_PRE:', pre_copy)
print('COPIED_POST:', post_copy)

try:
    if os.path.exists(project_path):
        aprx = arcpy.mp.ArcGISProject(project_path)
    else:
        base = arcpy.mp.ArcGISProject(r"C:\Users\UZOR\PycharmProjects\untitled\venv\SurvyAI\Adibawa_Volume_Project\Adibawa_Volume_Project.aprx")
        base.saveACopy(project_path)
        aprx = arcpy.mp.ArcGISProject(project_path)
except Exception:
    # Create a clean project folder structure even if project bootstrap is limited
    aprx = None
    print('PROJECT_WARN: could not bootstrap aprx immediately; continuing with geoprocessing')

mp = None
if aprx:
    maps = aprx.listMaps()
    mp = maps[0] if maps else None


def detect_fields(csv_path):
    with open(csv_path, 'r', newline='', encoding='utf-8-sig') as f:
        reader = csv.reader(f)
        header = next(reader)
    lower = {h.strip().lower(): h for h in header}
    x = next((v for k,v in lower.items() if k in ('e','east','easting','x')), None)
    y = next((v for k,v in lower.items() if k in ('n','north','northing','y')), None)
    z = next((v for k,v in lower.items() if k in ('z','elev','elevation','level','rl')), None)
    if not (x and y and z):
        for k,v in lower.items():
            if x is None and ('east' in k or k in ('x','e')): x = v
            if y is None and ('north' in k or k in ('y','n')): y = v
            if z is None and ('elev' in k or 'level' in k or k == 'z' or k == 'rl'): z = v
    return header, x, y, z


def make_points_from_csv(csv_path, fc_name):
    header, x_field, y_field, z_field = detect_fields(csv_path)
    print('FIELDS_FOR', csv_path, ':', header)
    print('USING_FIELDS:', x_field, y_field, z_field)
    if not (x_field and y_field and z_field):
        raise RuntimeError(f'Missing usable X/Y/Z fields in {csv_path}. Header={header}')
    fc = os.path.join(gdb, fc_name)
    if arcpy.Exists(fc):
        arcpy.management.Delete(fc)
    sr = arcpy.SpatialReference()
    arcpy.management.CreateFeatureclass(gdb, fc_name, 'POINT', has_z='ENABLED', spatial_reference=sr)
    arcpy.management.AddField(fc, 'SRC_ID', 'LONG')
    arcpy.management.AddField(fc, 'Z_VAL', 'DOUBLE')
    cnt = 0
    with open(csv_path, 'r', newline='', encoding='utf-8-sig') as f:
        rdr = csv.DictReader(f)
        with arcpy.da.InsertCursor(fc, ['SRC_ID','Z_VAL','SHAPE@XYZ']) as ic:
            oid = 1
            for row in rdr:
                try:
                    x = float(str(row[x_field]).replace(',','').strip())
                    y = float(str(row[y_field]).replace(',','').strip())
                    z = float(str(row[z_field]).replace(',','').strip())
                    ic.insertRow((oid, z, (x,y,z)))
                    oid += 1
                    cnt += 1
                except Exception:
                    continue
    return fc, cnt

pre_fc, pre_count = make_points_from_csv(pre_copy, 'pre_points')
post_fc, post_count = make_points_from_csv(post_copy, 'post_points')
print('RESULT_PRE_POINTS_INSERTED:', pre_count)
print('RESULT_POST_POINTS_INSERTED:', post_count)
if pre_count == 0 or post_count == 0:
    raise RuntimeError('No usable X/Y/Z rows found in PRE or POST CSV.')

cad_gdb_parent = project_dir
cad_gdb_name = 'cad_import'
cad_ds = os.path.join(cad_gdb_parent, cad_gdb_name + '.gdb')
if not arcpy.Exists(cad_ds):
    arcpy.conversion.CADToGeodatabase(dwg_path, cad_gdb_parent, cad_gdb_name)
polygon_fc = os.path.join(cad_ds, 'Polygon')
polyline_fc = os.path.join(cad_ds, 'Polyline')
analysis_poly = os.path.join(gdb, 'analysis_boundary')
if arcpy.Exists(analysis_poly):
    arcpy.management.Delete(analysis_poly)

if arcpy.Exists(polygon_fc) and int(arcpy.management.GetCount(polygon_fc)[0]) > 0:
    arcpy.management.MultipartToSinglepart(polygon_fc, analysis_poly)
else:
    tmp_poly = os.path.join(gdb, 'tmp_boundary_poly')
    if arcpy.Exists(tmp_poly):
        arcpy.management.Delete(tmp_poly)
    arcpy.management.FeatureToPolygon(polyline_fc, tmp_poly)
    if int(arcpy.management.GetCount(tmp_poly)[0]) == 0:
        raise RuntimeError('Could not derive analysis polygon from DWG.')
    arcpy.management.MultipartToSinglepart(tmp_poly, analysis_poly)

largest_poly = os.path.join(gdb, 'analysis_boundary_largest')
if arcpy.Exists(largest_poly):
    arcpy.management.Delete(largest_poly)
spref = arcpy.Describe(analysis_poly).spatialReference
arcpy.management.CreateFeatureclass(gdb, 'analysis_boundary_largest', 'POLYGON', spatial_reference=spref)
max_area = -1.0
keep = None
with arcpy.da.SearchCursor(analysis_poly, ['SHAPE@']) as sc:
    for (geom,) in sc:
        if geom and geom.area > max_area:
            max_area = geom.area
            keep = geom
if keep is None:
    raise RuntimeError('No boundary geometry available after DWG import.')
with arcpy.da.InsertCursor(largest_poly, ['SHAPE@']) as ic:
    ic.insertRow([keep])

ext = arcpy.Describe(largest_poly).extent
xmin, ymin, xmax, ymax = ext.XMin, ext.YMin, ext.XMax, ext.YMax
padx = max((xmax-xmin)*0.02, 1.0)
pady = max((ymax-ymin)*0.02, 1.0)
arcpy.env.extent = arcpy.Extent(xmin-padx, ymin-pady, xmax+padx, ymax+pady)
arcpy.env.mask = largest_poly
arcpy.env.outputCoordinateSystem = spref
cell_size = max(min((xmax-xmin)/100.0, (ymax-ymin)/100.0), 1.0)
print('CELL_SIZE:', cell_size)
print('EXTENT:', arcpy.env.extent.XMin, arcpy.env.extent.YMin, arcpy.env.extent.XMax, arcpy.env.extent.YMax)

arcpy.CheckOutExtension('Spatial')
from arcpy.sa import Idw, ExtractByMask, CutFill
pre_idw = os.path.join(gdb, 'pre_idw')
post_idw = os.path.join(gdb, 'post_idw')
pre_clip = os.path.join(gdb, 'pre_idw_clip')
post_clip = os.path.join(gdb, 'post_idw_clip')
cutfill_ras = os.path.join(gdb, 'cutfill_raster')

Idw(pre_fc, 'Z_VAL', cell_size).save(pre_idw)
Idw(post_fc, 'Z_VAL', cell_size).save(post_idw)
ExtractByMask(pre_idw, largest_poly).save(pre_clip)
ExtractByMask(post_idw, largest_poly).save(post_clip)
CutFill(pre_clip, post_clip).save(cutfill_ras)

cf_area = 0.0
net_vol = 0.0
try:
    with arcpy.da.SearchCursor(cutfill_ras, ['AREA','VOLUME']) as sc:
        for a,v in sc:
            if a is not None: cf_area += float(a)
            if v is not None: net_vol += float(v)
except Exception as e:
    print('CUTFILL_TABLE_WARN:', str(e))
    with arcpy.da.SearchCursor(largest_poly, ['SHAPE@AREA']) as sc:
        for (a,) in sc:
            cf_area += float(a)

with open(result_csv, 'w', newline='', encoding='utf-8') as f:
    w = csv.writer(f)
    w.writerow(['Metric','Value','Units'])
    w.writerow(['PRE_Points_Inserted', pre_count, 'count'])
    w.writerow(['POST_Points_Inserted', post_count, 'count'])
    w.writerow(['Analysis_Area', cf_area, 'square_map_units'])
    w.writerow(['Net_Volume', net_vol, 'cubic_map_units'])
    w.writerow(['Boundary_Source_DWG', dwg_path, 'path'])

if mp:
    for p in [pre_fc, post_fc, largest_poly, pre_clip, post_clip, cutfill_ras]:
        try:
            mp.addDataFromPath(p)
        except Exception as e:
            print('ADD_WARN:', p, str(e))
if aprx:
    aprx.save()

print('RESULT_AREA:', cf_area)
print('RESULT_NET_VOLUME:', net_vol)
print('RESULT_RESULT_CSV:', result_csv)
print('RESULT_PROJECT_PATH:', project_path)
print('RESULT_PRE_COPY:', pre_copy)
print('RESULT_POST_COPY:', post_copy)

