# Generated by SurvyAI
# This script was dynamically generated based on user request
# Generated: 2026-05-05T17:50:49.385300
#
# REQUIRED checklist for analyst workflows (IDW, Cut Fill, borrow pits):
# - Use a projected CRS with known linear units for volume; log EPSG/WKID.
# - Add every output feature class/raster to the active map (addDataFromPath / layer objects).
# - project.save() after writes so the open Pro window shows new layers.
#
# Execute this script in ArcGIS Pro's Python Window if needed:
# exec(open(r'C:\Users\UZOR\PycharmProjects\untitled\venv\SurvyAI\scripts\adibawa_tin_volume.py').read())

import arcpy, os, shutil, math, csv, sys
arcpy.env.overwriteOutput = True

# Inputs
pre_src = r"C:\Users\USER\Documents\SPDC\ADIBAWA WELL 13\Adibawa Well 13A BORROWPIT-Contractor\ADIBAWA WELL 13 BORROW PIT VOLUME COMPUTATION_074938\csv_adibawa__020416_0411510.csv"
post_src = r"C:\Users\USER\Documents\SPDC\ADIBAWA WELL 13\Adibawa Well 13A BORROWPIT-Contractor\ADIBAWA WELL 13 BORROW PIT VOLUME COMPUTATION_074938\csv_Adi post_031618_062229.csv"
dwg_path = r"C:\Users\USER\Documents\SPDC\ADIBAWA WELL 13\Adibawa Well 13A BORROWPIT-Contractor\REVIEW\POST SURVEY FOR ADIBAWA WELL 13 BORROW PIT 13A RESTORATION.dwg"
workspace = r"C:\Users\UZOR\PycharmProjects\untitled\venv\SurvyAI"
project_dir = os.path.join(workspace, "Adibawa_TIN_Volume")
project_path = os.path.join(project_dir, "Adibawa_TIN_Volume.aprx")
out_csv = os.path.join(workspace, "Adibawa_VolumeResult2.csv")
pre_copy = os.path.join(workspace, os.path.basename(pre_src))
post_copy = os.path.join(workspace, os.path.basename(post_src).replace(' ', '_'))

sr = arcpy.SpatialReference(26392)  # Minna / Nigeria Mid Belt

os.makedirs(project_dir, exist_ok=True)
if os.path.exists(pre_src):
    shutil.copy2(pre_src, pre_copy)
if os.path.exists(post_src):
    shutil.copy2(post_src, post_copy)

# Create project if needed
if not os.path.exists(project_path):
    arcpy.management.CreateProject(project_dir, "Adibawa_TIN_Volume", "MAP")

aprx = arcpy.mp.ArcGISProject(project_path)
maps = aprx.listMaps()
mp = maps[0] if maps else aprx.createMap("Map")

# GDB
home = project_dir
gdb = os.path.join(home, "Adibawa_TIN_Volume.gdb")
if not arcpy.Exists(gdb):
    arcpy.management.CreateFileGDB(home, "Adibawa_TIN_Volume.gdb")
arcpy.env.workspace = gdb
print("WORKSPACE:", gdb)

# Prepare CSV readers and detect fields

def detect_fields(csv_path):
    with open(csv_path, 'r', newline='', encoding='utf-8-sig') as f:
        reader = csv.DictReader(f)
        fields = reader.fieldnames or []
    lower = {k.lower().strip(): k for k in fields}
    x = None; y = None; z = None
    for cand in ['e', 'east', 'easting', 'x']:
        for lk, orig in lower.items():
            if lk == cand or cand in lk:
                x = orig; break
        if x: break
    for cand in ['n', 'north', 'northing', 'y']:
        for lk, orig in lower.items():
            if lk == cand or cand in lk:
                y = orig; break
        if y: break
    for cand in ['z', 'elev', 'elevation', 'level', 'rl']:
        for lk, orig in lower.items():
            if lk == cand or cand in lk:
                z = orig; break
        if z: break
    return fields, x, y, z

pre_fields, pre_x, pre_y, pre_z = detect_fields(pre_copy)
post_fields, post_x, post_y, post_z = detect_fields(post_copy)
if not (pre_x and pre_y and pre_z and post_x and post_y and post_z):
    raise RuntimeError(f"Could not detect E/N/Z fields. PRE={pre_fields}, POST={post_fields}")

# Create point FCs manually from CSV

def create_points(csv_path, fc_name, x_field, y_field, z_field):
    fc = os.path.join(gdb, fc_name)
    if arcpy.Exists(fc):
        arcpy.management.Delete(fc)
    arcpy.management.CreateFeatureclass(gdb, fc_name, 'POINT', spatial_reference=sr, has_z='ENABLED')
    arcpy.management.AddField(fc, 'ZVAL', 'DOUBLE')
    inserted = 0
    with open(csv_path, 'r', newline='', encoding='utf-8-sig') as f, \
         arcpy.da.InsertCursor(fc, ['SHAPE@XYZ', 'ZVAL']) as ic:
        reader = csv.DictReader(f)
        for row in reader:
            try:
                x = float(str(row[x_field]).replace(',', '').strip())
                y = float(str(row[y_field]).replace(',', '').strip())
                z = float(str(row[z_field]).replace(',', '').strip())
            except Exception:
                continue
            ic.insertRow(((x, y, z), z))
            inserted += 1
    return fc, inserted

pre_fc, pre_count = create_points(pre_copy, 'PRE_POINTS', pre_x, pre_y, pre_z)
post_fc, post_count = create_points(post_copy, 'POST_POINTS', post_x, post_y, post_z)

# Import DWG boundary
cad_gdb = os.path.join(gdb, 'cad_import.gdb')
if arcpy.Exists(cad_gdb):
    arcpy.management.Delete(cad_gdb)
arcpy.conversion.CADToGeodatabase(dwg_path, gdb, 'adibawa_cad')
poly_fc = os.path.join(gdb, 'adibawa_cad', 'Polygon')
pline_fc = os.path.join(gdb, 'adibawa_cad', 'Polyline')

boundary_fc = os.path.join(gdb, 'BOUNDARY')
if arcpy.Exists(boundary_fc):
    arcpy.management.Delete(boundary_fc)

# Prefer polygon features; fallback to closed polyline -> polygon
if arcpy.Exists(poly_fc) and int(arcpy.management.GetCount(poly_fc)[0]) > 0:
    arcpy.management.CopyFeatures(poly_fc, boundary_fc)
else:
    tmp_lines = os.path.join(gdb, 'tmp_lines')
    if arcpy.Exists(tmp_lines):
        arcpy.management.Delete(tmp_lines)
    arcpy.management.CopyFeatures(pline_fc, tmp_lines)
    arcpy.management.FeatureToPolygon(tmp_lines, boundary_fc)

# Dissolve to single boundary if multiple polygons
boundary_single = os.path.join(gdb, 'BOUNDARY_SINGLE')
if arcpy.Exists(boundary_single):
    arcpy.management.Delete(boundary_single)
arcpy.management.Dissolve(boundary_fc, boundary_single)

# TINs
pre_tin = os.path.join(project_dir, 'pre_surface')
post_tin = os.path.join(project_dir, 'post_surface')
for tin in [pre_tin, post_tin]:
    if arcpy.Exists(tin):
        arcpy.management.Delete(tin)

arcpy.ddd.CreateTin(pre_tin, sr, [[pre_fc, 'ZVAL', 'masspoints'], [boundary_single, '<None>', 'hardclip']], 'DELAUNAY')
arcpy.ddd.CreateTin(post_tin, sr, [[post_fc, 'ZVAL', 'masspoints'], [boundary_single, '<None>', 'hardclip']], 'DELAUNAY')

# Rasterize TINs for differencing / volume over same grid
pre_ras = os.path.join(gdb, 'pre_tin_ras')
post_ras = os.path.join(gdb, 'post_tin_ras')
for ras in [pre_ras, post_ras]:
    if arcpy.Exists(ras):
        arcpy.management.Delete(ras)

# Cell size from boundary extent ~ reasonable dense grid
ext = arcpy.Describe(boundary_single).extent
width = max(ext.width, 1.0)
height = max(ext.height, 1.0)
cell = max(min(width, height) / 100.0, 0.5)
arcpy.env.extent = boundary_single
arcpy.env.mask = boundary_single
arcpy.env.outputCoordinateSystem = sr

arcpy.ddd.TinRaster(pre_tin, pre_ras, 'FLOAT', 'LINEAR', 'CELLSIZE', cell)
arcpy.ddd.TinRaster(post_tin, post_ras, 'FLOAT', 'LINEAR', 'CELLSIZE', cell)

# Difference raster
from arcpy.sa import Minus, ExtractByMask
arcpy.CheckOutExtension('Spatial')
dz = os.path.join(gdb, 'dz_tin')
if arcpy.Exists(dz):
    arcpy.management.Delete(dz)
dz_tmp = Minus(post_ras, pre_ras)
dz_mask = ExtractByMask(dz_tmp, boundary_single)
dz_mask.save(dz)

# Compute area/volume from raster cell values
cellx = float(arcpy.management.GetRasterProperties(dz, 'CELLSIZEX')[0])
celly = float(arcpy.management.GetRasterProperties(dz, 'CELLSIZEY')[0])
cell_area = cellx * celly
fill = 0.0
cut = 0.0
count = 0
with arcpy.da.SearchCursor(dz, ['VALUE']) as cur:
    for (v,) in cur:
        if v is None:
            continue
        count += 1
        if v > 0:
            fill += v * cell_area
        elif v < 0:
            cut += v * cell_area
analysis_area = count * cell_area
net = fill + cut

# Export CSV
with open(out_csv, 'w', newline='', encoding='utf-8') as f:
    w = csv.writer(f)
    w.writerow(['metric', 'value', 'unit'])
    w.writerow(['pre_points_inserted', pre_count, 'count'])
    w.writerow(['post_points_inserted', post_count, 'count'])
    w.writerow(['analysis_area', analysis_area, 'square_meters'])
    w.writerow(['fill_volume', fill, 'cubic_meters'])
    w.writerow(['cut_volume', cut, 'cubic_meters'])
    w.writerow(['net_volume', net, 'cubic_meters'])

# Add layers to map
for p in [boundary_single, pre_fc, post_fc, pre_ras, post_ras, dz]:
    try:
        mp.addDataFromPath(p)
    except Exception as e:
        print('ADD_WARN', p, str(e))

aprx.save()

print('RESULT_PRE_POINTS_INSERTED:', pre_count)
print('RESULT_POST_POINTS_INSERTED:', post_count)
print('RESULT_ANALYSIS_AREA_SQM:', analysis_area)
print('RESULT_FILL_VOLUME_M3:', fill)
print('RESULT_CUT_VOLUME_M3:', cut)
print('RESULT_NET_VOLUME_M3:', net)
print('RESULT_OUTPUT_CSV:', out_csv)
print('RESULT_PRE_COPY:', pre_copy)
print('RESULT_POST_COPY:', post_copy)
print('RESULT_PROJECT_PATH:', project_path)
print('RESULT_PRE_TIN:', pre_tin)
print('RESULT_POST_TIN:', post_tin)
