# Generated by SurvyAI
# Automatic fallback after ArcGIS Pro UI bootstrap failed
# Generated: 2026-03-29T14:36:36.790815
# 
# Original interactive script: C:\Users\UZOR\PycharmProjects\untitled\venv\SurvyAI\scripts\adibawa_cutfill_workflow.py

import arcpy, os, math

# Workspace and input paths
pre_csv = r"C:\Users\USER\Documents\SPDC\ADIBAWA WELL 13\Adibawa Well 13A BORROWPIT-Contractor\ADIBAWA WELL 13 BORROW PIT VOLUME COMPUTATION_074938\csv_adibawa__020416_0411510.csv"
post_csv = r"C:\Users\USER\Documents\SPDC\ADIBAWA WELL 13\Adibawa Well 13A BORROWPIT-Contractor\ADIBAWA WELL 13 BORROW PIT VOLUME COMPUTATION_074938\csv_Adi post_031618_062229.csv"

# SurvyAI workspace (same folder as PRE CSV, per instructions)
workspace = os.path.dirname(pre_csv)
arcpy.env.workspace = workspace
arcpy.env.overwriteOutput = True

# Copy CSVs into SurvyAI workspace folder (here, workspace already)
pre_csv_copy = os.path.join(workspace, "PRE_Adibawa.csv")
post_csv_copy = os.path.join(workspace, "POST_Adibawa.csv")

if pre_csv != pre_csv_copy:
    arcpy.management.Copy(pre_csv, pre_csv_copy)
else:
    pre_csv_copy = pre_csv

if post_csv != post_csv_copy:
    arcpy.management.Copy(post_csv, post_csv_copy)
else:
    post_csv_copy = post_csv

# Create a file geodatabase for this workflow
gdb = os.path.join(workspace, "Adibawa_GIS.gdb")
if not arcpy.Exists(gdb):
    arcpy.management.CreateFileGDB(workspace, "Adibawa_GIS.gdb")

arcpy.env.workspace = gdb

# Import DWG polygon as feature class and derive boundary polygon
source_dwg = r"C:\Users\USER\Documents\SPDC\ADIBAWA WELL 13\Adibawa Well 13A BORROWPIT-Contractor\REVIEW\POST SURVEY FOR ADIBAWA WELL 13 BORROW PIT 13A RESTORATION.dwg"

# Use CADToGeodatabase to bring in CAD content
cad_gdb = os.path.join(workspace, "Adibawa_CAD.gdb")
if not arcpy.Exists(cad_gdb):
    arcpy.conversion.CADToGeodatabase(source_dwg, cad_gdb, "Adibawa_CAD", "2000", "ByLayer")

# Assume polygon feature class is named "Adibawa_CAD_Polygon" inside a feature dataset
arcpy.env.workspace = cad_gdb
fds_list = arcpy.ListDatasets()
polygon_fc = None
for fds in fds_list:
    polys = arcpy.ListFeatureClasses(feature_dataset=fds)
    for fc in polys:
        desc = arcpy.Describe(fc)
        if desc.shapeType.lower() == 'polygon':
            polygon_fc = fc
            break
    if polygon_fc:
        break

if not polygon_fc:
    raise RuntimeError("No polygon feature class found in CAD-derived geodatabase.")

boundary_fc = os.path.join(gdb, "Adibawa_Boundary")
if not arcpy.Exists(boundary_fc):
    arcpy.management.CopyFeatures(os.path.join(cad_gdb, polygon_fc), boundary_fc)

# Set environment from boundary polygon
boundary_desc = arcpy.Describe(boundary_fc)
arcpy.env.extent = boundary_desc.extent
arcpy.env.mask = boundary_fc
arcpy.env.outputCoordinateSystem = boundary_desc.spatialReference

# Helper: create points from CSV
arcpy.env.workspace = gdb

sr = boundary_desc.spatialReference

pre_points = os.path.join(gdb, "PRE_points")
post_points = os.path.join(gdb, "POST_points")

for fc in [pre_points, post_points]:
    if arcpy.Exists(fc):
        arcpy.management.Delete(fc)

# Use XYTableToPoint directly on CSVs; ArcGIS will infer E, N, Z field types
pre_table = pre_csv_copy
post_table = post_csv_copy

# Determine field names (assumed 'E' and 'N' based on csv_to_excel inspection)
pre_fields = [f.name for f in arcpy.ListFields(pre_table)]
post_fields = [f.name for f in arcpy.ListFields(post_table)]

if not ("E" in pre_fields and "N" in pre_fields and "Z" in pre_fields):
    raise RuntimeError("PRE CSV does not contain required E, N, Z fields.")
if not ("E" in post_fields and "N" in post_fields and "Z" in post_fields):
    raise RuntimeError("POST CSV does not contain required E, N, Z fields.")

arcpy.management.XYTableToPoint(pre_table, pre_points, "E", "N", "Z", sr)
arcpy.management.XYTableToPoint(post_table, post_points, "E", "N", "Z", sr)

# Create IDW rasters
cell_size = (boundary_desc.extent.width + boundary_desc.extent.height) / 1000.0
if cell_size <= 0:
    cell_size = 1

pre_idw = os.path.join(gdb, "PRE_IDW")
post_idw = os.path.join(gdb, "POST_IDW")

for r in [pre_idw, post_idw]:
    if arcpy.Exists(r):
        arcpy.management.Delete(r)

pre_idw_res = arcpy.sa.Idw(pre_points, "Z", cell_size)
pre_idw_res.save(pre_idw)

post_idw_res = arcpy.sa.Idw(post_points, "Z", cell_size)
post_idw_res.save(post_idw)

# Run CutFill: POST minus PRE (assuming POST is final/restored)
cutfill_raster = os.path.join(gdb, "CutFill_PRE_POST")
if arcpy.Exists(cutfill_raster):
    arcpy.management.Delete(cutfill_raster)

cf = arcpy.sa.CutFill(post_idw, pre_idw)
cf.save(cutfill_raster)

# Compute total fill volume (positive values) and cut volume (negative)
# Use RasterToNumPyArray for zonal stats within the boundary
import numpy as np

arr = arcpy.da.FeatureClassToNumPyArray(boundary_fc, ["SHAPE@"], explode_to_points=False)
geom = arr[0][0]

# Clip CutFill raster to boundary explicitly
cf_clip = os.path.join(gdb, "CutFill_Clip")
if arcpy.Exists(cf_clip):
    arcpy.management.Delete(cf_clip)

arcpy.sa.ExtractByMask(cf, boundary_fc).save(cf_clip)

r_desc = arcpy.Describe(cf_clip)
cell_w = r_desc.meanCellWidth
cell_h = r_desc.meanCellHeight
cell_area = cell_w * cell_h

lower_left = arcpy.Point(r_desc.extent.XMin, r_desc.extent.YMin)
arr_cf = arcpy.RasterToNumPyArray(cf_clip, nodata_to_value=np.nan)

fill_mask = arr_cf > 0
cut_mask = arr_cf < 0

fill_volume = float(np.nansum(arr_cf[fill_mask]) * cell_area) if np.any(fill_mask) else 0.0
cut_volume = float(np.nansum(arr_cf[cut_mask]) * cell_area) if np.any(cut_mask) else 0.0
net_volume = fill_volume + cut_volume

# Export results to CSV in workspace
result_csv = os.path.join(workspace, "Adibawa_VolumeResult.csv")
with open(result_csv, 'w') as f:
    f.write('Type,Volume_m3\n')
    f.write('Fill,{:.3f}\n'.format(fill_volume))
    f.write('Cut,{:.3f}\n'.format(cut_volume))
    f.write('Net,{:.3f}\n'.format(net_volume))

print('RESULT_FILL_VOLUME_M3:', fill_volume)
print('RESULT_CUT_VOLUME_M3:', cut_volume)
print('RESULT_NET_VOLUME_M3:', net_volume)
print('RESULT_CSV_PATH:', result_csv)

