# Generated by SurvyAI
# This script was dynamically generated based on user request
# Generated: 2026-04-01T08:01:55.177501
# 
# Execute this script in ArcGIS Pro's Python Window if needed:
# exec(open(r'C:\Users\UZOR\PycharmProjects\untitled\venv\SurvyAI\scripts\adibawa_pre_post_cutfill.py').read())

import arcpy, os, csv, math, shutil, sys, traceback
from arcpy.sa import Idw, CutFill

arcpy.env.overwriteOutput = True
base_workspace = os.getcwd()
workspace = base_workspace
pre_src = r"C:\Users\USER\Documents\SPDC\ADIBAWA WELL 13\Adibawa Well 13A BORROWPIT-Contractor\ADIBAWA WELL 13 BORROW PIT VOLUME COMPUTATION_074938\csv_adibawa__020416_0411510.csv"
post_src = r"C:\Users\USER\Documents\SPDC\ADIBAWA WELL 13\Adibawa Well 13A BORROWPIT-Contractor\ADIBAWA WELL 13 BORROW PIT VOLUME COMPUTATION_074938\csv_Adi post_031618_062229.csv"
dwg_path = r"C:\Users\USER\Documents\SPDC\ADIBAWA WELL 13\Adibawa Well 13A BORROWPIT-Contractor\REVIEW\POST SURVEY FOR ADIBAWA WELL 13 BORROW PIT 13A RESTORATION.dwg"
pre_copy = os.path.join(workspace, 'csv_adibawa__020416_0411510.csv')
post_copy = os.path.join(workspace, 'csv_Adi post_031618_062229.csv')
out_csv = os.path.join(workspace, 'Adibawa_VolumeResult.csv')
project_dir = r"C:\Users\USER\Documents\SPDC\ADIBAWA WELL 13\Adibawa Well 13A BORROWPIT-Contractor\ADIBAWA WELL 13 BORROW PIT VOLUME COMPUTATION_074938\Adibawa_BorrowPit_Volume"
os.makedirs(project_dir, exist_ok=True)
gdb = os.path.join(project_dir, 'Adibawa_BorrowPit_Volume.gdb')
if not arcpy.Exists(gdb):
    arcpy.management.CreateFileGDB(project_dir, 'Adibawa_BorrowPit_Volume.gdb')

# copy source csv files into SurvyAI workspace
shutil.copy2(pre_src, pre_copy)
shutil.copy2(post_src, post_copy)
print('RESULT_PRE_COPY:', pre_copy)
print('RESULT_POST_COPY:', post_copy)

# ensure Spatial Analyst
arcpy.CheckOutExtension('Spatial')

# create or open project
aprx_path = r"C:\Users\USER\Documents\SPDC\ADIBAWA WELL 13\Adibawa Well 13A BORROWPIT-Contractor\ADIBAWA WELL 13 BORROW PIT VOLUME COMPUTATION_074938\Adibawa_BorrowPit_Volume\Adibawa_BorrowPit_Volume.aprx"
if not os.path.exists(aprx_path):
    arcpy.mp.CreateProject('Adibawa_BorrowPit_Volume', project_dir, 'MAP')
aprx = arcpy.mp.ArcGISProject(aprx_path)
maps = aprx.listMaps()
mp = maps[0] if maps else aprx.createMap('Map')

# import DWG and find polygon boundary
cad_ds = os.path.join(project_dir, 'cad_import.gdb', 'cad_import')
cad_gdb = os.path.join(project_dir, 'cad_import.gdb')
if arcpy.Exists(cad_gdb):
    arcpy.management.Delete(cad_gdb)
arcpy.conversion.CADToGeodatabase(dwg_path, project_dir, 'cad_import')
polygon_candidates = []
for ds_name in ['Polygon', 'Polyline', 'Point', 'Annotation']:
    fc = os.path.join(cad_gdb, 'cad_import', ds_name) if arcpy.Exists(os.path.join(cad_gdb, 'cad_import', ds_name)) else os.path.join(cad_gdb, ds_name)
    if arcpy.Exists(fc):
        polygon_candidates.append(fc)

boundary_fc = None
boundary_geom = None
max_area = -1
for fc in polygon_candidates:
    shape_type = arcpy.Describe(fc).shapeType
    if shape_type != 'Polygon':
        continue
    with arcpy.da.SearchCursor(fc, ['OID@', 'SHAPE@']) as cur:
        for oid, geom in cur:
            if geom and geom.area > max_area:
                max_area = geom.area
                boundary_fc = fc
                boundary_geom = geom

if boundary_fc is None or boundary_geom is None:
    raise RuntimeError('No usable polygon found in DWG for boundary/extent mask')

mask_fc = os.path.join(gdb, 'borrowpit_mask')
if arcpy.Exists(mask_fc):
    arcpy.management.Delete(mask_fc)
arcpy.management.CreateFeatureclass(gdb, 'borrowpit_mask', 'POLYGON', spatial_reference=arcpy.Describe(boundary_fc).spatialReference)
with arcpy.da.InsertCursor(mask_fc, ['SHAPE@']) as ic:
    ic.insertRow([boundary_geom])

sr = arcpy.Describe(mask_fc).spatialReference
ext = arcpy.Describe(mask_fc).extent
# expand extent slightly to avoid extent issues
xpad = max((ext.XMax - ext.XMin) * 0.01, 1.0)
ypad = max((ext.YMax - ext.YMin) * 0.01, 1.0)
expanded = arcpy.Extent(ext.XMin - xpad, ext.YMin - ypad, ext.XMax + xpad, ext.YMax + ypad)
arcpy.env.extent = expanded
arcpy.env.mask = mask_fc
arcpy.env.outputCoordinateSystem = sr
arcpy.env.snapRaster = None
arcpy.env.cellSize = 'MINOF'

# helpers

def detect_fields(csv_path):
    with open(csv_path, 'r', newline='', encoding='utf-8-sig') as f:
        reader = csv.reader(f)
        header = next(reader)
    norm = {h.strip(): h for h in header}
    lowered = {h.lower().strip(): h for h in header}
    def pick(cands):
        for c in cands:
            for k,v in lowered.items():
                if k == c:
                    return v
        for c in cands:
            for k,v in lowered.items():
                if c in k:
                    return v
        return None
    x_field = pick(['e','east','easting','x'])
    y_field = pick(['n','north','northing','y'])
    z_field = pick(['z','elev','elevation','level','rl'])
    return header, x_field, y_field, z_field

def csv_to_points(csv_path, out_name):
    header, x_field, y_field, z_field = detect_fields(csv_path)
    if not x_field or not y_field or not z_field:
        raise RuntimeError(f'Missing usable E/N/Z fields in {csv_path}. Header={header}')
    out_fc = os.path.join(gdb, out_name)
    if arcpy.Exists(out_fc):
        arcpy.management.Delete(out_fc)
    arcpy.management.CreateFeatureclass(gdb, out_name, 'POINT', spatial_reference=sr)
    arcpy.management.AddField(out_fc, 'ZVAL', 'DOUBLE')
    inserted = 0
    with open(csv_path, 'r', newline='', encoding='utf-8-sig') as f:
        reader = csv.DictReader(f)
        with arcpy.da.InsertCursor(out_fc, ['SHAPE@XY', 'ZVAL']) as ic:
            for row in reader:
                try:
                    x = float(str(row[x_field]).replace(',', '').strip())
                    y = float(str(row[y_field]).replace(',', '').strip())
                    z = float(str(row[z_field]).replace(',', '').strip())
                except Exception:
                    continue
                if math.isnan(x) or math.isnan(y) or math.isnan(z):
                    continue
                ic.insertRow([(x,y), z])
                inserted += 1
    if inserted == 0:
        raise RuntimeError(f'No usable rows inserted from {csv_path}')
    return out_fc, inserted, x_field, y_field, z_field

pre_fc, pre_count, pre_x, pre_y, pre_z = csv_to_points(pre_copy, 'pre_points')
post_fc, post_count, post_x, post_y, post_z = csv_to_points(post_copy, 'post_points')
print('RESULT_PRE_POINTS_INSERTED:', pre_count)
print('RESULT_POST_POINTS_INSERTED:', post_count)
print('RESULT_PRE_FIELDS:', pre_x, pre_y, pre_z)
print('RESULT_POST_FIELDS:', post_x, post_y, post_z)

# Choose cell size from extent size
width = expanded.XMax - expanded.XMin
height = expanded.YMax - expanded.YMin
cell = max(min(width, height) / 100.0, 0.5)
arcpy.env.cellSize = cell

pre_raster = os.path.join(gdb, 'pre_idw')
post_raster = os.path.join(gdb, 'post_idw')
cutfill_raster = os.path.join(gdb, 'cutfill')
for p in [pre_raster, post_raster, cutfill_raster]:
    if arcpy.Exists(p):
        arcpy.management.Delete(p)

# run idw with retry for extent
for attempt in range(2):
    try:
        pre_idw = Idw(pre_fc, 'ZVAL', cell_size=cell)
        pre_idw.save(pre_raster)
        post_idw = Idw(post_fc, 'ZVAL', cell_size=cell)
        post_idw.save(post_raster)
        break
    except Exception as e:
        msg = arcpy.GetMessages(2)
        if '010092' in msg or 'Invalid output extent' in str(e):
            xpad *= 2
            ypad *= 2
            expanded = arcpy.Extent(ext.XMin - xpad, ext.YMin - ypad, ext.XMax + xpad, ext.YMax + ypad)
            arcpy.env.extent = expanded
            continue
        raise

cf = CutFill(pre_raster, post_raster)
cf.save(cutfill_raster)

# summarize cut/fill volume by reading raster attribute table
arcpy.management.BuildRasterAttributeTable(cutfill_raster, 'Overwrite')
fields = [f.name for f in arcpy.ListFields(cutfill_raster)]
count_field = 'COUNT' if 'COUNT' in fields else next((f for f in fields if f.upper() == 'COUNT'), None)
area_field = next((f for f in fields if f.upper() in ['AREA','AREA_2D']), None)
vol_field = next((f for f in fields if f.upper() in ['VOLUME','VOL']) or 'VOLUME' in f.upper(), None)
if vol_field is None:
    raise RuntimeError(f'Could not find volume field in cutfill raster fields: {fields}')
zone_area = boundary_geom.area
fill_volume = 0.0
cut_volume = 0.0
net_volume = 0.0
with arcpy.da.SearchCursor(cutfill_raster, [vol_field]) as cur:
    for (v,) in cur:
        if v is None:
            continue
        net_volume += float(v)
        if float(v) > 0:
            fill_volume += float(v)
        elif float(v) < 0:
            cut_volume += float(v)

with open(out_csv, 'w', newline='', encoding='utf-8') as f:
    writer = csv.writer(f)
    writer.writerow(['Metric','Value','Unit'])
    writer.writerow(['Boundary_Area', zone_area, 'square_meters'])
    writer.writerow(['Fill_Volume', fill_volume, 'cubic_meters'])
    writer.writerow(['Cut_Volume', cut_volume, 'cubic_meters'])
    writer.writerow(['Net_Volume', net_volume, 'cubic_meters'])
    writer.writerow(['Pre_Points_Inserted', pre_count, 'count'])
    writer.writerow(['Post_Points_Inserted', post_count, 'count'])

# add layers to map where possible
for ds in [mask_fc, pre_fc, post_fc, pre_raster, post_raster, cutfill_raster]:
    try:
        mp.addDataFromPath(ds)
    except Exception:
        pass
aprx.save()

print('RESULT_AREA:', zone_area)
print('RESULT_FILL_VOLUME:', fill_volume)
print('RESULT_CUT_VOLUME:', cut_volume)
print('RESULT_NET_VOLUME:', net_volume)
print('RESULT_OUTPUT_CSV:', out_csv)
print('RESULT_PROJECT:', aprx_path)

