# Generated by SurvyAI
# This script was dynamically generated based on user request
# Generated: 2026-02-08T10:04:39.748386
# 
# Execute this script in ArcGIS Pro's Python Window if needed:
# exec(open(r'C:\Users\UZOR\PycharmProjects\untitled\venv\SurvyAI\scripts\csv_to_xlsx_coords4.py').read())

import arcpy, os, csv

csv_path = r"C:\Users\UZOR\PycharmProjects\untitled\venv\SurvyAI\Coords.csv"
xlsx_path = r"C:\Users\UZOR\PycharmProjects\untitled\venv\SurvyAI\Coords.xlsx"

# Simple CSV to Excel conversion using arcpy.TableToTable and Excel conversion
workspace = os.path.dirname(csv_path)
arcpy.env.workspace = workspace

# Create a geodatabase table from CSV
gdb_path = os.path.join(workspace, "temp_coords.gdb")
if not arcpy.Exists(gdb_path):
    arcpy.management.CreateFileGDB(workspace, "temp_coords.gdb")

table_in_gdb = os.path.join(gdb_path, "coords_table")
if arcpy.Exists(table_in_gdb):
    arcpy.management.Delete(table_in_gdb)

arcpy.conversion.TableToTable(csv_path, gdb_path, "coords_table")

# Export that table to Excel
if arcpy.Exists(xlsx_path):
    arcpy.management.Delete(xlsx_path)

arcpy.conversion.TableToExcel(table_in_gdb, xlsx_path)

print("RESULT_CSV_TO_XLSX:SUCCESS", xlsx_path)
