# Generated by SurvyAI
# This script was dynamically generated based on user request
# Generated: 2026-03-28T13:04:24.397200
# 
# Execute this script in ArcGIS Pro's Python Window if needed:
# exec(open(r'C:\Users\UZOR\PycharmProjects\untitled\venv\SurvyAI\scripts\dynexec_arcgis_1d0a60a1_a1.py').read())

import arcpy, os, math

# Inputs
pre_excel = r"C:\\Users\\USER\\Documents\\SPDC\\ADIBAWA WELL 13\\Adibawa Well 13A BORROWPIT-Contractor\\ADIBAWA WELL 13 BORROW PIT VOLUME COMPUTATION_074938\\csv_adibawa__020416_0411510.xlsx"
post_excel = r"C:\\Users\\USER\\Documents\\SPDC\\ADIBAWA WELL 13\\Adibawa Well 13A BORROWPIT-Contractor\\ADIBAWA WELL 13 BORROW PIT VOLUME COMPUTATION_074938\\csv_Adi post_031618_062229.xlsx"
dwg_path = r"C:\\Users\\USER\\Documents\\SPDC\\ADIBAWA WELL 13\\Adibawa Well 13A BORROWPIT-Contractor\\REVIEW\\POST SURVEY FOR ADIBAWA WELL 13 BORROW PIT 13A RESTORATION.dwg"

base_folder = os.path.dirname(pre_excel)
project_name = "Adibawa_Well13_CutFill"
project_path = os.path.join(base_folder, project_name + ".aprx")

arcpy.CheckOutExtension("Spatial")

# Create or open project
if not os.path.exists(project_path):
    arcpy.mp.ArcGISProject.create(base_folder, project_name)

aprx = arcpy.mp.ArcGISProject(project_path)

maps = aprx.listMaps()
if maps:
    m = maps[0]
else:
    m = aprx.createMap("Map")

# Create geodatabase
gdb = os.path.join(base_folder, project_name + ".gdb")
if not arcpy.Exists(gdb):
    arcpy.management.CreateFileGDB(base_folder, project_name + ".gdb")

arcpy.env.workspace = gdb

# Import DWG to GDB and get polygon feature class
cad_dataset = os.path.join(gdb, "cad_import")
if not arcpy.Exists(cad_dataset):
    arcpy.conversion.CADToGeodatabase(dwg_path, gdb, "cad_import", "1000", "00:00:00", "0")

polygon_fc = None
# Search in feature dataset first
arcpy.env.workspace = gdb
for ds in (arcpy.ListDatasets("cad_import", "Feature") or []):
    arcpy.env.workspace = os.path.join(gdb, ds)
    fcs = arcpy.ListFeatureClasses(feature_type="Polygon") or []
    if fcs:
        polygon_fc = os.path.join(gdb, ds, fcs[0])
        break

# Fallback: any polygon FC in GDB
if not polygon_fc:
    arcpy.env.workspace = gdb
    fcs = arcpy.ListFeatureClasses(feature_type="Polygon") or []
    if fcs:
        polygon_fc = os.path.join(gdb, fcs[0])

if not polygon_fc:
    raise RuntimeError("No polygon feature class found after importing DWG.")

# Use first polygon as analysis zone
analysis_polygon = os.path.join(gdb, "analysis_polygon")
if not arcpy.Exists(analysis_polygon):
    arcpy.management.FeatureClassToFeatureClass(polygon_fc, gdb, "analysis_polygon")

# Get extent and spatial reference from polygon
desc_poly = arcpy.Describe(analysis_polygon)
poly_sr = desc_poly.spatialReference
arcpy.env.extent = desc_poly.extent
arcpy.env.mask = analysis_polygon
arcpy.env.outputCoordinateSystem = poly_sr

# Helper to import Excel points to FC

def excel_to_points(excel_path, out_name):
    temp_table = os.path.join(gdb, out_name + "_tbl")
    if arcpy.Exists(temp_table):
        arcpy.management.Delete(temp_table)
    arcpy.conversion.ExcelToTable(excel_path, temp_table, "Sheet1")

    fields = [f.name for f in arcpy.ListFields(temp_table)]
    # Expect E, N, Z
    if not ("E" in fields and "N" in fields and "Z" in fields):
        raise RuntimeError("Expected fields E, N, Z not found in {}".format(excel_path))

    sr = poly_sr
    fc = os.path.join(gdb, out_name)
    if arcpy.Exists(fc):
        arcpy.management.Delete(fc)
    arcpy.management.CreateFeatureclass(gdb, out_name, "POINT", spatial_reference=sr)
    arcpy.management.AddField(fc, "Z", "DOUBLE")

    with arcpy.da.SearchCursor(temp_table, ["E", "N", "Z"]) as sc, \
         arcpy.da.InsertCursor(fc, ["SHAPE@XY", "Z"]) as ic:
        for e, n, z in sc:
            if e is None or n is None or z is None:
                continue
            try:
                ex = float(str(e).replace(",", ""))
                ny = float(str(n).replace(",", ""))
                zz = float(str(z).replace(",", ""))
            except:
                continue
            ic.insertRow(((ex, ny), zz))

    return fc

pre_points = excel_to_points(pre_excel, "pre_points")
post_points = excel_to_points(post_excel, "post_points")

# Add to map
for lyr_path in [analysis_polygon, pre_points, post_points]:
    if not any(lyr.name == os.path.basename(lyr_path) for lyr in m.listLayers()):
        m.addDataFromPath(lyr_path)

# Create IDW rasters
arcpy.env.workspace = gdb
pre_idw = os.path.join(gdb, "pre_idw")
post_idw = os.path.join(gdb, "post_idw")

for out_raster, in_points in [(pre_idw, pre_points), (post_idw, post_points)]:
    if arcpy.Exists(out_raster):
        arcpy.management.Delete(out_raster)
    arcpy.sa.Idw(in_points, "Z", cell_size=1).save(out_raster)

# CutFill: PRE (surface1) vs POST (surface2)
cutfill = os.path.join(gdb, "cutfill")
if arcpy.Exists(cutfill):
    arcpy.management.Delete(cutfill)

cutfill_raster = arcpy.sa.CutFill(pre_idw, post_idw)
cutfill_raster.save(cutfill)

# Add rasters to map
for lyr_path in [pre_idw, post_idw, cutfill]:
    if not any(lyr.isRasterLayer and lyr.name == os.path.basename(lyr_path) for lyr in m.listLayers()):
        m.addDataFromPath(lyr_path)

# Read CutFill raster attribute table to get volumes
arcpy.BuildRasterAttributeTable_management(cutfill, "OVERWRITE")

total_cut = 0.0
total_fill = 0.0

# Fields for CutFill: AREA, VOLUME, etc.
fields = [f.name for f in arcpy.ListFields(cutfill)]
area_field = "AREA" if "AREA" in fields else None
vol_field = "VOLUME" if "VOLUME" in fields else None

if not area_field or not vol_field:
    raise RuntimeError("CutFill raster missing AREA or VOLUME fields.")

with arcpy.da.SearchCursor(cutfill, [area_field, vol_field]) as cursor:
    for area, vol in cursor:
        if vol is None or area is None:
            continue
        if vol < 0:
            total_cut += abs(vol)
        elif vol > 0:
            total_fill += vol

# Total analysis area from polygon
poly_area = 0.0
with arcpy.da.SearchCursor(analysis_polygon, ["SHAPE@AREA"]) as cursor:
    for (a,) in cursor:
        if a is None:
            continue
        poly_area += a

# Export results to Excel/CSV
import csv

result_csv = os.path.join(base_folder, "Adibawa_VolumeResult.csv")
with open(result_csv, "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerow(["Metric", "Value", "Unit"])
    writer.writerow(["Analysis Area", poly_area, "square_meters"])
    writer.writerow(["Total Cut Volume", total_cut, "cubic_meters"])
    writer.writerow(["Total Fill Volume", total_fill, "cubic_meters"])

print("RESULT_AREA:", poly_area)
print("RESULT_TOTAL_CUT:", total_cut)
print("RESULT_TOTAL_FILL:", total_fill)
print("RESULT_FILE:", result_csv)

# Save project
aprx.save()

