# Generated by SurvyAI
# This script was dynamically generated based on user request
# Generated: 2026-03-28T13:25:39.084596
# 
# Execute this script in ArcGIS Pro's Python Window if needed:
# exec(open(r'C:\Users\UZOR\PycharmProjects\untitled\venv\SurvyAI\scripts\dynexec_arcgis_59dcadd3_a3.py').read())

import arcpy, os, math
from arcpy.sa import *

arcpy.CheckOutExtension("Spatial")

# Paths
pre_excel = r"C:\Users\USER\Documents\SPDC\ADIBAWA WELL 13\Adibawa Well 13A BORROWPIT-Contractor\ADIBAWA WELL 13 BORROW PIT VOLUME COMPUTATION_074938\csv_adibawa__020416_0411510.xlsx"
post_excel = r"C:\Users\USER\Documents\SPDC\ADIBAWA WELL 13\Adibawa Well 13A BORROWPIT-Contractor\ADIBAWA WELL 13 BORROW PIT VOLUME COMPUTATION_074938\csv_Adi post_031618_062229.xlsx"

dwg_path = r"C:\Users\USER\Documents\SPDC\ADIBAWA WELL 13\Adibawa Well 13A BORROWPIT-Contractor\REVIEW\POST SURVEY FOR ADIBAWA WELL 13 BORROW PIT 13A RESTORATION.dwg"

workspace = os.path.dirname(pre_excel)
project_folder = workspace
project_name = "Adibawa_BorrowPit_Volume"
project_path = os.path.join(project_folder, project_name + ".aprx")

# Create project from template if it does not exist
dest = os.path.join(os.path.abspath(project_folder), str(project_name) + ".aprx")
if not os.path.exists(dest):
    install = arcpy.GetInstallInfo()["InstallDir"]
    for tpl in ("BlankProject.aptx", "Blank.aptx", "Map.aptx"):
        tp = os.path.join(install, "Resources", "ProjectTemplates", tpl)
        if os.path.isfile(tp):
            ap = arcpy.mp.ArcGISProject(tp)
            ap.saveACopy(dest)
            break

aprx = arcpy.mp.ArcGISProject(dest)

# Get map
maps = aprx.listMaps()
if maps:
    m = maps[0]
else:
    m = aprx.createMap("Map")

# Create geodatabase
gdb = os.path.join(project_folder, project_name + ".gdb")
if not arcpy.Exists(gdb):
    arcpy.management.CreateFileGDB(project_folder, project_name + ".gdb")

arcpy.env.workspace = gdb

# Import DWG to GDB and find polygon feature class for boundary
cad_dataset = "cad_import"
arcpy.conversion.CADToGeodatabase(dwg_path, gdb, cad_dataset, 1000)

polygon_fc = None
# Search in feature dataset first
for ds in (arcpy.ListDatasets(cad_dataset, "Feature") or []):
    arcpy.env.workspace = os.path.join(gdb, ds)
    for fc in (arcpy.ListFeatureClasses("*", "Polygon") or []):
        polygon_fc = os.path.join(gdb, ds, fc)
        break
    if polygon_fc:
        break

# Fallback: any polygon FC in GDB
if not polygon_fc:
    arcpy.env.workspace = gdb
    for fc in (arcpy.ListFeatureClasses("*", "Polygon") or []):
        polygon_fc = os.path.join(gdb, fc)
        break

if not polygon_fc:
    raise RuntimeError("No polygon feature class found in DWG import for boundary.")

# Reset workspace
arcpy.env.workspace = gdb

# Import Excel tables
pre_table = os.path.join(gdb, "pre_points_table")
post_table = os.path.join(gdb, "post_points_table")
if not arcpy.Exists(pre_table):
    arcpy.conversion.ExcelToTable(pre_excel, pre_table)
if not arcpy.Exists(post_table):
    arcpy.conversion.ExcelToTable(post_excel, post_table)

# Discover field names for E, N, Z (case-insensitive)
def find_field(table, candidates):
    fields = [f.name for f in arcpy.ListFields(table)]
    lower = {f.lower(): f for f in fields}
    for cand in candidates:
        if cand.lower() in lower:
            return lower[cand.lower()]
    # Try fuzzy contains
    for f in fields:
        for cand in candidates:
            if cand.lower() in f.lower():
                return f
    raise RuntimeError(f"Could not find any of {candidates} in {table} fields {fields}")

pre_E = find_field(pre_table, ["E", "Easting", "X"])
pre_N = find_field(pre_table, ["N", "Northing", "Y"])
pre_Z = find_field(pre_table, ["Z", "Elev", "Height"]) 

post_E = find_field(post_table, ["E", "Easting", "X"])
post_N = find_field(post_table, ["N", "Northing", "Y"])
post_Z = find_field(post_table, ["Z", "Elev", "Height"]) 

# Spatial reference: infer from polygon FC
sr = arcpy.Describe(polygon_fc).spatialReference
if not sr or sr.name == "Unknown":
    sr = arcpy.SpatialReference(26392)  # Minna / Nigeria Mid Belt as reasonable default

# Helper to create point feature class from table

def table_to_points(table, x_field, y_field, z_field, out_name):
    fc = os.path.join(gdb, out_name)
    if arcpy.Exists(fc):
        return fc
    arcpy.management.CreateFeatureclass(gdb, out_name, "POINT", spatial_reference=sr, has_z="ENABLED")
    arcpy.management.AddField(fc, "SrcOID", "LONG")
    arcpy.management.AddField(fc, z_field, "DOUBLE")
    with arcpy.da.SearchCursor(table, ["OID@", x_field, y_field, z_field]) as sc, \
         arcpy.da.InsertCursor(fc, ["SrcOID", "SHAPE@XY", "SHAPE@Z", z_field]) as ic:
        for oid, x_raw, y_raw, z_raw in sc:
            if x_raw in (None, "") or y_raw in (None, "") or z_raw in (None, ""):
                continue
            try:
                x = float(str(x_raw).replace(",", ""))
                y = float(str(y_raw).replace(",", ""))
                z = float(str(z_raw).replace(",", ""))
            except Exception:
                continue
            ic.insertRow((oid, (x, y), z, z))
    return fc

pre_points = table_to_points(pre_table, pre_E, pre_N, pre_Z, "pre_points")
post_points = table_to_points(post_table, post_E, post_N, post_Z, "post_points")

# Set environment from polygon for IDW
desc = arcpy.Describe(polygon_fc)
ext = desc.extent
arcpy.env.extent = arcpy.Extent(ext.XMin-1, ext.YMin-1, ext.XMax+1, ext.YMax+1)
arcpy.env.mask = polygon_fc
arcpy.env.outputCoordinateSystem = desc.spatialReference

# Generate IDW rasters
cell_size = (desc.extent.XMax - desc.extent.XMin) / 200.0
if cell_size <= 0:
    cell_size = 1.0

pre_idw = Idw(pre_points, pre_Z, cell_size)
post_idw = Idw(post_points, post_Z, cell_size)

pre_idw_path = os.path.join(gdb, "pre_idw")
post_idw_path = os.path.join(gdb, "post_idw")
pre_idw.save(pre_idw_path)
post_idw.save(post_idw_path)

# CutFill analysis
cutfill_raster = CutFill(post_idw, pre_idw)
cutfill_path = os.path.join(gdb, "cutfill")
cutfill_raster.save(cutfill_path)

# Use raster properties and cell statistics to estimate total volume
cell_area = abs(cutfill_raster.meanCellHeight * cutfill_raster.meanCellWidth)

# Separate positive (fill) and negative (cut) parts
pos_raster = Con(cutfill_raster > 0, cutfill_raster)
neg_raster = Con(cutfill_raster < 0, cutfill_raster)

fill_vol = float(arcpy.management.GetRasterProperties(pos_raster, "SUM").getOutput(0)) * cell_area if pos_raster else 0.0
cut_vol = float(arcpy.management.GetRasterProperties(neg_raster, "SUM").getOutput(0)) * cell_area if neg_raster else 0.0

# Note: neg_raster sum is negative; volume of cut is absolute value
cut_vol = abs(cut_vol)

net_vol = fill_vol - cut_vol

# Export result to Excel in workspace
import openpyxl
from openpyxl import Workbook

result_xlsx = os.path.join(workspace, "Adibawa_VolumeResult.xlsx")
wb = Workbook()
ws = wb.active
ws.title = "VolumeResult"
ws.append(["Metric", "Volume_m3"])
ws.append(["Fill_Volume", fill_vol])
ws.append(["Cut_Volume", cut_vol])
ws.append(["Net_Volume", net_vol])
wb.save(result_xlsx)

print("RESULT_FILE:", result_xlsx)
print("RESULT_FILL_VOLUME:", fill_vol)
print("RESULT_CUT_VOLUME:", cut_vol)
print("RESULT_NET_VOLUME:", net_vol)

# Add layers to map
for lyr_path in [polygon_fc, pre_points, post_points, pre_idw_path, post_idw_path, cutfill_path]:
    try:
        m.addDataFromPath(lyr_path)
    except Exception:
        pass

aprx.save()
