# Generated by SurvyAI
# This script was dynamically generated based on user request
# Generated: 2026-03-28T13:38:04.521485
# 
# Execute this script in ArcGIS Pro's Python Window if needed:
# exec(open(r'C:\Users\UZOR\PycharmProjects\untitled\venv\SurvyAI\scripts\dynexec_arcgis_d8576b0e_a2.py').read())

import arcpy, os, math, shutil

# INPUT PATHS (original folder)

# ---- SurvyAI auto-patch: retry ArcGISProject() open (propy / saveACopy timing) ----
def _survyai_open_aprx_robust(_p):
    import time as _t
    import os as _os
    _p = _os.path.abspath(_p)
    _last = None
    _cls = getattr(getattr(arcpy, "mp", None), "ArcGISProject", None)
    if _cls is None:
        raise RuntimeError("arcpy.mp.ArcGISProject is not available")
    for _i in range(12):
        try:
            return _cls(_p)
        except OSError as _e:
            _last = _e
            _t.sleep(1.5)
        except Exception as _e:
            _last = _e
            _t.sleep(0.6)
    if _last:
        raise _last
    raise OSError("SurvyAI: failed to open ArcGIS project after retries")
# ---- end open retry ----

pre_xlsx = r"C:\Users\USER\Documents\SPDC\ADIBAWA WELL 13\Adibawa Well 13A BORROWPIT-Contractor\ADIBAWA WELL 13 BORROW PIT VOLUME COMPUTATION_074938\csv_adibawa__020416_0411510.xlsx"
post_xlsx = r"C:\Users\USER\Documents\SPDC\ADIBAWA WELL 13\Adibawa Well 13A BORROWPIT-Contractor\ADIBAWA WELL 13 BORROW PIT VOLUME COMPUTATION_074938\csv_Adi post_031618_062229.xlsx"

dwg_path = r"C:\Users\USER\Documents\SPDC\ADIBAWA WELL 13\Adibawa Well 13A BORROWPIT-Contractor\REVIEW\POST SURVEY FOR ADIBAWA WELL 13 BORROW PIT 13A RESTORATION.dwg"

# Define SurvyAI workspace as same folder as PRE Excel (per instructions)
workspace = os.path.dirname(pre_xlsx)
project_name = "Adibawa_BorrowPit_Volume"
project_folder = workspace
project_path = os.path.join(project_folder, project_name + ".aprx")

arcpy.CheckOutExtension("Spatial")

# Ensure workspace exists
os.makedirs(project_folder, exist_ok=True)

# Create or open ArcGIS Pro project using template pattern
dest = os.path.join(os.path.abspath(project_folder), str(project_name) + ".aprx")
if not os.path.exists(dest):
    install = arcpy.GetInstallInfo()["InstallDir"]
    for tpl in ("BlankProject.aptx", "Blank.aptx", "Map.aptx"):
        tp = os.path.join(install, "Resources", "ProjectTemplates", tpl)
        if os.path.isfile(tp):
            ap = _survyai_open_aprx_robust(tp)
            ap.saveACopy(dest)
            break
aprx = _survyai_open_aprx_robust(dest)

# Get or create a map
maps = aprx.listMaps()
if maps:
    m = maps[0]
else:
    m = aprx.createMap("Map")

# Create a file geodatabase
gdb = os.path.join(project_folder, project_name + ".gdb")
if not arcpy.Exists(gdb):
    arcpy.management.CreateFileGDB(project_folder, project_name)

arcpy.env.workspace = gdb

# Import DWG polygon as feature class via CADToGeodatabase
cad_dataset_name = "cad_import"
if not arcpy.Exists(os.path.join(gdb, cad_dataset_name)):
    arcpy.conversion.CADToGeodatabase(dwg_path, gdb, cad_dataset_name, 1000)

# Discover polygon feature class inside CAD import
polygon_fc = None
arcpy.env.workspace = gdb
for ds in (arcpy.ListDatasets(cad_dataset_name, "Feature") or []):
    arcpy.env.workspace = os.path.join(gdb, ds)
    for fc in (arcpy.ListFeatureClasses("*", "Polygon") or []):
        polygon_fc = os.path.join(gdb, ds, fc)
        break
    if polygon_fc:
        break

# Fallback search for any polygon FC in GDB if above failed
if not polygon_fc:
    arcpy.env.workspace = gdb
    for fc in (arcpy.ListFeatureClasses("*", "Polygon") or []):
        polygon_fc = os.path.join(gdb, fc)
        break

if not polygon_fc:
    raise RuntimeError("No polygon feature class found in DWG import for mask/extent")

# Set environment from polygon
poly_desc = arcpy.Describe(polygon_fc)
poly_sr = poly_desc.spatialReference
arcpy.env.extent = poly_desc.extent
arcpy.env.mask = polygon_fc
arcpy.env.outputCoordinateSystem = poly_sr

# Helper to create points from Excel
def create_points_from_excel(xlsx_path, fc_name):
    excel_table = os.path.join(gdb, fc_name + "_tbl")
    # Always use Sheet1 because that's what exists
    arcpy.conversion.ExcelToTable(xlsx_path, excel_table, "Sheet1")

    # Discover fields
    fields = [f.name for f in arcpy.ListFields(excel_table)]
    # Expect E, N, Z
    if not {"E", "N", "Z"}.issubset(set(fields)):
        raise RuntimeError(f"Expected E,N,Z fields in {xlsx_path}, found: {fields}")

    # Create point feature class
    fc = os.path.join(gdb, fc_name)
    if not arcpy.Exists(fc):
        arcpy.management.CreateFeatureclass(gdb, fc_name, "POINT", spatial_reference=poly_sr)
        arcpy.management.AddField(fc, "Z", "DOUBLE")

    with arcpy.da.SearchCursor(excel_table, ["E", "N", "Z"]) as sc, \
         arcpy.da.InsertCursor(fc, ["SHAPE@XY", "Z"]) as ic:
        count = 0
        for e_raw, n_raw, z_raw in sc:
            try:
                x = float(str(e_raw).replace(",", ""))
                y = float(str(n_raw).replace(",", ""))
                z = float(str(z_raw).replace(",", ""))
            except Exception:
                continue
            ic.insertRow(((x, y), z))
            count += 1

    print(f"RESULT_POINTS_{fc_name.upper()}:", count)
    return fc

pre_points = create_points_from_excel(pre_xlsx, "PRE_points")
post_points = create_points_from_excel(post_xlsx, "POST_points")

# Add points and polygon to map
for lyr_path in (polygon_fc, pre_points, post_points):
    try:
        m.addDataFromPath(lyr_path)
    except Exception:
        pass

# Create IDW rasters for PRE and POST using Z as field
arcpy.CheckOutExtension("Spatial")
from arcpy.sa import Idw

pre_idw = os.path.join(gdb, "PRE_IDW")
post_idw = os.path.join(gdb, "POST_IDW")

pre_idw_raster = Idw(pre_points, "Z", cell_size=poly_desc.extent.width/500.0)
pre_idw_raster.save(pre_idw)

post_idw_raster = Idw(post_points, "Z", cell_size=poly_desc.extent.width/500.0)
post_idw_raster.save(post_idw)

# Add rasters to map
for r in (pre_idw, post_idw):
    try:
        m.addDataFromPath(r)
    except Exception:
        pass

# Run CutFill: PRE as base (surface_raster1), POST as surface2
from arcpy.sa import CutFill
cutfill_raster_path = os.path.join(gdb, "CutFill_PRE_POST")
cutfill_result = CutFill(pre_idw, post_idw)
cutfill_result.save(cutfill_raster_path)

try:
    m.addDataFromPath(cutfill_raster_path)
except Exception:
    pass

# Read CutFill attribute table for total fill volume (positive values)
# Note: CutFill raster has an attribute table with fields: GRIDCODE, FROM, TO, VOLUME, AREA
fill_volume = 0.0
fill_area = 0.0

# Build raster attribute table if needed
try:
    arcpy.management.BuildRasterAttributeTable(cutfill_raster_path, "OVERWRITE")
except Exception:
    pass

fields = [f.name for f in arcpy.ListFields(cutfill_raster_path)]
vol_field = "VOLUME" if "VOLUME" in fields else None
area_field = "AREA" if "AREA" in fields else None

if vol_field:
    with arcpy.da.SearchCursor(cutfill_raster_path, [vol_field, area_field] if area_field else [vol_field]) as cursor:
        for row in cursor:
            vol = float(row[0]) if row[0] is not None else 0.0
            if vol > 0:
                fill_volume += vol
            if area_field and row[1] is not None:
                fill_area += float(row[1])

# Export result to Excel in workspace
import openpyxl
from openpyxl import Workbook

out_xlsx = os.path.join(workspace, "Adibawa_VolumeResult.xlsx")
wb = Workbook()
ws = wb.active
ws.title = "VolumeResult"
ws.append(["Description", "Value", "Units"])
ws.append(["Fill Volume", fill_volume, "cubic meters"])
if fill_area:
    ws.append(["Fill Area", fill_area, "square meters"])
wb.save(out_xlsx)

print("RESULT_FILE:", out_xlsx)
print("RESULT_FILL_VOLUME:", fill_volume)
if fill_area:
    print("RESULT_FILL_AREA:", fill_area)

# Save project
aprx.save()
