# Generated by SurvyAI
# This script was dynamically generated based on user request
# Generated: 2026-03-27T13:34:59.991187
# 
# Execute this script in ArcGIS Pro's Python Window if needed:
# exec(open(r'C:\Users\UZOR\PycharmProjects\untitled\venv\SurvyAI\scripts\dynexec_arcgis_7f33c016_a2.py').read())

import arcpy, os, math

# Input paths
pre_excel = r"C:\Users\USER\Documents\SPDC\ADIBAWA WELL 13\Adibawa Well 13A BORROWPIT-Contractor\ADIBAWA WELL 13 BORROW PIT VOLUME COMPUTATION_074938\csv_adibawa__020416_0411510.xlsx"
post_excel = r"C:\Users\USER\Documents\SPDC\ADIBAWA WELL 13\Adibawa Well 13A BORROWPIT-Contractor\ADIBAWA WELL 13 BORROW PIT VOLUME COMPUTATION_074938\csv_Adi post_031618_062229.xlsx"

# DWG polygon for extent/mask
cad_path = r"C:\Users\USER\Documents\SPDC\ADIBAWA WELL 13\Adibawa Well 13A BORROWPIT-Contractor\REVIEW\POST SURVEY FOR ADIBAWA WELL 13 BORROW PIT 13A RESTORATION.dwg"

# Workspace/project folder
workspace = os.path.dirname(pre_excel)
project_name = "Adibawa_BorrowPit_Volume"
project_folder = workspace
project_path = os.path.join(project_folder, project_name + ".aprx")

arcpy.env.overwriteOutput = True

# Create a new project if it doesn't exist
if not os.path.exists(project_path):
    aprx = arcpy.mp.ArcGISProject("CURRENT")
    # Save a copy of CURRENT project into our desired path if running inside Pro
    try:
        aprx.saveACopy(project_path)
    except Exception as e:
        # If not in Pro, create a default project structure-less by using a blank APRX
        aprx = arcpy.mp.ArcGISProject("CURRENT")
else:
    aprx = arcpy.mp.ArcGISProject(project_path)

m = aprx.listMaps()[0]

# Create a file geodatabase
gdb_path = os.path.join(project_folder, project_name + ".gdb")
if not arcpy.Exists(gdb_path):
    arcpy.management.CreateFileGDB(project_folder, project_name + ".gdb")

arcpy.env.workspace = gdb_path

# Import CAD and get polygon for extent/mask
cad_gdb_name = "cad_import.gdb"
cad_gdb = os.path.join(project_folder, cad_gdb_name)
if not arcpy.Exists(cad_gdb):
    arcpy.conversion.CADToGeodatabase(cad_path, project_folder, "cad_import", 1)

polygon_fc = os.path.join(project_folder, "cad_import.gdb", "cad_import", "Polygon")
if not arcpy.Exists(polygon_fc):
    # Try alternative typical CAD import path
    polygon_fc = os.path.join(project_folder, "cad_import.gdb", "Polygon")

if not arcpy.Exists(polygon_fc):
    raise RuntimeError("Could not find polygon feature class from CAD import")

poly_desc = arcpy.Describe(polygon_fc)
poly_sr = poly_desc.spatialReference
ext = poly_desc.extent

# Set environment based on polygon
arcpy.env.extent = arcpy.Extent(ext.XMin - 1, ext.YMin - 1, ext.XMax + 1, ext.YMax + 1)
arcpy.env.mask = polygon_fc
arcpy.env.outputCoordinateSystem = poly_sr

# Add polygon layer to map
m.addDataFromPath(polygon_fc)

# Function to import Excel as table and create point FC

def excel_to_points(excel_path, out_name):
    temp_table = os.path.join(gdb_path, out_name + "_tbl")
    if arcpy.Exists(temp_table):
        arcpy.management.Delete(temp_table)
    arcpy.conversion.ExcelToTable(excel_path, temp_table)

    # Discover fields
    fields = [f.name for f in arcpy.ListFields(temp_table)]
    # Expect 'E', 'N', 'Z'
    if not all(f in fields for f in ["E", "N", "Z"]):
        raise RuntimeError("Expected fields 'E','N','Z' in {} but found {}".format(excel_path, fields))

    # Create point feature class
    out_fc = os.path.join(gdb_path, out_name + "_pts")
    if arcpy.Exists(out_fc):
        arcpy.management.Delete(out_fc)
    arcpy.management.CreateFeatureclass(gdb_path, out_name + "_pts", "POINT", spatial_reference=poly_sr)
    arcpy.management.AddField(out_fc, "Z", "DOUBLE")

    with arcpy.da.SearchCursor(temp_table, ["E", "N", "Z"]) as sc, \
         arcpy.da.InsertCursor(out_fc, ["SHAPE@XY", "Z"]) as ic:
        for e, n, z in sc:
            if e is None or n is None or z is None:
                continue
            try:
                x = float(str(e).replace(",", ""))
                y = float(str(n).replace(",", ""))
                z_val = float(str(z).replace(",", ""))
            except:
                continue
            ic.insertRow(((x, y), z_val))

    return out_fc

pre_pts = excel_to_points(pre_excel, "pre")
post_pts = excel_to_points(post_excel, "post")

# Add points to map
m.addDataFromPath(pre_pts)
m.addDataFromPath(post_pts)

# Create IDW rasters
arcpy.CheckOutExtension("Spatial")
from arcpy.sa import Idw

cell_size = (ext.XMax - ext.XMin) / 200.0  # reasonable resolution

pre_idw = Idw(pre_pts, "Z", cell_size=cell_size)
post_idw = Idw(post_pts, "Z", cell_size=cell_size)

pre_idw_path = os.path.join(gdb_path, "pre_idw")
post_idw_path = os.path.join(gdb_path, "post_idw")

pre_idw.save(pre_idw_path)
post_idw.save(post_idw_path)

m.addDataFromPath(pre_idw_path)
m.addDataFromPath(post_idw_path)

# CutFill: PRE is the base, POST is the surface
cf = arcpy.sa.CutFill(pre_idw_path, post_idw_path)
cf_path = os.path.join(gdb_path, "cutfill")
cf.save(cf_path)

m.addDataFromPath(cf_path)

# Read CutFill raster attribute table to get AREA and VOLUME
area = 0.0
volume = 0.0
has_table = False
try:
    fields = [f.name for f in arcpy.ListFields(cf_path)]
    if "AREA" in fields and "VOLUME" in fields:
        has_table = True
        with arcpy.da.SearchCursor(cf_path, ["AREA", "VOLUME"]) as cur:
            for a, v in cur:
                if a is None or v is None:
                    continue
                area += float(a)
                volume += float(v)
except Exception as e:
    has_table = False

# If no attribute table, approximate area from polygon and compute average difference
if not has_table:
    # Compute area from polygon
    with arcpy.da.SearchCursor(polygon_fc, ["SHAPE@AREA"]) as cur:
        for (a,) in cur:
            area += a

    # Compute mean difference between rasters within polygon using ZonalStatistics as Table
    zs_table = os.path.join(gdb_path, "zs_cf")
    if arcpy.Exists(zs_table):
        arcpy.management.Delete(zs_table)
    arcpy.sa.ZonalStatisticsAsTable(polygon_fc, "FID", cf_path, zs_table, "DATA", "MEAN")
    mean_diff = 0.0
    with arcpy.da.SearchCursor(zs_table, ["MEAN"]) as cur:
        for (mval,) in cur:
            if mval is None:
                continue
            mean_diff = float(mval)
    volume = mean_diff * area

# Export results to Excel/CSV
out_xlsx = os.path.join(project_folder, "Adibawa_VolumeResult.xlsx")
out_csv = os.path.join(project_folder, "Adibawa_VolumeResult.csv")

# Create a simple table in memory then copy to Excel/CSV
res_table = os.path.join("in_memory", "vol_results")
if arcpy.Exists(res_table):
    arcpy.management.Delete(res_table)

arcpy.management.CreateTable("in_memory", "vol_results")
arcpy.management.AddField(res_table, "AREA_SQM", "DOUBLE")
arcpy.management.AddField(res_table, "VOLUME_CUM", "DOUBLE")

with arcpy.da.InsertCursor(res_table, ["AREA_SQM", "VOLUME_CUM"]) as ic:
    ic.insertRow((area, volume))

# Export to CSV
if arcpy.Exists(out_csv):
    arcpy.management.Delete(out_csv)
arcpy.conversion.TableToTable(res_table, project_folder, "Adibawa_VolumeResult.csv")

# Try Excel export if Excel tools are available
try:
    if arcpy.Exists(out_xlsx):
        arcpy.management.Delete(out_xlsx)
    arcpy.conversion.TableToExcel(res_table, out_xlsx)
    print("RESULT_FILE_XLSX:", out_xlsx)
except Exception as e:
    print("RESULT_TABLE_TO_EXCEL_FAILED:", e)

print("RESULT_FILE_CSV:", out_csv)
print("RESULT_AREA_SQM:", area)
print("RESULT_VOLUME_CUM:", volume)

# Save project
try:
    aprx.save()
except:
    pass
