# Generated by SurvyAI
# This script was dynamically generated based on user request
# Generated: 2026-04-03T12:40:12.402091
# 
# Execute this script in ArcGIS Pro's Python Window if needed:
# exec(open(r'C:\Users\UZOR\PycharmProjects\untitled\venv\SurvyAI\scripts\iseni_pre_post_cutfill_retry2.py').read())

import arcpy, os, csv, sys, traceback
from openpyxl import load_workbook

pre_xlsx = r"C:/Users/USER/Documents/SPDC/ISENI/REPORT ON FRONT OF CAMP SITE AND ISENI WELL 2 AND 4 LOCATION/REVIEW/FRONT CAMP SITE/camp site pre.xlsx"
post_xlsx = r"C:/Users/USER/Documents/SPDC/ISENI/REPORT ON FRONT OF CAMP SITE AND ISENI WELL 2 AND 4 LOCATION/REVIEW/FRONT CAMP SITE/camp site post.xlsx"
boundary_dwg = r"C:/Users/USER/Documents/SPDC/ISENI/REPORT ON FRONT OF CAMP SITE AND ISENI WELL 2 AND 4 LOCATION/REVIEW/FRONT CAMP SITE/FRONT CAMP SITE 2 POST.dwg"
workspace = os.getcwd()
output_csv = os.path.join(workspace, 'Iseni_VolumeResult.csv')
pre_csv = os.path.join(workspace, 'camp_site_pre.csv')
post_csv = os.path.join(workspace, 'camp_site_post.csv')
gdb = os.path.join(workspace, 'Iseni_CutFill_Volume.gdb')
sr = arcpy.SpatialReference(26391)
arcpy.env.overwriteOutput = True


def p(*args):
    print(*args)
    sys.stdout.flush()


def sheet_to_csv_and_headers(xlsx_path, csv_path):
    wb = load_workbook(xlsx_path, data_only=True, read_only=True)
    ws = wb[wb.sheetnames[0]]
    rows = list(ws.iter_rows(values_only=True))
    if not rows:
        raise RuntimeError('Workbook is empty: ' + xlsx_path)

    # detect header row: prefer first row containing at least 3 non-empty string-ish cells
    header_idx = 0
    for i, row in enumerate(rows[:10]):
        vals = [str(v).strip() for v in row if v is not None and str(v).strip() != '']
        if len(vals) >= 3:
            header_idx = i
            break

    raw_header = rows[header_idx]
    headers = []
    used = {}
    for j, v in enumerate(raw_header):
        name = str(v).strip() if v is not None and str(v).strip() != '' else f'Field{j+1}'
        base = name
        k = 1
        while name.lower() in used:
            k += 1
            name = f'{base}_{k}'
        used[name.lower()] = True
        headers.append(name)

    with open(csv_path, 'w', newline='', encoding='utf-8-sig') as f:
        w = csv.writer(f)
        w.writerow(headers)
        for row in rows[header_idx+1:]:
            vals = list(row)
            if len(vals) < len(headers):
                vals += [''] * (len(headers)-len(vals))
            vals = vals[:len(headers)]
            w.writerow(['' if v is None else v for v in vals])
    return headers


def norm(s):
    return str(s).lower().replace('_','').replace(' ','').replace('.','')


def choose_enz(headers, csv_path):
    nh = [(h, norm(h)) for h in headers]
    def pick(keys):
        for h, n in nh:
            if n in keys:
                return h
        for h, n in nh:
            for k in keys:
                if k in n:
                    return h
        return None
    xh = pick({'e','east','easting','x'})
    yh = pick({'n','north','northing','y'})
    zh = pick({'z','elev','elevation','rl','level','height'})

    # fallback by numeric-content inspection
    if not (xh and yh and zh):
        with open(csv_path, 'r', encoding='utf-8-sig', newline='') as f:
            r = csv.DictReader(f)
            samples = []
            for i, row in enumerate(r):
                samples.append(row)
                if i >= 20:
                    break
        numeric_scores = []
        for h in headers:
            ok = 0
            for row in samples:
                try:
                    float(str(row.get(h,'')).replace(',','').strip())
                    ok += 1
                except:
                    pass
            numeric_scores.append((h, ok))
        numeric_scores.sort(key=lambda t: t[1], reverse=True)
        numeric_headers = [h for h, score in numeric_scores if score > 0]
        if len(numeric_headers) >= 3:
            # common survey order E,N,Z among first three numeric columns
            if not xh: xh = numeric_headers[0]
            if not yh: yh = numeric_headers[1]
            if not zh: zh = numeric_headers[2]
    return xh, yh, zh


def csv_to_points(csv_path, out_fc, xh, yh, zh):
    if arcpy.Exists(out_fc):
        arcpy.management.Delete(out_fc)
    folder, name = os.path.split(out_fc)
    arcpy.management.CreateFeatureclass(folder, name, 'POINT', spatial_reference=sr, has_z='ENABLED')
    arcpy.management.AddField(out_fc, 'Z_VAL', 'DOUBLE')
    arcpy.management.AddField(out_fc, 'SRC_ROW', 'LONG')
    count = 0
    with open(csv_path, 'r', encoding='utf-8-sig', newline='') as f:
        r = csv.DictReader(f)
        with arcpy.da.InsertCursor(out_fc, ['Z_VAL', 'SRC_ROW', 'SHAPE@XY', 'SHAPE@Z']) as ic:
            rowno = 1
            for row in r:
                try:
                    x = float(str(row.get(xh,'')).replace(',','').strip())
                    y = float(str(row.get(yh,'')).replace(',','').strip())
                    z = float(str(row.get(zh,'')).replace(',','').strip())
                except:
                    rowno += 1
                    continue
                ic.insertRow((z, rowno, (x, y), z))
                count += 1
                rowno += 1
    return count


def prepare_boundary():
    cad_name = 'cad_import'
    try:
        arcpy.conversion.CADToGeodatabase(boundary_dwg, gdb, cad_name, 1000, sr)
        cad_ds = os.path.join(gdb, cad_name)
        poly = os.path.join(cad_ds, 'Polygon')
        pline = os.path.join(cad_ds, 'Polyline')
        out_fc = os.path.join(gdb, 'boundary_polygon')
        if arcpy.Exists(out_fc): arcpy.management.Delete(out_fc)
        if arcpy.Exists(poly) and int(arcpy.management.GetCount(poly)[0]) > 0:
            arcpy.management.CopyFeatures(poly, out_fc)
        elif arcpy.Exists(pline) and int(arcpy.management.GetCount(pline)[0]) > 0:
            tmp = os.path.join(gdb, 'boundary_lines')
            if arcpy.Exists(tmp): arcpy.management.Delete(tmp)
            arcpy.management.CopyFeatures(pline, tmp)
            arcpy.management.FeatureToPolygon(tmp, out_fc)
        else:
            raise RuntimeError('No Polygon/Polyline from CADToGeodatabase')
    except Exception:
        poly = boundary_dwg + r'\Polygon'
        pline = boundary_dwg + r'\Polyline'
        out_fc = os.path.join(gdb, 'boundary_polygon')
        if arcpy.Exists(out_fc): arcpy.management.Delete(out_fc)
        if arcpy.Exists(poly) and int(arcpy.management.GetCount(poly)[0]) > 0:
            arcpy.management.CopyFeatures(poly, out_fc)
        elif arcpy.Exists(pline) and int(arcpy.management.GetCount(pline)[0]) > 0:
            tmp = os.path.join(gdb, 'boundary_lines')
            if arcpy.Exists(tmp): arcpy.management.Delete(tmp)
            arcpy.management.CopyFeatures(pline, tmp)
            arcpy.management.FeatureToPolygon(tmp, out_fc)
        else:
            raise RuntimeError('Could not derive polygon from DWG')
    oidf = arcpy.Describe(out_fc).OIDFieldName
    max_oid = None
    max_area = -1
    with arcpy.da.SearchCursor(out_fc, [oidf, 'SHAPE@AREA']) as cur:
        for oid, area in cur:
            if area and area > max_area:
                max_oid = oid
                max_area = area
    if max_oid is None:
        raise RuntimeError('No usable polygon boundary geometry')
    lyr = 'bnd_lyr'
    arcpy.management.MakeFeatureLayer(out_fc, lyr)
    arcpy.management.SelectLayerByAttribute(lyr, 'NEW_SELECTION', f"{arcpy.AddFieldDelimiters(out_fc, oidf)} = {max_oid}")
    single = os.path.join(gdb, 'boundary_polygon_single')
    if arcpy.Exists(single): arcpy.management.Delete(single)
    arcpy.management.CopyFeatures(lyr, single)
    return single


def set_env(poly_fc, expand=0.02):
    ext = arcpy.Describe(poly_fc).extent
    dx = max((ext.XMax-ext.XMin)*expand, 1.0)
    dy = max((ext.YMax-ext.YMin)*expand, 1.0)
    arcpy.env.extent = arcpy.Extent(ext.XMin-dx, ext.YMin-dy, ext.XMax+dx, ext.YMax+dy)
    arcpy.env.mask = poly_fc
    arcpy.env.outputCoordinateSystem = sr
    span = max(ext.XMax-ext.XMin, ext.YMax-ext.YMin)
    arcpy.env.cellSize = max(span/200.0, 0.5)


def idw_masked(points_fc, out_raster):
    from arcpy.sa import Idw, ExtractByMask
    tmp = os.path.join(gdb, os.path.basename(out_raster) + '_tmp')
    if arcpy.Exists(tmp): arcpy.management.Delete(tmp)
    if arcpy.Exists(out_raster): arcpy.management.Delete(out_raster)
    Idw(points_fc, 'Z_VAL').save(tmp)
    ExtractByMask(tmp, arcpy.env.mask).save(out_raster)


def do_cutfill(pre_ras, post_ras, out_ras):
    from arcpy.sa import CutFill
    if arcpy.Exists(out_ras): arcpy.management.Delete(out_ras)
    CutFill(pre_ras, post_ras).save(out_ras)


def export_csv(cutfill_raster, csv_path):
    arcpy.management.BuildRasterAttributeTable(cutfill_raster, 'Overwrite')
    tbl = os.path.join(gdb, 'cutfill_table')
    if arcpy.Exists(tbl): arcpy.management.Delete(tbl)
    arcpy.conversion.TableToTable(cutfill_raster, gdb, 'cutfill_table')
    cellx = float(arcpy.management.GetRasterProperties(cutfill_raster, 'CELLSIZEX')[0])
    celly = float(arcpy.management.GetRasterProperties(cutfill_raster, 'CELLSIZEY')[0])
    cell_area = cellx * celly
    total_area = total_net = total_cut = total_fill = 0.0
    rows = []
    with arcpy.da.SearchCursor(tbl, ['VALUE', 'COUNT']) as cur:
        for val, cnt in cur:
            if val is None or cnt in (None, 0):
                continue
            area = float(cnt) * cell_area
            vol = float(val) * float(cnt) * cell_area
            total_area += area
            total_net += vol
            if vol < 0: total_cut += vol
            elif vol > 0: total_fill += vol
            rows.append((val, cnt, area, vol))
    with open(csv_path, 'w', newline='', encoding='utf-8-sig') as f:
        w = csv.writer(f)
        w.writerow(['metric','value'])
        w.writerow(['total_area_sq_m', total_area])
        w.writerow(['net_volume_cu_m', total_net])
        w.writerow(['cut_volume_cu_m', total_cut])
        w.writerow(['fill_volume_cu_m', total_fill])
        w.writerow([])
        w.writerow(['cutfill_value','cell_count','area_sq_m','volume_cu_m'])
        for r in rows:
            w.writerow(r)
    return total_area, total_net, total_cut, total_fill

try:
    p('START_WORKSPACE', workspace)
    if not os.path.exists(pre_xlsx) or not os.path.exists(post_xlsx) or not os.path.exists(boundary_dwg):
        raise RuntimeError('One or more source files do not exist')
    arcpy.CheckOutExtension('Spatial')
    if not arcpy.Exists(gdb):
        arcpy.management.CreateFileGDB(workspace, 'Iseni_CutFill_Volume.gdb')

    pre_headers = sheet_to_csv_and_headers(pre_xlsx, pre_csv)
    post_headers = sheet_to_csv_and_headers(post_xlsx, post_csv)
    p('RESULT_PRE_CSV:', pre_csv)
    p('RESULT_POST_CSV:', post_csv)
    p('DEBUG_PRE_HEADERS:', pre_headers)
    p('DEBUG_POST_HEADERS:', post_headers)

    pre_xh, pre_yh, pre_zh = choose_enz(pre_headers, pre_csv)
    post_xh, post_yh, post_zh = choose_enz(post_headers, post_csv)
    p('RESULT_PRE_FIELDS:', pre_xh, pre_yh, pre_zh)
    p('RESULT_POST_FIELDS:', post_xh, post_yh, post_zh)
    if not (pre_xh and pre_yh and pre_zh and post_xh and post_yh and post_zh):
        raise RuntimeError('Could not resolve usable E/N/Z columns from workbook headers/content')

    pre_points = os.path.join(gdb, 'pre_points')
    post_points = os.path.join(gdb, 'post_points')
    pre_count = csv_to_points(pre_csv, pre_points, pre_xh, pre_yh, pre_zh)
    post_count = csv_to_points(post_csv, post_points, post_xh, post_yh, post_zh)
    p('RESULT_PRE_POINTS_INSERTED:', pre_count)
    p('RESULT_POST_POINTS_INSERTED:', post_count)
    if pre_count <= 0 or post_count <= 0:
        raise RuntimeError('No usable X/Y/Z rows found for PRE or POST after parsing CSV copies')

    boundary = prepare_boundary()
    p('RESULT_BOUNDARY_FC:', boundary)
    set_env(boundary, 0.02)

    pre_idw = os.path.join(gdb, 'pre_idw')
    post_idw = os.path.join(gdb, 'post_idw')
    try:
        idw_masked(pre_points, pre_idw)
        idw_masked(post_points, post_idw)
    except arcpy.ExecuteError:
        em = arcpy.GetMessages(2)
        p('IDW_ERROR_MSG', em)
        if '010092' in em or 'Invalid output extent' in em:
            set_env(boundary, 0.10)
            idw_masked(pre_points, pre_idw)
            idw_masked(post_points, post_idw)
        else:
            raise
    p('RESULT_PRE_IDW:', pre_idw)
    p('RESULT_POST_IDW:', post_idw)

    cutfill = os.path.join(gdb, 'cutfill')
    try:
        do_cutfill(pre_idw, post_idw, cutfill)
    except arcpy.ExecuteError:
        em = arcpy.GetMessages(2)
        p('CUTFILL_ERROR_MSG', em)
        if '010092' in em or 'Invalid output extent' in em:
            set_env(boundary, 0.10)
            do_cutfill(pre_idw, post_idw, cutfill)
        else:
            raise
    p('RESULT_CUTFILL:', cutfill)

    area, net_vol, cut_vol, fill_vol = export_csv(cutfill, output_csv)
    p('RESULT_OUTPUT_CSV:', output_csv)
    p('RESULT_AREA_SQ_M:', area)
    p('RESULT_NET_VOLUME_CU_M:', net_vol)
    p('RESULT_CUT_VOLUME_CU_M:', cut_vol)
    p('RESULT_FILL_VOLUME_CU_M:', fill_vol)

except Exception as e:
    p('ERROR:', str(e))
    p(traceback.format_exc())
    raise
finally:
    try:
        arcpy.CheckInExtension('Spatial')
    except:
        pass
