# Generated by SurvyAI
# This script was dynamically generated based on user request
# Generated: 2026-04-03T12:38:22.023759
# 
# Execute this script in ArcGIS Pro's Python Window if needed:
# exec(open(r'C:\Users\UZOR\PycharmProjects\untitled\venv\SurvyAI\scripts\iseni_pre_post_cutfill.py').read())

import arcpy, os, csv, math, traceback, sys
from openpyxl import load_workbook

# =========================
# User inputs
# =========================
pre_xlsx = r"C:/Users/USER/Documents/SPDC/ISENI/REPORT ON FRONT OF CAMP SITE AND ISENI WELL 2 AND 4 LOCATION/REVIEW/FRONT CAMP SITE/camp site pre.xlsx"
post_xlsx = r"C:/Users/USER/Documents/SPDC/ISENI/REPORT ON FRONT OF CAMP SITE AND ISENI WELL 2 AND 4 LOCATION/REVIEW/FRONT CAMP SITE/camp site post.xlsx"
boundary_dwg = r"C:/Users/USER/Documents/SPDC/ISENI/REPORT ON FRONT OF CAMP SITE AND ISENI WELL 2 AND 4 LOCATION/REVIEW/FRONT CAMP SITE/FRONT CAMP SITE 2 POST.dwg"
workspace = os.getcwd()
output_csv = os.path.join(workspace, "Iseni_VolumeResult.csv")
pre_csv = os.path.join(workspace, "camp_site_pre.csv")
post_csv = os.path.join(workspace, "camp_site_post.csv")
project_name = "Iseni_CutFill_Volume"
project_folder = workspace
project_path = os.path.join(project_folder, project_name + ".aprx")
gdb = os.path.join(project_folder, project_name + ".gdb")

# Nigerian West-Belt Projected system
sr = arcpy.SpatialReference(26391)

arcpy.env.overwriteOutput = True


def log(msg):
    print(msg)
    sys.stdout.flush()


def workbook_to_csv(xlsx_path, csv_path):
    wb = load_workbook(xlsx_path, data_only=True, read_only=True)
    ws = wb[wb.sheetnames[0]]
    with open(csv_path, 'w', newline='', encoding='utf-8-sig') as f:
        writer = csv.writer(f)
        for row in ws.iter_rows(values_only=True):
            writer.writerow(list(row) if row is not None else [])
    return csv_path


def find_fields(table_path):
    fields = [f.name for f in arcpy.ListFields(table_path)]
    lower = {f.lower(): f for f in fields}
    def pick(cands):
        for c in cands:
            for lf, orig in lower.items():
                if lf == c or lf.replace('_','').replace(' ','') == c.replace('_','').replace(' ',''):
                    return orig
        for c in cands:
            for lf, orig in lower.items():
                if c in lf.replace(' ','').replace('_',''):
                    return orig
        return None
    x = pick(['e','east','easting','x'])
    y = pick(['n','north','northing','y'])
    z = pick(['z','rl','elev','elevation','level'])
    return fields, x, y, z


def make_points_from_table(table_path, out_fc, sr):
    fields, x_field, y_field, z_field = find_fields(table_path)
    if not x_field or not y_field or not z_field:
        raise RuntimeError(f"Could not resolve E/N/Z fields in {table_path}. Fields: {fields}")

    folder, name = os.path.split(out_fc)
    if arcpy.Exists(out_fc):
        arcpy.management.Delete(out_fc)
    arcpy.management.CreateFeatureclass(folder, name, 'POINT', spatial_reference=sr, has_z='ENABLED')
    arcpy.management.AddField(out_fc, 'SRC_OID', 'LONG')
    arcpy.management.AddField(out_fc, 'Z_VAL', 'DOUBLE')

    inserted = 0
    with arcpy.da.SearchCursor(table_path, ['OID@', x_field, y_field, z_field]) as sc, \
         arcpy.da.InsertCursor(out_fc, ['SRC_OID', 'Z_VAL', 'SHAPE@']) as ic:
        for oid, x_raw, y_raw, z_raw in sc:
            try:
                x = float(str(x_raw).replace(',', '').strip())
                y = float(str(y_raw).replace(',', '').strip())
                z = float(str(z_raw).replace(',', '').strip())
            except:
                continue
            p = arcpy.Point(x, y, z)
            ic.insertRow((oid, z, arcpy.PointGeometry(p, sr, True)))
            inserted += 1
    return inserted, x_field, y_field, z_field


def pick_boundary_polygon(cad_ds, out_fc):
    poly = os.path.join(cad_ds, 'Polygon')
    pline = os.path.join(cad_ds, 'Polyline')
    created = None
    if arcpy.Exists(poly) and int(arcpy.management.GetCount(poly)[0]) > 0:
        arcpy.management.CopyFeatures(poly, out_fc)
        created = out_fc
    elif arcpy.Exists(pline) and int(arcpy.management.GetCount(pline)[0]) > 0:
        tmp_line = os.path.join(gdb, 'boundary_lines')
        arcpy.management.CopyFeatures(pline, tmp_line)
        arcpy.management.FeatureToPolygon(tmp_line, out_fc)
        created = out_fc
    else:
        raise RuntimeError('No Polygon or Polyline feature class found in DWG')

    # choose largest polygon if multiple
    largest = None
    max_area = -1
    with arcpy.da.SearchCursor(created, ['OID@', 'SHAPE@AREA']) as cur:
        for oid, area in cur:
            if area and area > max_area:
                max_area = area
                largest = oid
    if largest is None:
        raise RuntimeError('Boundary polygon has no usable geometry')
    lyr = 'boundary_lyr'
    arcpy.management.MakeFeatureLayer(created, lyr)
    oid_field = arcpy.Describe(created).OIDFieldName
    arcpy.management.SelectLayerByAttribute(lyr, 'NEW_SELECTION', f"{arcpy.AddFieldDelimiters(created, oid_field)} = {largest}")
    single = os.path.join(gdb, 'boundary_polygon_single')
    if arcpy.Exists(single):
        arcpy.management.Delete(single)
    arcpy.management.CopyFeatures(lyr, single)
    return single


def set_env_from_polygon(poly_fc, expand_factor=0.02):
    desc = arcpy.Describe(poly_fc)
    ext = desc.extent
    dx = max((ext.XMax - ext.XMin) * expand_factor, 1.0)
    dy = max((ext.YMax - ext.YMin) * expand_factor, 1.0)
    new_extent = arcpy.Extent(ext.XMin - dx, ext.YMin - dy, ext.XMax + dx, ext.YMax + dy)
    arcpy.env.extent = new_extent
    arcpy.env.mask = poly_fc
    arcpy.env.outputCoordinateSystem = desc.spatialReference if desc.spatialReference and desc.spatialReference.name not in ['Unknown', ''] else sr
    try:
        arcpy.env.cellSize = max((ext.XMax - ext.XMin), (ext.YMax - ext.YMin)) / 250.0
    except:
        pass
    return new_extent


def run_idw(points_fc, z_field, out_raster):
    if arcpy.Exists(out_raster):
        arcpy.management.Delete(out_raster)
    from arcpy.sa import Idw
    ras = Idw(points_fc, z_field)
    ras.save(out_raster)
    return out_raster


def run_cutfill(pre_ras, post_ras, out_ras):
    if arcpy.Exists(out_ras):
        arcpy.management.Delete(out_ras)
    from arcpy.sa import CutFill
    ras = CutFill(pre_ras, post_ras)
    ras.save(out_ras)
    return out_ras


def export_cutfill_stats(cutfill_raster, csv_path):
    tmp_table = os.path.join(gdb, 'cutfill_table')
    if arcpy.Exists(tmp_table):
        arcpy.management.Delete(tmp_table)
    arcpy.management.BuildRasterAttributeTable(cutfill_raster, 'Overwrite')
    arcpy.conversion.TableToTable(cutfill_raster, gdb, 'cutfill_table')

    fields = [f.name for f in arcpy.ListFields(tmp_table)]
    area_field = next((f for f in fields if f.upper() in ('AREA','COUNT')), None)
    count_field = next((f for f in fields if f.upper() == 'COUNT'), None)
    value_field = next((f for f in fields if f.upper() == 'VALUE'), None)

    cellx = float(arcpy.management.GetRasterProperties(cutfill_raster, 'CELLSIZEX')[0])
    celly = float(arcpy.management.GetRasterProperties(cutfill_raster, 'CELLSIZEY')[0])
    cell_area = cellx * celly

    rows = []
    total_volume = 0.0
    total_cut = 0.0
    total_fill = 0.0
    total_area = 0.0

    use_fields = []
    for fld in [value_field, count_field]:
        if fld:
            use_fields.append(fld)
    if len(use_fields) < 2:
        raise RuntimeError(f'Could not resolve VALUE and COUNT fields from cutfill table fields: {fields}')

    with arcpy.da.SearchCursor(tmp_table, use_fields) as cur:
        for value, count in cur:
            if value is None or count in (None, 0):
                continue
            volume = float(value) * float(count) * cell_area
            area = float(count) * cell_area
            total_volume += volume
            total_area += area
            if volume < 0:
                total_cut += volume
            elif volume > 0:
                total_fill += volume
            rows.append((value, count, area, volume))

    with open(csv_path, 'w', newline='', encoding='utf-8-sig') as f:
        writer = csv.writer(f)
        writer.writerow(['metric', 'value'])
        writer.writerow(['total_area_sq_m', total_area])
        writer.writerow(['net_volume_cu_m', total_volume])
        writer.writerow(['cut_volume_cu_m', total_cut])
        writer.writerow(['fill_volume_cu_m', total_fill])
        writer.writerow([])
        writer.writerow(['cutfill_value', 'cell_count', 'area_sq_m', 'volume_cu_m'])
        writer.writerows(rows)
    return total_area, total_volume, total_cut, total_fill


try:
    arcpy.CheckOutExtension('Spatial')

    # Create project/gdb if needed
    if not os.path.exists(project_folder):
        os.makedirs(project_folder)
    if not arcpy.Exists(gdb):
        arcpy.management.CreateFileGDB(project_folder, os.path.basename(gdb))
    if not os.path.exists(project_path):
        arcpy.mp.CreateProject(project_folder, project_name, 'MAP')

    # 1) Copy xlsx data to csv files in workspace
    workbook_to_csv(pre_xlsx, pre_csv)
    workbook_to_csv(post_xlsx, post_csv)
    print('RESULT_PRE_CSV:', pre_csv)
    print('RESULT_POST_CSV:', post_csv)

    # 2) Import csv tables into gdb
    pre_table = os.path.join(gdb, 'pre_table')
    post_table = os.path.join(gdb, 'post_table')
    if arcpy.Exists(pre_table): arcpy.management.Delete(pre_table)
    if arcpy.Exists(post_table): arcpy.management.Delete(post_table)
    arcpy.conversion.TableToTable(pre_csv, gdb, 'pre_table')
    arcpy.conversion.TableToTable(post_csv, gdb, 'post_table')

    # 3) Create point feature classes with E/N/Z
    pre_points = os.path.join(gdb, 'pre_points')
    post_points = os.path.join(gdb, 'post_points')
    pre_count, pre_x, pre_y, pre_z = make_points_from_table(pre_table, pre_points, sr)
    post_count, post_x, post_y, post_z = make_points_from_table(post_table, post_points, sr)
    print('RESULT_PRE_POINTS_INSERTED:', pre_count)
    print('RESULT_POST_POINTS_INSERTED:', post_count)
    print('RESULT_PRE_FIELDS:', pre_x, pre_y, pre_z)
    print('RESULT_POST_FIELDS:', post_x, post_y, post_z)

    if pre_count <= 0 or post_count <= 0:
        raise RuntimeError('No usable PRE or POST points were inserted from E/N/Z fields.')

    # 4) Import DWG and derive polygon boundary
    cad_name = 'cad_import'
    cad_ds = os.path.join(gdb, cad_name)
    if arcpy.Exists(cad_ds):
        try:
            arcpy.management.Delete(cad_ds)
        except:
            pass
    arcpy.conversion.CADToGeodatabase(boundary_dwg, gdb, cad_name, 1000, sr)

    boundary_fc = os.path.join(gdb, 'boundary_polygon')
    boundary_single = pick_boundary_polygon(cad_ds, boundary_fc)
    print('RESULT_BOUNDARY_FC:', boundary_single)

    # 5) Set env from boundary polygon
    set_env_from_polygon(boundary_single)

    # 6) IDW rasters
    pre_idw = os.path.join(gdb, 'pre_idw')
    post_idw = os.path.join(gdb, 'post_idw')

    try:
        run_idw(pre_points, 'Z_VAL', pre_idw)
        run_idw(post_points, 'Z_VAL', post_idw)
    except arcpy.ExecuteError:
        msg = arcpy.GetMessages(2)
        if '010092' in msg or 'Invalid output extent' in msg:
            set_env_from_polygon(boundary_single, expand_factor=0.10)
            run_idw(pre_points, 'Z_VAL', pre_idw)
            run_idw(post_points, 'Z_VAL', post_idw)
        else:
            raise

    print('RESULT_PRE_IDW:', pre_idw)
    print('RESULT_POST_IDW:', post_idw)

    # 7) CutFill
    cutfill = os.path.join(gdb, 'cutfill')
    try:
        run_cutfill(pre_idw, post_idw, cutfill)
    except arcpy.ExecuteError:
        msg = arcpy.GetMessages(2)
        if '010092' in msg or 'Invalid output extent' in msg:
            set_env_from_polygon(boundary_single, expand_factor=0.10)
            run_cutfill(pre_idw, post_idw, cutfill)
        else:
            raise

    print('RESULT_CUTFILL:', cutfill)

    # 8) Export results CSV
    total_area, net_volume, cut_volume, fill_volume = export_cutfill_stats(cutfill, output_csv)
    print('RESULT_OUTPUT_CSV:', output_csv)
    print('RESULT_AREA_SQ_M:', total_area)
    print('RESULT_NET_VOLUME_CU_M:', net_volume)
    print('RESULT_CUT_VOLUME_CU_M:', cut_volume)
    print('RESULT_FILL_VOLUME_CU_M:', fill_volume)

except Exception as e:
    print('ERROR:', str(e))
    print(traceback.format_exc())
    raise
finally:
    try:
        arcpy.CheckInExtension('Spatial')
    except:
        pass
