# Generated by SurvyAI
# This script was dynamically generated based on user request
# Generated: 2026-04-03T12:35:07.238198
# 
# Execute this script in ArcGIS Pro's Python Window if needed:
# exec(open(r'C:\Users\UZOR\PycharmProjects\untitled\venv\SurvyAI\scripts\iseni_pre_post_idw_cutfill_retry.py').read())

import os, csv, traceback, re, sys
import arcpy
from arcpy.sa import Idw, CutFill

pre_xlsx = r"C:/Users/USER/Documents/SPDC/ISENI/REPORT ON FRONT OF CAMP SITE AND ISENI WELL 2 AND 4 LOCATION/REVIEW/FRONT CAMP SITE/camp site pre.xlsx"
post_xlsx = r"C:/Users/USER/Documents/SPDC/ISENI/REPORT ON FRONT OF CAMP SITE AND ISENI WELL 2 AND 4 LOCATION/REVIEW/FRONT CAMP SITE/camp site post.xlsx"
boundary_dwg = r"C:/Users/USER/Documents/SPDC/ISENI/REPORT ON FRONT OF CAMP SITE AND ISENI WELL 2 AND 4 LOCATION/REVIEW/FRONT CAMP SITE/FRONT CAMP SITE 2 POST.dwg"
workspace = os.getcwd()
project_root = os.path.join(workspace, 'Iseni_Volume_Project')
output_csv = os.path.join(workspace, 'Iseni_VolumeResult.csv')
aprx_path = os.path.join(project_root, 'Iseni_Volume_Project.aprx')
sr = arcpy.SpatialReference(26391)


def msg(s):
    print(s)
    sys.stdout.flush()


def ensure_dir(p):
    os.makedirs(p, exist_ok=True)


def norm(s):
    return re.sub(r'[^a-z0-9]+', '', str(s).strip().lower())


def first_sheet(xlsx):
    try:
        d = arcpy.Describe(xlsx)
        kids = getattr(d, 'children', None)
        if kids:
            return kids[0].name
    except:
        pass
    return None


def find_fields(table):
    fobjs = arcpy.ListFields(table)
    fields = [f.name for f in fobjs]
    fmap = {norm(f): f for f in fields}
    x = fmap.get('e') or fmap.get('easting') or fmap.get('eastings') or fmap.get('east') or fmap.get('x')
    y = fmap.get('n') or fmap.get('northing') or fmap.get('northings') or fmap.get('north') or fmap.get('y')
    z = fmap.get('z') or fmap.get('elevation') or fmap.get('elev') or fmap.get('level') or fmap.get('rl') or fmap.get('height')
    if not x:
        for f in fields:
            lf = f.lower()
            if 'east' in lf or lf == 'e' or lf == 'x':
                x = f; break
    if not y:
        for f in fields:
            lf = f.lower()
            if 'north' in lf or lf == 'n' or lf == 'y':
                y = f; break
    if not z:
        for f in fields:
            lf = f.lower()
            if lf == 'z' or 'elev' in lf or 'level' in lf or lf == 'rl' or 'height' in lf:
                z = f; break
    return fields, x, y, z


def export_table_to_csv(table, csv_path):
    fields = [f.name for f in arcpy.ListFields(table) if f.type not in ('OID', 'Geometry', 'Blob', 'Raster')]
    with open(csv_path, 'w', newline='', encoding='utf-8') as f:
        w = csv.writer(f)
        w.writerow(fields)
        with arcpy.da.SearchCursor(table, fields) as cur:
            for row in cur:
                w.writerow(list(row))


def create_points(table, out_fc):
    fields, x_field, y_field, z_field = find_fields(table)
    if not (x_field and y_field and z_field):
        raise RuntimeError('Missing usable E/N/Z fields in %s. Fields=%s' % (table, fields))
    if arcpy.Exists(out_fc):
        arcpy.management.Delete(out_fc)
    arcpy.management.CreateFeatureclass(os.path.dirname(out_fc), os.path.basename(out_fc), 'POINT', spatial_reference=sr)
    arcpy.management.AddField(out_fc, 'ZVAL', 'DOUBLE')
    inserted = 0
    with arcpy.da.SearchCursor(table, [x_field, y_field, z_field]) as sc:
        with arcpy.da.InsertCursor(out_fc, ['ZVAL', 'SHAPE@XY']) as ic:
            for xv, yv, zv in sc:
                try:
                    x = float(str(xv).replace(',', '').strip())
                    y = float(str(yv).replace(',', '').strip())
                    z = float(str(zv).replace(',', '').strip())
                except:
                    continue
                ic.insertRow((z, (x, y)))
                inserted += 1
    if inserted == 0:
        raise RuntimeError('No usable numeric E/N/Z rows found in %s' % table)
    return inserted


def largest_boundary_from_dwg(cad_gdb, out_fc):
    dataset_name = 'cadimport'
    try:
        arcpy.conversion.CADToGeodatabase(boundary_dwg, cad_gdb, dataset_name, 1000, sr)
    except:
        # try deleting existing and reimporting
        ds = os.path.join(cad_gdb, dataset_name)
        if arcpy.Exists(ds):
            arcpy.management.Delete(ds)
        arcpy.conversion.CADToGeodatabase(boundary_dwg, cad_gdb, dataset_name, 1000, sr)
    poly_fc = os.path.join(cad_gdb, dataset_name, 'Polygon')
    pline_fc = os.path.join(cad_gdb, dataset_name, 'Polyline')
    temp_fc = None
    if arcpy.Exists(poly_fc) and int(arcpy.management.GetCount(poly_fc)[0]) > 0:
        temp_fc = poly_fc
    elif arcpy.Exists(pline_fc) and int(arcpy.management.GetCount(pline_fc)[0]) > 0:
        temp_poly = os.path.join(os.path.dirname(out_fc), 'boundary_from_polyline')
        if arcpy.Exists(temp_poly): arcpy.management.Delete(temp_poly)
        arcpy.management.FeatureToPolygon(pline_fc, temp_poly)
        temp_fc = temp_poly
    else:
        raise RuntimeError('No usable polygon/polyline boundary found in DWG')
    if arcpy.Exists(out_fc): arcpy.management.Delete(out_fc)
    arcpy.management.CopyFeatures(temp_fc, out_fc)
    oidf = arcpy.Describe(out_fc).OIDFieldName
    max_oid = None
    max_area = -1
    with arcpy.da.SearchCursor(out_fc, [oidf, 'SHAPE@AREA']) as cur:
        for oid, a in cur:
            if a and a > max_area:
                max_area = a; max_oid = oid
    lyr = 'bnd_lyr'
    arcpy.management.MakeFeatureLayer(out_fc, lyr, '{0} = {1}'.format(arcpy.AddFieldDelimiters(out_fc, oidf), max_oid))
    single = out_fc + '_single'
    if arcpy.Exists(single): arcpy.management.Delete(single)
    arcpy.management.CopyFeatures(lyr, single)
    arcpy.management.Delete(out_fc)
    arcpy.management.Rename(single, out_fc)


def set_env(boundary_fc, expand=0.0):
    ext = arcpy.Describe(boundary_fc).extent
    if expand:
        ext = arcpy.Extent(ext.XMin-expand, ext.YMin-expand, ext.XMax+expand, ext.YMax+expand)
    arcpy.env.extent = ext
    arcpy.env.mask = boundary_fc
    arcpy.env.outputCoordinateSystem = sr
    cell = max((ext.width + ext.height) / 500.0, 1.0)
    arcpy.env.cellSize = cell
    return cell


def save_idw(points_fc, out_raster, boundary_fc):
    if arcpy.Exists(out_raster): arcpy.management.Delete(out_raster)
    try:
        set_env(boundary_fc, 0.0)
        ras = Idw(points_fc, 'ZVAL')
        ras.save(out_raster)
    except arcpy.ExecuteError:
        m = arcpy.GetMessages(2)
        if '010092' in m or 'Invalid output extent' in m:
            set_env(boundary_fc, 1.0)
            ras = Idw(points_fc, 'ZVAL')
            ras.save(out_raster)
        else:
            raise


try:
    msg('Starting workflow')
    arcpy.CheckOutExtension('Spatial')
    ensure_dir(project_root)
    gdb = os.path.join(project_root, 'Iseni_Volume.gdb')
    cad_gdb = os.path.join(project_root, 'cad.gdb')
    if not arcpy.Exists(gdb):
        arcpy.management.CreateFileGDB(project_root, 'Iseni_Volume.gdb')
    if not arcpy.Exists(cad_gdb):
        arcpy.management.CreateFileGDB(project_root, 'cad.gdb')

    # Create project via ArcGISProject import template fallback-free approach
    if not os.path.exists(aprx_path):
        arcpy.management.CreateProject(project_root, 'Iseni_Volume_Project', 'MAP')
    msg('Project ready: ' + aprx_path)

    pre_sheet = first_sheet(pre_xlsx)
    post_sheet = first_sheet(post_xlsx)
    pre_tbl = os.path.join(gdb, 'pre_tbl')
    post_tbl = os.path.join(gdb, 'post_tbl')
    if arcpy.Exists(pre_tbl): arcpy.management.Delete(pre_tbl)
    if arcpy.Exists(post_tbl): arcpy.management.Delete(post_tbl)
    if pre_sheet:
        arcpy.conversion.ExcelToTable(pre_xlsx, pre_tbl, pre_sheet)
    else:
        arcpy.conversion.ExcelToTable(pre_xlsx, pre_tbl)
    if post_sheet:
        arcpy.conversion.ExcelToTable(post_xlsx, post_tbl, post_sheet)
    else:
        arcpy.conversion.ExcelToTable(post_xlsx, post_tbl)
    msg('Excel imported to tables')

    pre_csv = os.path.join(workspace, 'camp_site_pre.csv')
    post_csv = os.path.join(workspace, 'camp_site_post.csv')
    export_table_to_csv(pre_tbl, pre_csv)
    export_table_to_csv(post_tbl, post_csv)
    msg('CSV copies created')

    pre_pts = os.path.join(gdb, 'PRE_points')
    post_pts = os.path.join(gdb, 'POST_points')
    pre_count = create_points(pre_tbl, pre_pts)
    post_count = create_points(post_tbl, post_pts)
    msg('Point features created')

    boundary_fc = os.path.join(gdb, 'boundary_polygon')
    largest_boundary_from_dwg(cad_gdb, boundary_fc)
    msg('Boundary polygon created')

    pre_idw = os.path.join(gdb, 'PRE_IDW')
    post_idw = os.path.join(gdb, 'POST_IDW')
    save_idw(pre_pts, pre_idw, boundary_fc)
    save_idw(post_pts, post_idw, boundary_fc)
    msg('IDW rasters created')

    cutfill = os.path.join(gdb, 'CutFill')
    if arcpy.Exists(cutfill): arcpy.management.Delete(cutfill)
    try:
        set_env(boundary_fc, 0.0)
        CutFill(pre_idw, post_idw).save(cutfill)
    except arcpy.ExecuteError:
        m = arcpy.GetMessages(2)
        if '010092' in m or 'Invalid output extent' in m:
            set_env(boundary_fc, 1.0)
            CutFill(pre_idw, post_idw).save(cutfill)
        else:
            raise
    msg('CutFill raster created')

    # Summarize using Raster attribute table (VALUE, COUNT)
    desc = arcpy.Describe(cutfill)
    cell_area = float(desc.meanCellWidth) * float(desc.meanCellHeight)
    total_volume = 0.0
    cut_volume = 0.0
    fill_volume = 0.0
    total_area = 0.0
    with arcpy.da.SearchCursor(cutfill, ['VALUE', 'COUNT']) as cur:
        for val, cnt in cur:
            if val is None or cnt is None:
                continue
            vol = float(val) * float(cnt) * cell_area
            total_volume += vol
            total_area += float(cnt) * cell_area
            if vol < 0:
                cut_volume += vol
            else:
                fill_volume += vol

    with open(output_csv, 'w', newline='', encoding='utf-8') as f:
        w = csv.writer(f)
        w.writerow(['Metric','Value','Units'])
        w.writerow(['Pre_Point_Count', pre_count, 'points'])
        w.writerow(['Post_Point_Count', post_count, 'points'])
        w.writerow(['Analysis_Area', total_area, 'square_meters'])
        w.writerow(['Cut_Volume', cut_volume, 'cubic_meters'])
        w.writerow(['Fill_Volume', fill_volume, 'cubic_meters'])
        w.writerow(['Net_Volume_Post_minus_Pre', total_volume, 'cubic_meters'])
        w.writerow(['Coordinate_System', sr.name, ''])
        w.writerow(['Pre_CSV_Copy', pre_csv, ''])
        w.writerow(['Post_CSV_Copy', post_csv, ''])

    try:
        aprx = arcpy.mp.ArcGISProject(aprx_path)
        m = aprx.listMaps()[0]
        for ds in [boundary_fc, pre_pts, post_pts, pre_idw, post_idw, cutfill]:
            try:
                m.addDataFromPath(ds)
            except:
                pass
        aprx.save()
    except:
        pass

    print('RESULT_PRE_POINT_COUNT:', pre_count)
    print('RESULT_POST_POINT_COUNT:', post_count)
    print('RESULT_ANALYSIS_AREA_SQM:', total_area)
    print('RESULT_CUT_VOLUME_CUM:', cut_volume)
    print('RESULT_FILL_VOLUME_CUM:', fill_volume)
    print('RESULT_NET_VOLUME_CUM:', total_volume)
    print('RESULT_OUTPUT_CSV:', output_csv)
    print('RESULT_PRE_CSV_COPY:', pre_csv)
    print('RESULT_POST_CSV_COPY:', post_csv)
    print('RESULT_PROJECT_PATH:', aprx_path)
    print('RESULT_CRS:', sr.name)

except Exception as e:
    print('ERROR:', str(e))
    try:
        print(arcpy.GetMessages())
    except:
        pass
    print(traceback.format_exc())
    raise
finally:
    try:
        arcpy.CheckInExtension('Spatial')
    except:
        pass

