# Generated by SurvyAI
# This script was dynamically generated based on user request
# Generated: 2026-04-03T12:41:05.540387
# 
# Execute this script in ArcGIS Pro's Python Window if needed:
# exec(open(r'C:\Users\UZOR\PycharmProjects\untitled\venv\SurvyAI\scripts\iseni_pre_post_cutfill_retry3.py').read())

import arcpy, os, csv, sys, traceback
from openpyxl import load_workbook

pre_xlsx = r"C:/Users/USER/Documents/SPDC/ISENI/REPORT ON FRONT OF CAMP SITE AND ISENI WELL 2 AND 4 LOCATION/REVIEW/FRONT CAMP SITE/camp site pre.xlsx"
post_xlsx = r"C:/Users/USER/Documents/SPDC/ISENI/REPORT ON FRONT OF CAMP SITE AND ISENI WELL 2 AND 4 LOCATION/REVIEW/FRONT CAMP SITE/camp site post.xlsx"
boundary_dwg = r"C:/Users/USER/Documents/SPDC/ISENI/REPORT ON FRONT OF CAMP SITE AND ISENI WELL 2 AND 4 LOCATION/REVIEW/FRONT CAMP SITE/FRONT CAMP SITE 2 POST.dwg"
workspace = os.getcwd()
output_csv = os.path.join(workspace, 'Iseni_VolumeResult.csv')
pre_csv = os.path.join(workspace, 'camp_site_pre.csv')
post_csv = os.path.join(workspace, 'camp_site_post.csv')
gdb = os.path.join(workspace, 'Iseni_CutFill_Volume.gdb')
sr = arcpy.SpatialReference(26391)
arcpy.env.overwriteOutput = True


def p(*args):
    print(*args)
    sys.stdout.flush()


def extract_data_and_write_csv(xlsx_path, csv_path):
    wb = load_workbook(xlsx_path, data_only=True, read_only=True)
    ws = wb[wb.sheetnames[0]]
    rows_out = []
    for row in ws.iter_rows(values_only=True):
        vals = []
        for v in row:
            if v is None:
                vals.append('')
            else:
                vals.append(str(v).strip())
        nonempty = [v for v in vals if v != '']
        if len(nonempty) < 4:
            continue
        # collect numeric positions
        nums = []
        for i, v in enumerate(vals):
            try:
                nums.append((i, float(v.replace(',',''))))
            except:
                pass
        if len(nums) < 4:
            continue
        # assume first 4 numeric values are ptno/e/n/z in some order; identify e/n by magnitude, z by smallest magnitude
        first4 = nums[:4]
        num_vals = [n for _, n in first4]
        sorted_vals = sorted(first4, key=lambda t: t[1])
        z_idx, z_val = sorted_vals[0]
        rem = [item for item in first4 if item[0] != z_idx]
        rem_sorted = sorted(rem, key=lambda t: t[1], reverse=True)
        # typical Nigerian West Belt: E around 300k-800k, N around 0-2xxk here. Larger of the two horizontal values likely Easting.
        e_idx, e_val = rem_sorted[0]
        n_idx, n_val = rem_sorted[1]
        rows_out.append((e_val, n_val, z_val, vals))

    if not rows_out:
        raise RuntimeError('No usable numeric rows found in workbook: ' + xlsx_path)

    with open(csv_path, 'w', newline='', encoding='utf-8-sig') as f:
        w = csv.writer(f)
        w.writerow(['E','N','Z'])
        for e, n, z, _ in rows_out:
            w.writerow([e, n, z])
    return len(rows_out)


def csv_to_points(csv_path, out_fc):
    if arcpy.Exists(out_fc): arcpy.management.Delete(out_fc)
    folder, name = os.path.split(out_fc)
    arcpy.management.CreateFeatureclass(folder, name, 'POINT', spatial_reference=sr, has_z='ENABLED')
    arcpy.management.AddField(out_fc, 'Z_VAL', 'DOUBLE')
    count = 0
    with open(csv_path, 'r', encoding='utf-8-sig', newline='') as f:
        r = csv.DictReader(f)
        with arcpy.da.InsertCursor(out_fc, ['Z_VAL', 'SHAPE@XY', 'SHAPE@Z']) as ic:
            for row in r:
                try:
                    e = float(row['E'])
                    n = float(row['N'])
                    z = float(row['Z'])
                except:
                    continue
                ic.insertRow((z, (e, n), z))
                count += 1
    return count


def prepare_boundary():
    cad_name = 'cad_import'
    try:
        arcpy.conversion.CADToGeodatabase(boundary_dwg, gdb, cad_name, 1000, sr)
        cad_ds = os.path.join(gdb, cad_name)
        poly = os.path.join(cad_ds, 'Polygon')
        pline = os.path.join(cad_ds, 'Polyline')
        out_fc = os.path.join(gdb, 'boundary_polygon')
        if arcpy.Exists(out_fc): arcpy.management.Delete(out_fc)
        if arcpy.Exists(poly) and int(arcpy.management.GetCount(poly)[0]) > 0:
            arcpy.management.CopyFeatures(poly, out_fc)
        elif arcpy.Exists(pline) and int(arcpy.management.GetCount(pline)[0]) > 0:
            tmp = os.path.join(gdb, 'boundary_lines')
            if arcpy.Exists(tmp): arcpy.management.Delete(tmp)
            arcpy.management.CopyFeatures(pline, tmp)
            arcpy.management.FeatureToPolygon(tmp, out_fc)
        else:
            raise RuntimeError('No polygon/polyline available from DWG')
    except Exception:
        poly = boundary_dwg + r'\Polygon'
        pline = boundary_dwg + r'\Polyline'
        out_fc = os.path.join(gdb, 'boundary_polygon')
        if arcpy.Exists(out_fc): arcpy.management.Delete(out_fc)
        if arcpy.Exists(poly) and int(arcpy.management.GetCount(poly)[0]) > 0:
            arcpy.management.CopyFeatures(poly, out_fc)
        elif arcpy.Exists(pline) and int(arcpy.management.GetCount(pline)[0]) > 0:
            tmp = os.path.join(gdb, 'boundary_lines')
            if arcpy.Exists(tmp): arcpy.management.Delete(tmp)
            arcpy.management.CopyFeatures(pline, tmp)
            arcpy.management.FeatureToPolygon(tmp, out_fc)
        else:
            raise RuntimeError('Could not derive polygon from DWG')
    oidf = arcpy.Describe(out_fc).OIDFieldName
    best_oid = None
    best_area = -1
    with arcpy.da.SearchCursor(out_fc, [oidf, 'SHAPE@AREA']) as cur:
        for oid, area in cur:
            if area and area > best_area:
                best_oid = oid
                best_area = area
    if best_oid is None:
        raise RuntimeError('Boundary polygon not usable')
    lyr = 'bnd_lyr'
    arcpy.management.MakeFeatureLayer(out_fc, lyr)
    arcpy.management.SelectLayerByAttribute(lyr, 'NEW_SELECTION', f"{arcpy.AddFieldDelimiters(out_fc, oidf)} = {best_oid}")
    single = os.path.join(gdb, 'boundary_polygon_single')
    if arcpy.Exists(single): arcpy.management.Delete(single)
    arcpy.management.CopyFeatures(lyr, single)
    return single


def set_env(poly_fc, expand=0.02):
    ext = arcpy.Describe(poly_fc).extent
    dx = max((ext.XMax-ext.XMin)*expand, 1.0)
    dy = max((ext.YMax-ext.YMin)*expand, 1.0)
    arcpy.env.extent = arcpy.Extent(ext.XMin-dx, ext.YMin-dy, ext.XMax+dx, ext.YMax+dy)
    arcpy.env.mask = poly_fc
    arcpy.env.outputCoordinateSystem = sr
    span = max(ext.XMax-ext.XMin, ext.YMax-ext.YMin)
    arcpy.env.cellSize = max(span/200.0, 0.5)


def make_idw(points_fc, out_raster):
    from arcpy.sa import Idw, ExtractByMask
    tmp = os.path.join(gdb, os.path.basename(out_raster) + '_tmp')
    if arcpy.Exists(tmp): arcpy.management.Delete(tmp)
    if arcpy.Exists(out_raster): arcpy.management.Delete(out_raster)
    Idw(points_fc, 'Z_VAL').save(tmp)
    ExtractByMask(tmp, arcpy.env.mask).save(out_raster)


def make_cutfill(pre_ras, post_ras, out_ras):
    from arcpy.sa import CutFill
    if arcpy.Exists(out_ras): arcpy.management.Delete(out_ras)
    CutFill(pre_ras, post_ras).save(out_ras)


def export_csv(cutfill_raster, csv_path):
    arcpy.management.BuildRasterAttributeTable(cutfill_raster, 'Overwrite')
    tbl = os.path.join(gdb, 'cutfill_table')
    if arcpy.Exists(tbl): arcpy.management.Delete(tbl)
    arcpy.conversion.TableToTable(cutfill_raster, gdb, 'cutfill_table')
    cellx = float(arcpy.management.GetRasterProperties(cutfill_raster, 'CELLSIZEX')[0])
    celly = float(arcpy.management.GetRasterProperties(cutfill_raster, 'CELLSIZEY')[0])
    cell_area = cellx * celly
    total_area = total_net = total_cut = total_fill = 0.0
    detail = []
    with arcpy.da.SearchCursor(tbl, ['VALUE', 'COUNT']) as cur:
        for val, cnt in cur:
            if val is None or cnt in (None, 0):
                continue
            area = float(cnt) * cell_area
            vol = float(val) * float(cnt) * cell_area
            total_area += area
            total_net += vol
            if vol < 0: total_cut += vol
            elif vol > 0: total_fill += vol
            detail.append((val, cnt, area, vol))
    with open(csv_path, 'w', newline='', encoding='utf-8-sig') as f:
        w = csv.writer(f)
        w.writerow(['metric','value'])
        w.writerow(['total_area_sq_m', total_area])
        w.writerow(['net_volume_cu_m', total_net])
        w.writerow(['cut_volume_cu_m', total_cut])
        w.writerow(['fill_volume_cu_m', total_fill])
        w.writerow([])
        w.writerow(['cutfill_value','cell_count','area_sq_m','volume_cu_m'])
        for r in detail:
            w.writerow(r)
    return total_area, total_net, total_cut, total_fill

try:
    p('START_WORKSPACE', workspace)
    if not os.path.exists(pre_xlsx): raise RuntimeError('PRE file missing')
    if not os.path.exists(post_xlsx): raise RuntimeError('POST file missing')
    if not os.path.exists(boundary_dwg): raise RuntimeError('DWG file missing')

    arcpy.CheckOutExtension('Spatial')
    if not arcpy.Exists(gdb):
        arcpy.management.CreateFileGDB(workspace, 'Iseni_CutFill_Volume.gdb')

    pre_rows = extract_data_and_write_csv(pre_xlsx, pre_csv)
    post_rows = extract_data_and_write_csv(post_xlsx, post_csv)
    p('RESULT_PRE_CSV:', pre_csv)
    p('RESULT_POST_CSV:', post_csv)
    p('RESULT_PRE_ROWS_PARSED:', pre_rows)
    p('RESULT_POST_ROWS_PARSED:', post_rows)

    pre_points = os.path.join(gdb, 'pre_points')
    post_points = os.path.join(gdb, 'post_points')
    pre_inserted = csv_to_points(pre_csv, pre_points)
    post_inserted = csv_to_points(post_csv, post_points)
    p('RESULT_PRE_POINTS_INSERTED:', pre_inserted)
    p('RESULT_POST_POINTS_INSERTED:', post_inserted)
    if pre_inserted <= 0 or post_inserted <= 0:
        raise RuntimeError('No usable X/Y/Z rows found after parsing workbook data')

    boundary = prepare_boundary()
    p('RESULT_BOUNDARY_FC:', boundary)
    set_env(boundary, 0.02)

    pre_idw = os.path.join(gdb, 'pre_idw')
    post_idw = os.path.join(gdb, 'post_idw')
    try:
        make_idw(pre_points, pre_idw)
        make_idw(post_points, post_idw)
    except arcpy.ExecuteError:
        em = arcpy.GetMessages(2)
        p('IDW_ERROR_MSG', em)
        if '010092' in em or 'Invalid output extent' in em:
            set_env(boundary, 0.10)
            make_idw(pre_points, pre_idw)
            make_idw(post_points, post_idw)
        else:
            raise
    p('RESULT_PRE_IDW:', pre_idw)
    p('RESULT_POST_IDW:', post_idw)

    cutfill = os.path.join(gdb, 'cutfill')
    try:
        make_cutfill(pre_idw, post_idw, cutfill)
    except arcpy.ExecuteError:
        em = arcpy.GetMessages(2)
        p('CUTFILL_ERROR_MSG', em)
        if '010092' in em or 'Invalid output extent' in em:
            set_env(boundary, 0.10)
            make_cutfill(pre_idw, post_idw, cutfill)
        else:
            raise
    p('RESULT_CUTFILL:', cutfill)

    area, netv, cutv, fillv = export_csv(cutfill, output_csv)
    p('RESULT_OUTPUT_CSV:', output_csv)
    p('RESULT_AREA_SQ_M:', area)
    p('RESULT_NET_VOLUME_CU_M:', netv)
    p('RESULT_CUT_VOLUME_CU_M:', cutv)
    p('RESULT_FILL_VOLUME_CU_M:', fillv)

except Exception as e:
    p('ERROR:', str(e))
    p(traceback.format_exc())
    raise
finally:
    try:
        arcpy.CheckInExtension('Spatial')
    except:
        pass
