# Generated by SurvyAI
# This script was dynamically generated based on user request
# Generated: 2026-04-03T12:34:15.865368
# 
# Execute this script in ArcGIS Pro's Python Window if needed:
# exec(open(r'C:\Users\UZOR\PycharmProjects\untitled\venv\SurvyAI\scripts\iseni_pre_post_idw_cutfill.py').read())

import arcpy, os, csv, shutil, traceback, re, math

# =========================
# User inputs
# =========================
pre_xlsx = r"C:/Users/USER/Documents/SPDC/ISENI/REPORT ON FRONT OF CAMP SITE AND ISENI WELL 2 AND 4 LOCATION/REVIEW/FRONT CAMP SITE/camp site pre.xlsx"
post_xlsx = r"C:/Users/USER/Documents/SPDC/ISENI/REPORT ON FRONT OF CAMP SITE AND ISENI WELL 2 AND 4 LOCATION/REVIEW/FRONT CAMP SITE/camp site post.xlsx"
boundary_dwg = r"C:/Users/USER/Documents/SPDC/ISENI/REPORT ON FRONT OF CAMP SITE AND ISENI WELL 2 AND 4 LOCATION/REVIEW/FRONT CAMP SITE/FRONT CAMP SITE 2 POST.dwg"
workspace = os.getcwd()
output_csv = os.path.join(workspace, 'Iseni_VolumeResult.csv')
project_root = os.path.join(workspace, 'Iseni_Volume_Project')
project_name = 'Iseni_Volume_Project'

# Nigerian West-Belt Projected system (Minna / Nigeria West Belt)
sr = arcpy.SpatialReference(26391)

# =========================
# Helpers
# =========================
def ensure_dir(p):
    os.makedirs(p, exist_ok=True)

def norm(s):
    return re.sub(r'[^a-z0-9]+', '', str(s).strip().lower())

def find_fields(table):
    fields = [f.name for f in arcpy.ListFields(table)]
    fmap = {norm(f): f for f in fields}
    x = None; y = None; z = None
    # likely variants for survey E/N/Z
    x_candidates = ['e','east','easting','x','coorde','eastings']
    y_candidates = ['n','north','northing','y','coordn','northings']
    z_candidates = ['z','rl','elev','elevation','level','height','reducedlevel']
    for c in x_candidates:
        if c in fmap:
            x = fmap[c]; break
    for c in y_candidates:
        if c in fmap:
            y = fmap[c]; break
    for c in z_candidates:
        if c in fmap:
            z = fmap[c]; break
    # fallback fuzzy contains
    if not x:
        for f in fields:
            lf = f.lower()
            if 'east' in lf or lf in ['e','x']:
                x = f; break
    if not y:
        for f in fields:
            lf = f.lower()
            if 'north' in lf or lf in ['n','y']:
                y = f; break
    if not z:
        for f in fields:
            lf = f.lower()
            if lf == 'z' or 'elev' in lf or 'level' in lf or 'height' in lf or lf == 'rl':
                z = f; break
    return fields, x, y, z

def excel_sheet_name(xlsx_path):
    # ExcelToTable accepts sheet as positional argument; discover by workbook parse via Describe when possible.
    # Use first sheet by converting workbook to table view path via ExcelToTable with no sheet not possible, so inspect workbook through arcpy Excel table names.
    try:
        children = arcpy.Describe(xlsx_path).children
        if children:
            return children[0].name
    except:
        pass
    return None

def excel_to_csv(xlsx_path, csv_path, table_name):
    temp_gdb = os.path.join(project_root, 'scratch.gdb')
    if not arcpy.Exists(temp_gdb):
        arcpy.management.CreateFileGDB(project_root, 'scratch.gdb')
    out_table = os.path.join(temp_gdb, os.path.splitext(os.path.basename(csv_path))[0] + '_tbl')
    if arcpy.Exists(out_table):
        arcpy.management.Delete(out_table)
    if table_name:
        arcpy.conversion.ExcelToTable(xlsx_path, out_table, table_name)
    else:
        arcpy.conversion.ExcelToTable(xlsx_path, out_table)
    fields = [f.name for f in arcpy.ListFields(out_table) if f.type not in ('OID','Geometry','Blob','Raster')]
    with open(csv_path, 'w', newline='', encoding='utf-8') as f:
        w = csv.writer(f)
        w.writerow(fields)
        with arcpy.da.SearchCursor(out_table, fields) as cur:
            for row in cur:
                w.writerow(list(row))
    return out_table

def create_points_from_table(table, out_fc):
    fields, x_field, y_field, z_field = find_fields(table)
    if not (x_field and y_field and z_field):
        raise RuntimeError(f'Missing usable E/N/Z fields in {table}. Fields: {fields}')
    if arcpy.Exists(out_fc):
        arcpy.management.Delete(out_fc)
    gdb = os.path.dirname(out_fc)
    name = os.path.basename(out_fc)
    arcpy.management.CreateFeatureclass(gdb, name, 'POINT', spatial_reference=sr)
    arcpy.management.AddField(out_fc, 'SRC_OID', 'LONG')
    arcpy.management.AddField(out_fc, 'ZVAL', 'DOUBLE')
    inserted = 0
    with arcpy.da.SearchCursor(table, ['OID@', x_field, y_field, z_field]) as sc, \
         arcpy.da.InsertCursor(out_fc, ['SRC_OID', 'ZVAL', 'SHAPE@XY']) as ic:
        for oid, xv, yv, zv in sc:
            try:
                x = float(str(xv).replace(',', '').strip())
                y = float(str(yv).replace(',', '').strip())
                z = float(str(zv).replace(',', '').strip())
            except:
                continue
            ic.insertRow((oid, z, (x, y)))
            inserted += 1
    if inserted == 0:
        raise RuntimeError(f'No usable numeric E/N/Z rows found in {table}')
    return inserted, x_field, y_field, z_field

def derive_boundary_polygon(cad_gdb, out_poly):
    arcpy.conversion.CADToGeodatabase(boundary_dwg, cad_gdb, 'cadimport', 1000, sr)
    poly_fc = os.path.join(cad_gdb, 'cadimport', 'Polygon')
    pline_fc = os.path.join(cad_gdb, 'cadimport', 'Polyline')
    candidates = []
    if arcpy.Exists(poly_fc) and int(arcpy.management.GetCount(poly_fc)[0]) > 0:
        candidates.append(poly_fc)
    if arcpy.Exists(pline_fc) and int(arcpy.management.GetCount(pline_fc)[0]) > 0:
        candidates.append(pline_fc)
    if not candidates:
        raise RuntimeError('No polygon/polyline entities found in DWG boundary import')
    if arcpy.Exists(out_poly):
        arcpy.management.Delete(out_poly)
    # Prefer existing polygons; otherwise convert closed polylines to polygons
    if poly_fc in candidates:
        arcpy.management.CopyFeatures(poly_fc, out_poly)
    else:
        arcpy.management.FeatureToPolygon(pline_fc, out_poly)
    # Keep largest polygon as analysis boundary
    area_field = '__A'
    if area_field not in [f.name for f in arcpy.ListFields(out_poly)]:
        arcpy.management.AddField(out_poly, area_field, 'DOUBLE')
    arcpy.management.CalculateField(out_poly, area_field, '!shape.area!', 'PYTHON3')
    oid_field = arcpy.Describe(out_poly).OIDFieldName
    max_oid = None; max_a = -1
    with arcpy.da.SearchCursor(out_poly, [oid_field, area_field]) as cur:
        for oid, a in cur:
            if a is not None and a > max_a:
                max_a = a; max_oid = oid
    lyr = 'boundary_lyr'
    arcpy.management.MakeFeatureLayer(out_poly, lyr, f'{arcpy.AddFieldDelimiters(out_poly, oid_field)} = {max_oid}')
    tmp = out_poly + '_single'
    if arcpy.Exists(tmp):
        arcpy.management.Delete(tmp)
    arcpy.management.CopyFeatures(lyr, tmp)
    arcpy.management.Delete(out_poly)
    arcpy.management.Rename(tmp, out_poly)
    return out_poly

def run_idw(points_fc, z_field, out_raster, boundary_fc):
    ext = arcpy.Describe(boundary_fc).extent
    arcpy.env.extent = ext
    arcpy.env.mask = boundary_fc
    arcpy.env.outputCoordinateSystem = sr
    arcpy.env.cellSize = max((ext.width + ext.height) / 500.0, 1.0)
    try:
        if arcpy.Exists(out_raster):
            arcpy.management.Delete(out_raster)
    except:
        pass
    try:
        idw = arcpy.sa.Idw(points_fc, z_field)
        idw.save(out_raster)
    except arcpy.ExecuteError:
        msg = arcpy.GetMessages(2)
        if '010092' in msg or 'Invalid output extent' in msg:
            # repair extent: slightly expand, keep mask
            ext2 = arcpy.Extent(ext.XMin - 1, ext.YMin - 1, ext.XMax + 1, ext.YMax + 1)
            arcpy.env.extent = ext2
            idw = arcpy.sa.Idw(points_fc, z_field)
            idw.save(out_raster)
        else:
            raise

def add_to_map(aprx_path, datasets):
    try:
        aprx = arcpy.mp.ArcGISProject(aprx_path)
        m = aprx.listMaps()[0]
        existing = {lyr.name for lyr in m.listLayers()}
        for ds in datasets:
            if arcpy.Exists(ds):
                name = os.path.basename(ds)
                if name not in existing:
                    m.addDataFromPath(ds)
        aprx.save()
    except:
        pass

# =========================
# Main
# =========================
try:
    arcpy.CheckOutExtension('Spatial')
    ensure_dir(project_root)
    gdb = os.path.join(project_root, 'Iseni_Volume.gdb')
    cad_gdb = os.path.join(project_root, 'cad.gdb')
    if not arcpy.Exists(gdb):
        arcpy.management.CreateFileGDB(project_root, 'Iseni_Volume.gdb')
    if not arcpy.Exists(cad_gdb):
        arcpy.management.CreateFileGDB(project_root, 'cad.gdb')

    # create project if absent
    aprx_path = os.path.join(project_root, project_name + '.aprx')
    if not os.path.exists(aprx_path):
        arcpy.management.CreateProject(project_root, project_name, 'MAP')

    # Copy Excel data to CSV in workspace
    pre_csv = os.path.join(workspace, 'camp_site_pre.csv')
    post_csv = os.path.join(workspace, 'camp_site_post.csv')
    pre_sheet = excel_sheet_name(pre_xlsx)
    post_sheet = excel_sheet_name(post_xlsx)
    pre_tbl = excel_to_csv(pre_xlsx, pre_csv, pre_sheet)
    post_tbl = excel_to_csv(post_xlsx, post_csv, post_sheet)

    # Also import Excel tables into geodatabase for robust OID handling
    pre_gdb_tbl = os.path.join(gdb, 'pre_tbl')
    post_gdb_tbl = os.path.join(gdb, 'post_tbl')
    if arcpy.Exists(pre_gdb_tbl): arcpy.management.Delete(pre_gdb_tbl)
    if arcpy.Exists(post_gdb_tbl): arcpy.management.Delete(post_gdb_tbl)
    if pre_sheet:
        arcpy.conversion.ExcelToTable(pre_xlsx, pre_gdb_tbl, pre_sheet)
    else:
        arcpy.conversion.ExcelToTable(pre_xlsx, pre_gdb_tbl)
    if post_sheet:
        arcpy.conversion.ExcelToTable(post_xlsx, post_gdb_tbl, post_sheet)
    else:
        arcpy.conversion.ExcelToTable(post_xlsx, post_gdb_tbl)

    # Create point FCs
    pre_pts = os.path.join(gdb, 'PRE_points')
    post_pts = os.path.join(gdb, 'POST_points')
    pre_inserted, pre_x, pre_y, pre_z = create_points_from_table(pre_gdb_tbl, pre_pts)
    post_inserted, post_x, post_y, post_z = create_points_from_table(post_gdb_tbl, post_pts)

    # Boundary from DWG polygon/polyline
    boundary_fc = os.path.join(gdb, 'boundary_polygon')
    derive_boundary_polygon(cad_gdb, boundary_fc)

    # IDW rasters
    pre_idw = os.path.join(gdb, 'PRE_IDW')
    post_idw = os.path.join(gdb, 'POST_IDW')
    run_idw(pre_pts, 'ZVAL', pre_idw, boundary_fc)
    run_idw(post_pts, 'ZVAL', post_idw, boundary_fc)

    # CutFill
    arcpy.env.extent = arcpy.Describe(boundary_fc).extent
    arcpy.env.mask = boundary_fc
    arcpy.env.outputCoordinateSystem = sr
    cutfill = os.path.join(gdb, 'CutFill')
    if arcpy.Exists(cutfill):
        arcpy.management.Delete(cutfill)
    try:
        arcpy.sa.CutFill(pre_idw, post_idw).save(cutfill)
    except arcpy.ExecuteError:
        msg = arcpy.GetMessages(2)
        if '010092' in msg or 'Invalid output extent' in msg:
            ext = arcpy.Describe(boundary_fc).extent
            arcpy.env.extent = arcpy.Extent(ext.XMin - 1, ext.YMin - 1, ext.XMax + 1, ext.YMax + 1)
            arcpy.sa.CutFill(pre_idw, post_idw).save(cutfill)
        else:
            raise

    # Summarize cut/fill by raster cell values * cell area
    desc = arcpy.Describe(cutfill)
    cell_w = desc.meanCellWidth
    cell_h = desc.meanCellHeight
    cell_area = float(cell_w) * float(cell_h)
    total_volume = 0.0
    cut_volume = 0.0
    fill_volume = 0.0
    total_area = 0.0
    arr_fields = ['VALUE', 'COUNT']
    with arcpy.da.SearchCursor(cutfill, arr_fields) as cur:
        for val, cnt in cur:
            if val is None or cnt is None:
                continue
            vol = float(val) * float(cnt) * cell_area
            area = float(cnt) * cell_area
            total_volume += vol
            total_area += area
            if vol < 0:
                cut_volume += vol
            else:
                fill_volume += vol

    # Export CSV result
    with open(output_csv, 'w', newline='', encoding='utf-8') as f:
        w = csv.writer(f)
        w.writerow(['Metric', 'Value', 'Units'])
        w.writerow(['Pre_Point_Count', pre_inserted, 'points'])
        w.writerow(['Post_Point_Count', post_inserted, 'points'])
        w.writerow(['Analysis_Area', total_area, 'square_meters'])
        w.writerow(['Cut_Volume', cut_volume, 'cubic_meters'])
        w.writerow(['Fill_Volume', fill_volume, 'cubic_meters'])
        w.writerow(['Net_Volume_Post_minus_Pre', total_volume, 'cubic_meters'])
        w.writerow(['Coordinate_System', sr.name, ''])
        w.writerow(['Pre_CSV_Copy', pre_csv, ''])
        w.writerow(['Post_CSV_Copy', post_csv, ''])
        w.writerow(['Boundary_DWG', boundary_dwg, ''])

    add_to_map(aprx_path, [boundary_fc, pre_pts, post_pts, pre_idw, post_idw, cutfill])

    print(f'RESULT_PRE_POINT_COUNT: {pre_inserted}')
    print(f'RESULT_POST_POINT_COUNT: {post_inserted}')
    print(f'RESULT_ANALYSIS_AREA_SQM: {total_area}')
    print(f'RESULT_CUT_VOLUME_CUM: {cut_volume}')
    print(f'RESULT_FILL_VOLUME_CUM: {fill_volume}')
    print(f'RESULT_NET_VOLUME_CUM: {total_volume}')
    print(f'RESULT_OUTPUT_CSV: {output_csv}')
    print(f'RESULT_PRE_CSV_COPY: {pre_csv}')
    print(f'RESULT_POST_CSV_COPY: {post_csv}')
    print(f'RESULT_PROJECT_PATH: {aprx_path}')
    print(f'RESULT_CRS: {sr.name}')

except Exception as e:
    print('ERROR:', str(e))
    print(traceback.format_exc())
    raise
finally:
    try:
        arcpy.CheckInExtension('Spatial')
    except:
        pass

