# Generated by SurvyAI
# This script was dynamically generated based on user request
# Generated: 2026-04-03T12:39:15.039561
# 
# Execute this script in ArcGIS Pro's Python Window if needed:
# exec(open(r'C:\Users\UZOR\PycharmProjects\untitled\venv\SurvyAI\scripts\iseni_pre_post_cutfill_retry.py').read())

import arcpy, os, csv, math, traceback, sys, shutil
from openpyxl import load_workbook

pre_xlsx = r"C:/Users/USER/Documents/SPDC/ISENI/REPORT ON FRONT OF CAMP SITE AND ISENI WELL 2 AND 4 LOCATION/REVIEW/FRONT CAMP SITE/camp site pre.xlsx"
post_xlsx = r"C:/Users/USER/Documents/SPDC/ISENI/REPORT ON FRONT OF CAMP SITE AND ISENI WELL 2 AND 4 LOCATION/REVIEW/FRONT CAMP SITE/camp site post.xlsx"
boundary_dwg = r"C:/Users/USER/Documents/SPDC/ISENI/REPORT ON FRONT OF CAMP SITE AND ISENI WELL 2 AND 4 LOCATION/REVIEW/FRONT CAMP SITE/FRONT CAMP SITE 2 POST.dwg"
workspace = os.getcwd()
output_csv = os.path.join(workspace, 'Iseni_VolumeResult.csv')
pre_csv = os.path.join(workspace, 'camp_site_pre.csv')
post_csv = os.path.join(workspace, 'camp_site_post.csv')
project_name = 'Iseni_CutFill_Volume'
project_folder = workspace
project_path = os.path.join(project_folder, project_name + '.aprx')
gdb = os.path.join(project_folder, project_name + '.gdb')
sr = arcpy.SpatialReference(26391)

arcpy.env.overwriteOutput = True


def p(*args):
    print(*args)
    sys.stdout.flush()


def workbook_to_csv(xlsx_path, csv_path):
    wb = load_workbook(xlsx_path, data_only=True, read_only=True)
    ws = wb[wb.sheetnames[0]]
    with open(csv_path, 'w', newline='', encoding='utf-8-sig') as f:
        writer = csv.writer(f)
        for row in ws.iter_rows(values_only=True):
            writer.writerow(['' if v is None else v for v in row])
    return csv_path


def find_fields(table_path):
    fields = [f.name for f in arcpy.ListFields(table_path)]
    norm = {f.lower().replace('_','').replace(' ',''): f for f in fields}
    def pick(cands):
        for c in cands:
            key = c.lower().replace('_','').replace(' ','')
            if key in norm:
                return norm[key]
        for c in cands:
            key = c.lower().replace('_','').replace(' ','')
            for nk, orig in norm.items():
                if key in nk:
                    return orig
        return None
    return fields, pick(['e','east','easting','x']), pick(['n','north','northing','y']), pick(['z','elev','elevation','rl','level'])


def make_points(table_path, out_fc):
    fields, xf, yf, zf = find_fields(table_path)
    p('DEBUG_FIELDS', table_path, fields)
    if not xf or not yf or not zf:
        raise RuntimeError('Missing usable E/N/Z fields in {}. Fields={}'.format(table_path, fields))
    if arcpy.Exists(out_fc):
        arcpy.management.Delete(out_fc)
    folder, name = os.path.split(out_fc)
    arcpy.management.CreateFeatureclass(folder, name, 'POINT', spatial_reference=sr, has_z='ENABLED')
    arcpy.management.AddField(out_fc, 'SRC_OID', 'LONG')
    arcpy.management.AddField(out_fc, 'Z_VAL', 'DOUBLE')
    inserted = 0
    with arcpy.da.SearchCursor(table_path, ['OID@', xf, yf, zf]) as sc:
        with arcpy.da.InsertCursor(out_fc, ['SRC_OID', 'Z_VAL', 'SHAPE@XY', 'SHAPE@Z']) as ic:
            for oid, xv, yv, zv in sc:
                try:
                    x = float(str(xv).replace(',', '').strip())
                    y = float(str(yv).replace(',', '').strip())
                    z = float(str(zv).replace(',', '').strip())
                except:
                    continue
                ic.insertRow((oid, z, (x, y), z))
                inserted += 1
    return inserted, xf, yf, zf


def prepare_boundary():
    cad_name = 'cad_import'
    try:
        arcpy.conversion.CADToGeodatabase(boundary_dwg, gdb, cad_name, 1000, sr)
        cad_ds = os.path.join(gdb, cad_name)
        poly = os.path.join(cad_ds, 'Polygon')
        pline = os.path.join(cad_ds, 'Polyline')
        out_fc = os.path.join(gdb, 'boundary_polygon')
        if arcpy.Exists(out_fc):
            arcpy.management.Delete(out_fc)
        if arcpy.Exists(poly) and int(arcpy.management.GetCount(poly)[0]) > 0:
            arcpy.management.CopyFeatures(poly, out_fc)
        elif arcpy.Exists(pline) and int(arcpy.management.GetCount(pline)[0]) > 0:
            tmp = os.path.join(gdb, 'boundary_lines')
            if arcpy.Exists(tmp):
                arcpy.management.Delete(tmp)
            arcpy.management.CopyFeatures(pline, tmp)
            arcpy.management.FeatureToPolygon(tmp, out_fc)
        else:
            raise RuntimeError('DWG has no Polygon/Polyline data after CADToGeodatabase')
    except Exception:
        # fallback: direct CAD datasets
        poly = boundary_dwg + r'\Polygon'
        pline = boundary_dwg + r'\Polyline'
        out_fc = os.path.join(gdb, 'boundary_polygon')
        if arcpy.Exists(out_fc):
            arcpy.management.Delete(out_fc)
        if arcpy.Exists(poly) and int(arcpy.management.GetCount(poly)[0]) > 0:
            arcpy.management.CopyFeatures(poly, out_fc)
        elif arcpy.Exists(pline) and int(arcpy.management.GetCount(pline)[0]) > 0:
            tmp = os.path.join(gdb, 'boundary_lines')
            if arcpy.Exists(tmp):
                arcpy.management.Delete(tmp)
            arcpy.management.CopyFeatures(pline, tmp)
            arcpy.management.FeatureToPolygon(tmp, out_fc)
        else:
            raise RuntimeError('Could not derive polygon from DWG by either method')

    largest_oid = None
    max_area = -1
    oid_field = arcpy.Describe(out_fc).OIDFieldName
    with arcpy.da.SearchCursor(out_fc, [oid_field, 'SHAPE@AREA']) as cur:
        for oid, area in cur:
            if area and area > max_area:
                largest_oid = oid
                max_area = area
    if largest_oid is None:
        raise RuntimeError('No usable boundary polygon found')
    lyr = 'bnd_lyr'
    arcpy.management.MakeFeatureLayer(out_fc, lyr)
    arcpy.management.SelectLayerByAttribute(lyr, 'NEW_SELECTION', f"{arcpy.AddFieldDelimiters(out_fc, oid_field)} = {largest_oid}")
    single = os.path.join(gdb, 'boundary_polygon_single')
    if arcpy.Exists(single):
        arcpy.management.Delete(single)
    arcpy.management.CopyFeatures(lyr, single)
    return single


def set_env(poly_fc, expand=0.02):
    ext = arcpy.Describe(poly_fc).extent
    dx = max((ext.XMax - ext.XMin) * expand, 1.0)
    dy = max((ext.YMax - ext.YMin) * expand, 1.0)
    arcpy.env.extent = arcpy.Extent(ext.XMin - dx, ext.YMin - dy, ext.XMax + dx, ext.YMax + dy)
    arcpy.env.mask = poly_fc
    arcpy.env.outputCoordinateSystem = sr
    span = max(ext.XMax - ext.XMin, ext.YMax - ext.YMin)
    arcpy.env.cellSize = max(span / 200.0, 0.5)


def idw_run(points_fc, out_raster):
    if arcpy.Exists(out_raster):
        arcpy.management.Delete(out_raster)
    from arcpy.sa import Idw, ExtractByMask
    tmp = os.path.join(gdb, os.path.basename(out_raster) + '_tmp')
    if arcpy.Exists(tmp):
        arcpy.management.Delete(tmp)
    Idw(points_fc, 'Z_VAL').save(tmp)
    ExtractByMask(tmp, arcpy.env.mask).save(out_raster)
    return out_raster


def cutfill_run(pre_ras, post_ras, out_ras):
    from arcpy.sa import CutFill
    if arcpy.Exists(out_ras):
        arcpy.management.Delete(out_ras)
    CutFill(pre_ras, post_ras).save(out_ras)
    return out_ras


def export_results(cutfill_raster, csv_path):
    arcpy.management.BuildRasterAttributeTable(cutfill_raster, 'Overwrite')
    tbl = os.path.join(gdb, 'cutfill_table')
    if arcpy.Exists(tbl):
        arcpy.management.Delete(tbl)
    arcpy.conversion.TableToTable(cutfill_raster, gdb, 'cutfill_table')
    fields = [f.name for f in arcpy.ListFields(tbl)]
    val_field = next((f for f in fields if f.upper() == 'VALUE'), None)
    count_field = next((f for f in fields if f.upper() == 'COUNT'), None)
    if not val_field or not count_field:
        raise RuntimeError('Could not resolve VALUE/COUNT in cutfill table fields={}'.format(fields))
    cellx = float(arcpy.management.GetRasterProperties(cutfill_raster, 'CELLSIZEX')[0])
    celly = float(arcpy.management.GetRasterProperties(cutfill_raster, 'CELLSIZEY')[0])
    cell_area = cellx * celly
    total_area = total_net = total_cut = total_fill = 0.0
    rows = []
    with arcpy.da.SearchCursor(tbl, [val_field, count_field]) as cur:
        for val, cnt in cur:
            if val is None or cnt in (None, 0):
                continue
            area = float(cnt) * cell_area
            vol = float(val) * float(cnt) * cell_area
            total_area += area
            total_net += vol
            if vol < 0:
                total_cut += vol
            elif vol > 0:
                total_fill += vol
            rows.append((val, cnt, area, vol))
    with open(csv_path, 'w', newline='', encoding='utf-8-sig') as f:
        w = csv.writer(f)
        w.writerow(['metric', 'value'])
        w.writerow(['total_area_sq_m', total_area])
        w.writerow(['net_volume_cu_m', total_net])
        w.writerow(['cut_volume_cu_m', total_cut])
        w.writerow(['fill_volume_cu_m', total_fill])
        w.writerow([])
        w.writerow(['cutfill_value', 'cell_count', 'area_sq_m', 'volume_cu_m'])
        for r in rows:
            w.writerow(r)
    return total_area, total_net, total_cut, total_fill

try:
    p('START_WORKSPACE', workspace)
    p('START_PRE_XLSX', pre_xlsx)
    p('START_POST_XLSX', post_xlsx)
    p('START_DWG', boundary_dwg)

    if not os.path.exists(pre_xlsx):
        raise RuntimeError('PRE Excel not found: ' + pre_xlsx)
    if not os.path.exists(post_xlsx):
        raise RuntimeError('POST Excel not found: ' + post_xlsx)
    if not os.path.exists(boundary_dwg):
        raise RuntimeError('Boundary DWG not found: ' + boundary_dwg)

    arcpy.CheckOutExtension('Spatial')

    if not arcpy.Exists(gdb):
        arcpy.management.CreateFileGDB(project_folder, os.path.basename(gdb))
        p('CREATED_GDB', gdb)

    # Copy xlsx contents to csv in workspace
    workbook_to_csv(pre_xlsx, pre_csv)
    workbook_to_csv(post_xlsx, post_csv)
    p('RESULT_PRE_CSV:', pre_csv)
    p('RESULT_POST_CSV:', post_csv)

    # Import csv to gdb table
    pre_table = os.path.join(gdb, 'pre_table')
    post_table = os.path.join(gdb, 'post_table')
    if arcpy.Exists(pre_table): arcpy.management.Delete(pre_table)
    if arcpy.Exists(post_table): arcpy.management.Delete(post_table)
    arcpy.conversion.TableToTable(pre_csv, gdb, 'pre_table')
    arcpy.conversion.TableToTable(post_csv, gdb, 'post_table')
    p('IMPORTED_TABLES')

    pre_points = os.path.join(gdb, 'pre_points')
    post_points = os.path.join(gdb, 'post_points')
    pre_count, pre_xf, pre_yf, pre_zf = make_points(pre_table, pre_points)
    post_count, post_xf, post_yf, post_zf = make_points(post_table, post_points)
    p('RESULT_PRE_POINTS_INSERTED:', pre_count)
    p('RESULT_POST_POINTS_INSERTED:', post_count)
    p('RESULT_PRE_FIELDS:', pre_xf, pre_yf, pre_zf)
    p('RESULT_POST_FIELDS:', post_xf, post_yf, post_zf)
    if pre_count <= 0 or post_count <= 0:
        raise RuntimeError('No usable PRE/POST points inserted')

    boundary_single = prepare_boundary()
    p('RESULT_BOUNDARY_FC:', boundary_single)

    set_env(boundary_single, 0.02)
    pre_idw = os.path.join(gdb, 'pre_idw')
    post_idw = os.path.join(gdb, 'post_idw')
    try:
        idw_run(pre_points, pre_idw)
        idw_run(post_points, post_idw)
    except arcpy.ExecuteError:
        em = arcpy.GetMessages(2)
        p('IDW_ERROR_MSG', em)
        if '010092' in em or 'Invalid output extent' in em:
            set_env(boundary_single, 0.10)
            idw_run(pre_points, pre_idw)
            idw_run(post_points, post_idw)
        else:
            raise
    p('RESULT_PRE_IDW:', pre_idw)
    p('RESULT_POST_IDW:', post_idw)

    cutfill = os.path.join(gdb, 'cutfill')
    try:
        cutfill_run(pre_idw, post_idw, cutfill)
    except arcpy.ExecuteError:
        em = arcpy.GetMessages(2)
        p('CUTFILL_ERROR_MSG', em)
        if '010092' in em or 'Invalid output extent' in em:
            set_env(boundary_single, 0.10)
            cutfill_run(pre_idw, post_idw, cutfill)
        else:
            raise
    p('RESULT_CUTFILL:', cutfill)

    area, net_vol, cut_vol, fill_vol = export_results(cutfill, output_csv)
    p('RESULT_OUTPUT_CSV:', output_csv)
    p('RESULT_AREA_SQ_M:', area)
    p('RESULT_NET_VOLUME_CU_M:', net_vol)
    p('RESULT_CUT_VOLUME_CU_M:', cut_vol)
    p('RESULT_FILL_VOLUME_CU_M:', fill_vol)

except Exception as e:
    p('ERROR:', str(e))
    p(traceback.format_exc())
    raise
finally:
    try:
        arcpy.CheckInExtension('Spatial')
    except:
        pass
