# Generated by SurvyAI
# This script was dynamically generated based on user request
# Generated: 2026-02-13T09:04:53.752544
# 
# Execute this script in ArcGIS Pro's Python Window if needed:
# exec(open(r'C:\Users\UZOR\PycharmProjects\untitled\venv\SurvyAI\scripts\survyai_script_20260213_090453.py').read())

import arcpy, os

# Input parameters
excel_path = r'C:\Users\UZOR\PycharmProjects\untitled\venv\SurvyAI\WELL 8 TOPO DATA.xlsx'
project_folder = os.path.dirname(excel_path)
project_name = 'WELL_8_TOPO_VOLUME'
project_path = os.path.join(project_folder, project_name + '.aprx')
output_results_excel = os.path.join(project_folder, 'results_fill.xlsx')

# Coordinate system: Nigerian Mid-Belt Projection (Minna / Nigeria Mid Belt)
spatial_ref = arcpy.SpatialReference('Minna / Nigeria Mid Belt')

arcpy.env.overwriteOutput = True

# Create a new File GDB for this analysis
gdb_path = os.path.join(project_folder, project_name + '.gdb')
if not arcpy.Exists(gdb_path):
    arcpy.management.CreateFileGDB(project_folder, project_name + '.gdb')

# Step 1: Read Excel to table
excel_table = os.path.join(gdb_path, 'topo_points')
if arcpy.Exists(excel_table):
    arcpy.management.Delete(excel_table)

arcpy.conversion.ExcelToTable(excel_path, excel_table, 'WELL 8 TOPO')

# Discover fields
fields = [f.name for f in arcpy.ListFields(excel_table)]

# Map columns: chainages, Eastings, Northings, Height
x_field = 'Eastings'
y_field = 'Northings'
z_field = 'Height'

# Step 2: Create point feature class from table
points_fc = os.path.join(gdb_path, 'topo_points_fc')
if arcpy.Exists(points_fc):
    arcpy.management.Delete(points_fc)

arcpy.management.CreateFeatureclass(gdb_path, 'topo_points_fc', 'POINT', spatial_reference=spatial_ref)
arcpy.management.AddField(points_fc, 'Z', 'DOUBLE')

with arcpy.da.SearchCursor(excel_table, [x_field, y_field, z_field]) as sc, \
     arcpy.da.InsertCursor(points_fc, ['SHAPE@XY', 'Z']) as ic:
    for x_raw, y_raw, z_raw in sc:
        if x_raw is None or y_raw is None or z_raw is None:
            continue
        try:
            x = float(str(x_raw).replace(',', ''))
            y = float(str(y_raw).replace(',', ''))
            z = float(str(z_raw).replace(',', ''))
        except:
            continue
        ic.insertRow(((x, y), z))

# At this point, we only have one topo surface (no explicit Pre-fill/Post-fill separation in the workbook headers).
# Since the user requested Pre-fill and Post-fill volumes but the Excel file only has a single set of heights,
# we cannot reliably separate them into distinct surfaces without additional information.

print('RESULT_ERROR: The Excel file WELL 8 TOPO DATA.xlsx contains only one height field ("Height") and no distinct Pre-fill/Post-fill datasets.')
print('RESULT_ERROR_DETAIL: To compute Cut/Fill volume, the data must include separate Pre-fill and Post-fill height values or separate tables/sheets.')

