# Generated by SurvyAI
# This script was dynamically generated based on user request
# Generated: 2026-03-29T10:06:04.643115
# 
# Execute this script in ArcGIS Pro's Python Window if needed:
# exec(open(r'C:\Users\UZOR\PycharmProjects\untitled\venv\SurvyAI\scripts\survyai_script_20260329_100604.py').read())

import arcpy, os, csv

# Define source CSV paths
pre_csv = r'C:\Users\USER\Documents\SPDC\ADIBAWA WELL 13\Adibawa WELL 13A BORROWPIT-Contractor\ADIBAWA WELL 13 BORROW PIT VOLUME COMPUTATION_074938\csv_adibawa__020416_0411510.csv'
post_csv = r'C:\Users\USER\Documents\SPDC\ADIBAWA WELL 13\Adibawa WELL 13A BORROWPIT-Contractor\ADIBAWA WELL 13 BORROW PIT VOLUME COMPUTATION_074938\csv_Adi post_031618_062229.csv'

# Workspace in SurvyAI folder (use user's Documents as base)
base_workspace = os.path.join(os.path.expanduser('~'), 'Documents', 'SurvyAI')
os.makedirs(base_workspace, exist_ok=True)

pre_copy = os.path.join(base_workspace, 'pre_adibawa.csv')
post_copy = os.path.join(base_workspace, 'post_adibawa.csv')

# Copy CSVs to workspace
for src, dst in [(pre_csv, pre_copy), (post_csv, post_copy)]:
    with open(src, 'r', newline='', encoding='utf-8') as f_in, open(dst, 'w', newline='', encoding='utf-8') as f_out:
        reader = csv.reader(f_in)
        writer = csv.writer(f_out)
        for row in reader:
            writer.writerow(row)

print('RESULT_CSV_COPIES:', pre_copy, post_copy)

# Paths
aprx_path = os.path.join(base_workspace, 'Adibawa_Volume.aprx')

# If project doesn't exist, create a basic one
aif not os.path.exists(aprx_path):
    arcpy.mp.ArcGISProject('CURRENT')  # fallback; project will be created when run inside Pro

# Set environment
arcpy.env.workspace = base_workspace
arcpy.env.overwriteOutput = True

# Create file geodatabase
gdb = os.path.join(base_workspace, 'Adibawa_Volume.gdb')
if not arcpy.Exists(gdb):
    arcpy.management.CreateFileGDB(base_workspace, 'Adibawa_Volume.gdb')

# Import DWG polygon to get boundary
cad_path = r'C:\Users\USER\Documents\SPDC\ADIBAWA WELL 13\Adibawa WELL 13A BORROWPIT-Contractor\REVIEW\POST SURVEY FOR ADIBAWA WELL 13 BORROW PIT 13A RESTORATION.dwg'

cad_dataset = arcpy.conversion.CADToGeodatabase(cad_path, gdb, 'Adibawa_CAD', '2000', 'ByLayer')

# Assume polygon layer is the POLYGON feature class inside CAD dataset
cad_poly_fc = os.path.join(gdb, 'Adibawa_CAD', 'Polygon')

# Create a single-part polygon boundary (dissolve all)
boundary_fc = os.path.join(gdb, 'Adibawa_Boundary')
if arcpy.Exists(boundary_fc):
    arcpy.management.Delete(boundary_fc)

arcpy.management.Dissolve(cad_poly_fc, boundary_fc)

# Set environment from boundary polygon
desc = arcpy.Describe(boundary_fc)
arcpy.env.extent = desc.extent
arcpy.env.mask = boundary_fc
arcpy.env.outputCoordinateSystem = desc.spatialReference

# Helper to create points from CSV

def csv_to_points(csv_path, fc_name):
    table = os.path.join(gdb, fc_name + '_table')
    if arcpy.Exists(table):
        arcpy.management.Delete(table)
    arcpy.management.TableToTable(csv_path, gdb, fc_name + '_table')

    fields = [f.name for f in arcpy.ListFields(table)]
    # Try common names for E, N, Z
    def find_field(candidates):
        for c in candidates:
            for f in fields:
                if f.lower().replace(' ', '') == c.lower().replace(' ', ''):
                    return f
        return None

    x_field = find_field(['E', 'EASTING', 'X'])
    y_field = find_field(['N', 'NORTHING', 'Y'])
    z_field = find_field(['Z', 'ELEV', 'ELEVATION'])

    if not x_field or not y_field or not z_field:
        raise ValueError(f'Could not find E, N, Z fields in {csv_path}. Fields: {fields}')

    sr = desc.spatialReference
    points_fc = os.path.join(gdb, fc_name + '_points')
    if arcpy.Exists(points_fc):
        arcpy.management.Delete(points_fc)

    arcpy.management.CreateFeatureclass(gdb, fc_name + '_points', 'POINT', spatial_reference=sr)
    arcpy.management.AddField(points_fc, 'Z', 'DOUBLE')

    with arcpy.da.SearchCursor(table, [x_field, y_field, z_field]) as sc, \
         arcpy.da.InsertCursor(points_fc, ['SHAPE@XY', 'Z']) as ic:
        for x_raw, y_raw, z_raw in sc:
            try:
                x = float(str(x_raw).replace(',', ''))
                y = float(str(y_raw).replace(',', ''))
                z = float(str(z_raw).replace(',', ''))
                ic.insertRow(((x, y), z))
            except Exception:
                continue

    return points_fc

pre_points = csv_to_points(pre_copy, 'PRE')
post_points = csv_to_points(post_copy, 'POST')

print('RESULT_POINTS_CREATED:', pre_points, post_points)

# Create IDW rasters
cell_size = desc.extent.width / 200.0  # reasonable resolution

pre_idw = os.path.join(gdb, 'PRE_IDW')
post_idw = os.path.join(gdb, 'POST_IDW')

for pts, out_ras, z_field in [(pre_points, pre_idw, 'Z'), (post_points, post_idw, 'Z')]:
    if arcpy.Exists(out_ras):
        arcpy.management.Delete(out_ras)
    arcpy.sa.Idw(pts, z_field, cell_size).save(out_ras)

print('RESULT_RASTERS_CREATED:', pre_idw, post_idw)

# CutFill
cutfill_ras = os.path.join(gdb, 'CutFill_PRE_POST')
if arcpy.Exists(cutfill_ras):
    arcpy.management.Delete(cutfill_ras)

cf = arcpy.sa.CutFill(pre_idw, post_idw)
cf.save(cutfill_ras)

# Calculate volume within boundary (fill positive, cut negative)
# Convert raster to polygon with ZONES for positive/negative

pos_raster = arcpy.sa.SetNull(cutfill_ras, cutfill_ras, 'VALUE <= 0')
neg_raster = arcpy.sa.SetNull(cutfill_ras, cutfill_ras, 'VALUE > 0')

pos_poly = os.path.join(gdb, 'CutFill_Positive')
neg_poly = os.path.join(gdb, 'CutFill_Negative')
for p in [pos_poly, neg_poly]:
    if arcpy.Exists(p):
        arcpy.management.Delete(p)

arcpy.conversion.RasterToPolygon(pos_raster, pos_poly, 'NO_SIMPLIFY', 'VALUE')
arcpy.conversion.RasterToPolygon(neg_raster, neg_poly, 'NO_SIMPLIFY', 'VALUE')

# Add AREA and VOLUME fields and compute for both
for poly_fc, sign in [(pos_poly, 1), (neg_poly, -1)]:
    if not arcpy.ListFields(poly_fc, 'AREA_SQM'):
        arcpy.management.AddField(poly_fc, 'AREA_SQM', 'DOUBLE')
    if not arcpy.ListFields(poly_fc, 'VOL_CUM', 'DOUBLE'):
        arcpy.management.AddField(poly_fc, 'VOL_CUM', 'DOUBLE')

    with arcpy.da.UpdateCursor(poly_fc, ['SHAPE@AREA', 'GRIDCODE', 'AREA_SQM', 'VOL_CUM']) as uc:
        for shp_area, gridcode, area_f, vol_f in uc:
            area = float(shp_area)
            vol = area * float(gridcode) * sign
            uc.updateRow((shp_area, gridcode, area, vol))

# Summarize volumes

fill_volume = 0.0
cut_volume = 0.0

with arcpy.da.SearchCursor(pos_poly, ['VOL_CUM']) as sc:
    for (v,) in sc:
        if v is not None:
            fill_volume += v

with arcpy.da.SearchCursor(neg_poly, ['VOL_CUM']) as sc:
    for (v,) in sc:
        if v is not None:
            cut_volume += v

net_volume = fill_volume + cut_volume

print('RESULT_FILL_VOLUME_M3:', fill_volume)
print('RESULT_CUT_VOLUME_M3:', cut_volume)
print('RESULT_NET_VOLUME_M3:', net_volume)

# Export to CSV in workspace
result_csv = os.path.join(base_workspace, 'Adibawa_VolumeResult.csv')
with open(result_csv, 'w', newline='') as f:
    w = csv.writer(f)
    w.writerow(['Metric', 'Value_m3'])
    w.writerow(['Fill_Volume', fill_volume])
    w.writerow(['Cut_Volume', cut_volume])
    w.writerow(['Net_Volume', net_volume])

print('RESULT_OUTPUT_CSV:', result_csv)

