# Generated by SurvyAI
# This script was dynamically generated based on user request
# Generated: 2026-02-13T09:11:01.976578
# 
# Execute this script in ArcGIS Pro's Python Window if needed:
# exec(open(r'C:\Users\UZOR\PycharmProjects\untitled\venv\SurvyAI\scripts\well8_fill_idw_cutfill.py').read())

import arcpy, os, math

excel_path = r"C:\Users\UZOR\PycharmProjects\untitled\venv\SurvyAI\WELL 8 POST DATA.xlsx"
workspace = os.path.dirname(excel_path)
project_name = "WELL_8_Fill_Volume_IDW"
project_folder = workspace
aprx_path = os.path.join(project_folder, f"{project_name}.aprx")

# Create a new project if it does not exist
if not os.path.exists(aprx_path):
    arcpy.mp.ArcGISProject("CURRENT")

# Environment
gdb_path = os.path.join(project_folder, f"{project_name}.gdb")
if not arcpy.Exists(gdb_path):
    arcpy.management.CreateFileGDB(project_folder, f"{project_name}.gdb")
arcpy.env.workspace = gdb_path
arcpy.env.overwriteOutput = True

# Convert Excel to table (ArcGIS version without sheet_name arg)
excel_table = os.path.join(gdb_path, "well8_table")
if arcpy.Exists(excel_table):
    arcpy.management.Delete(excel_table)
arcpy.conversion.ExcelToTable(excel_path, excel_table, "WELL 8 POST FILL DATA FINAL$")

# Discover fields
fields = [f.name for f in arcpy.ListFields(excel_table)]
# Expect: Eastings, Northings, post fill, pre fill
x_field = "Eastings"
y_field = "Northings"
post_field = "post fill"
pre_field = "pre fill"

# Create points feature class
sr = arcpy.SpatialReference("Minna / Nigeria Mid Belt")
points_fc = os.path.join(gdb_path, "well8_points")
if arcpy.Exists(points_fc):
    arcpy.management.Delete(points_fc)
arcpy.management.CreateFeatureclass(gdb_path, "well8_points", "POINT", spatial_reference=sr)
arcpy.management.AddField(points_fc, "Post", "DOUBLE")
arcpy.management.AddField(points_fc, "Pre", "DOUBLE")

with arcpy.da.SearchCursor(excel_table, [x_field, y_field, post_field, pre_field]) as sc, \
     arcpy.da.InsertCursor(points_fc, ["SHAPE@XY", "Post", "Pre"]) as ic:
    for x_raw, y_raw, post_raw, pre_raw in sc:
        try:
            x = float(str(x_raw).replace(",", ""))
            y = float(str(y_raw).replace(",", ""))
            post_z = float(str(post_raw).replace(",", "")) if post_raw not in (None, "") else None
            pre_z = float(str(pre_raw).replace(",", "")) if pre_raw not in (None, "") else None
        except Exception:
            continue
        ic.insertRow(((x, y), post_z, pre_z))

# Generate convex hull polygon strictly from POST points only (where Post is not null)
post_points_fc = os.path.join(gdb_path, "well8_post_points")
if arcpy.Exists(post_points_fc):
    arcpy.management.Delete(post_points_fc)
arcpy.analysis.Select(points_fc, post_points_fc, "Post IS NOT NULL")

poly_fc = os.path.join(gdb_path, "well8_post_hull")
if arcpy.Exists(poly_fc):
    arcpy.management.Delete(poly_fc)
arcpy.management.MinimumBoundingGeometry(post_points_fc, poly_fc, "CONVEX_HULL", group_option="ALL")

# Create IDW rasters for Post and Pre
cell_size = 1  # meters
mask_poly = poly_fc
arcpy.env.mask = mask_poly

post_raster = os.path.join(gdb_path, "post_idw")
pre_raster = os.path.join(gdb_path, "pre_idw")
for r in [post_raster, pre_raster]:
    if arcpy.Exists(r):
        arcpy.management.Delete(r)

arcpy.sa.Idw(post_points_fc, "Post", cell_size=cell_size).save(post_raster)
arcpy.sa.Idw(points_fc, "Pre", cell_size=cell_size).save(pre_raster)

# Cut-Fill (Post as surface, Pre as base)
cutfill_raster = os.path.join(gdb_path, "cutfill")
if arcpy.Exists(cutfill_raster):
    arcpy.management.Delete(cutfill_raster)

arcpy.sa.CutFill(post_raster, pre_raster).save(cutfill_raster)

# Summarize fill volume (positive value = fill)
fill_volume = 0.0
cell_area = cell_size * cell_size
with arcpy.da.SearchCursor(cutfill_raster, ["VALUE", "COUNT"]) as cur:
    for dz, count in cur:
        if dz is None:
            continue
        if dz > 0:
            fill_volume += dz * count * cell_area

# Export per-cell stats to Excel-like table, then to .xlsx
stats_table = os.path.join(gdb_path, "cutfill_stats")
if arcpy.Exists(stats_table):
    arcpy.management.Delete(stats_table)
arcpy.sa.ZonalStatisticsAsTable(mask_poly, "OBJECTID", cutfill_raster, stats_table, "DATA", "SUM")

# Export results to Excel in same folder
excel_out = os.path.join(workspace, "results_fill.xlsx")
if arcpy.Exists(excel_out):
    arcpy.management.Delete(excel_out)

arcpy.conversion.TableToExcel(stats_table, excel_out)

print("RESULT_FILL_VOLUME_CUBIC_METERS:", fill_volume)
print("RESULT_EXCEL_PATH:", excel_out)

